# ════════════════════════════════════════════════════════════════════
# CCTT Proof-Annotated Source — sympy
# Generated by Cohomological Cubical Type Theory Library Proof Orchestrator
#
# Every spec is a PATH THEOREM: Path(f(x), expected(x)) over {x : InputType}
# Every proof inhabits the path type.
# Every annotation is COMPILABLE: @cctt_verify JSON is machine-checkable.
#
# Trust levels:
#   🟢 KERNEL   — Refl / Z3 (machine-checked path)
#   🔵 MATHLIB  — Lean4/Mathlib theorem (proof-assistant verified path)
#   🟡 LIBRARY  — LibraryAxiom (sound if dependency correct)
#   🟠 INFERRED — LLM-selected strategy, checker-verified
#   🔴 ASSUMED  — explicitly assumed
#   ❌ FAILED   — proof did not compile
# ════════════════════════════════════════════════════════════════════

"""
This module defines base class for handlers and some core handlers:
``Q.commutative`` and ``Q.is_true``.
"""

from sympy.assumptions import Q, ask, AppliedPredicate
from sympy.core import Basic, Symbol
from sympy.core.logic import _fuzzy_group, fuzzy_and, fuzzy_or
from sympy.core.numbers import NaN, Number
from sympy.logic.boolalg import (And, BooleanTrue, BooleanFalse, conjuncts,
    Equivalent, Implies, Not, Or)
from sympy.utilities.exceptions import sympy_deprecation_warning

from ..predicates.common import CommutativePredicate, IsTruePredicate


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(AskHandler(*args), correctly constructs a AskHandler instance) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ AskHandler : Any → Any                                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | e14a7bf7094e6e54  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.AskHandler","kind":"class","src_hash":"035698671004936d","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"AskHandler(*args)","rhs":"correctly constructs a AskHandler instance","over":{"base":"Any"},"name":"AskHandler_class_invariant"},"guarantee":"correctly constructs a AskHandler instance","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"e14a7bf7094e6e54","spec_source":"static","formal_spec":{"source":"static","strength":"trivial"},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":false,"binding_errors":["Function AskHandler not found in source"]}}
class AskHandler:
    """Base class that all Ask Handlers must inherit."""
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__new__(cls, *args, **kwargs), super().__new__(cls, *args, **kwargs)) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  super().__new__(cls, *args, **kwargs)          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __new__ : Any → Any                                        ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | bd23116f5b8eb6a9           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.AskHandler.__new__","kind":"method","src_hash":"5e64a6f4bb0c65e9","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__new__(cls, *args, **kwargs)","rhs":"super().__new__(cls, *args, **kwargs)","over":{"base":"Any"},"name":"__new___correct"},"guarantee":"returns super().__new__(cls, *args, **kwargs)","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"bd23116f5b8eb6a9","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"super().__new__(cls, *args, **kwargs)","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def __new__(cls, *args, **kwargs):
        sympy_deprecation_warning(
            """
            The AskHandler system is deprecated. The AskHandler class should
            be replaced with the multipledispatch handler of Predicate
            """,
            deprecated_since_version="1.8",
            active_deprecations_target='deprecated-askhandler',
        )
        return super().__new__(cls, *args, **kwargs)


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(CommonHandler(*args), correctly constructs a CommonHandler instance) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  isinstance(self, AskHandler)                   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ CommonHandler : Any → {Any | result satisfies: isinst...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 464701db45393818  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.CommonHandler","kind":"class","src_hash":"fa4be68df33ddfbd","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: isinstance(self, AskHandler)"},"spec":{"lhs":"CommonHandler(*args)","rhs":"correctly constructs a CommonHandler instance","over":{"base":"Any"},"name":"CommonHandler_class_invariant"},"guarantee":"isinstance(self, AskHandler)","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"464701db45393818","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["isinstance(self, AskHandler)"]},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":false,"binding_errors":["Function CommonHandler not found in source"]}}
class CommonHandler(AskHandler):
    # Deprecated
    """Defines some useful methods common to most Handlers. """

    @staticmethod
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(AlwaysTrue(expr, assumptions), True) over Any         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  True                                           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ AlwaysTrue : Any → Any                                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 3c626f7c6e0cb9c9           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.CommonHandler.AlwaysTrue","kind":"staticmethod","src_hash":"ed720a0620fff015","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"AlwaysTrue(expr, assumptions)","rhs":"True","over":{"base":"Any"},"name":"AlwaysTrue_correct"},"guarantee":"returns True","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"3c626f7c6e0cb9c9","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"True","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def AlwaysTrue(expr, assumptions):
        return True

    @staticmethod
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(AlwaysFalse(expr, assumptions), False) over Any       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  False                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ AlwaysFalse : Any → Any                                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 8dcfe4d8b39e2f96           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.CommonHandler.AlwaysFalse","kind":"staticmethod","src_hash":"29a0fbe15ee871ef","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"AlwaysFalse(expr, assumptions)","rhs":"False","over":{"base":"Any"},"name":"AlwaysFalse_correct"},"guarantee":"returns False","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"8dcfe4d8b39e2f96","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"False","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def AlwaysFalse(expr, assumptions):
        return False

    @staticmethod
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(AlwaysNone(expr, assumptions), None) over Any         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  None                                           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ AlwaysNone : Any → Any                                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 9f0f684e1ac486be           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.CommonHandler.AlwaysNone","kind":"staticmethod","src_hash":"45cd2c76126fa8c0","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"AlwaysNone(expr, assumptions)","rhs":"None","over":{"base":"Any"},"name":"AlwaysNone_correct"},"guarantee":"returns None","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"9f0f684e1ac486be","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"None","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def AlwaysNone(expr, assumptions):
        return None

    NaN = AlwaysFalse


# CommutativePredicate

@CommutativePredicate.register(Symbol)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), <unspecified:_>) over {Any | hasattr(expr, 'is_commutative')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   requires: hasattr(expr, 'is_commutative')                ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : {Any | hasattr(expr, 'is_commutative')} → Any          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | dd69a834c86a2e63  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"377a47088732efef","in":{"base":"Any","pred":"hasattr(expr, 'is_commutative')"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"<unspecified:_>","over":{"base":"Any","pred":"hasattr(expr, 'is_commutative')"},"name":"__correct"},"guarantee":"objects are expected to be commutative unless otherwise stated","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.__correct","statement":"Path(_(x), objects are expected to be commutative unless otherwise stated)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"dd69a834c86a2e63","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","requires":["hasattr(expr, 'is_commutative')"],"pure":false,"effects":{"effect_type":"reads_state","reads":["expr.is_commutative"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def _(expr, assumptions):
    """Objects are expected to be commutative unless otherwise stated"""
    assumps = conjuncts(assumptions)
    if expr.is_commutative is not None:
        return expr.is_commutative and not ~Q.commutative(expr) in assumps
    if Q.commutative(expr) in assumps:
        return True
    elif ~Q.commutative(expr) in assumps:
        return False
    return True

@CommutativePredicate.register(Basic)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), <unspecified:_>) over {Any | hasattr(expr, 'args')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   requires: hasattr(expr, 'args')                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : {Any | hasattr(expr, 'args')} → Any                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | d7413087d4461a8d  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"0d45c6f7bde1c1b7","in":{"base":"Any","pred":"hasattr(expr, 'args')"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"<unspecified:_>","over":{"base":"Any","pred":"hasattr(expr, 'args')"},"name":"__correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.__correct","statement":"Path(_(x), internal helper behaves correctly)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"d7413087d4461a8d","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","requires":["hasattr(expr, 'args')"],"pure":false,"effects":{"effect_type":"reads_state","reads":["expr.args"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def _(expr, assumptions):
    for arg in expr.args:
        if not ask(Q.commutative(arg), assumptions):
            return False
    return True

@CommutativePredicate.register(Number)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), True) over Any                  ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  True                                           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : Any → Any                                              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | f23bbcfdf77ff919           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"ae12acfea890b2e1","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"True","over":{"base":"Any"},"name":"__correct"},"guarantee":"returns True","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"f23bbcfdf77ff919","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"True","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":true}}
def _(expr, assumptions):
    return True

@CommutativePredicate.register(NaN)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), True) over Any                  ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  True                                           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : Any → Any                                              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | f23bbcfdf77ff919           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"ae12acfea890b2e1","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"True","over":{"base":"Any"},"name":"__correct"},"guarantee":"returns True","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"f23bbcfdf77ff919","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"True","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":true}}
def _(expr, assumptions):
    return True


# IsTruePredicate

@IsTruePredicate.register(bool)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), expr) over Any                  ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  result == expr                                 ║
# ║   returns:  expr                                           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : Any → {Any | result satisfies: result == (expr)}       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 53ec88d153f8407d           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"feec2f31b191e90f","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: result == (expr)"},"spec":{"lhs":"_(expr, assumptions)","rhs":"expr","over":{"base":"Any"},"name":"__correct"},"guarantee":"returns expr; result == expr","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"53ec88d153f8407d","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["result == expr"],"returns_expr":"expr","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":true}}
def _(expr, assumptions):
    return expr

@IsTruePredicate.register(BooleanTrue)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), True) over Any                  ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  True                                           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : Any → Any                                              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | f23bbcfdf77ff919           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"ae12acfea890b2e1","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"True","over":{"base":"Any"},"name":"__correct"},"guarantee":"returns True","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"f23bbcfdf77ff919","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"True","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":true}}
def _(expr, assumptions):
    return True

@IsTruePredicate.register(BooleanFalse)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), False) over Any                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  False                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : Any → Any                                              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 8db9577e16149318           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"e8576061ef4c1c0d","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"False","over":{"base":"Any"},"name":"__correct"},"guarantee":"returns False","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"8db9577e16149318","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"False","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":true}}
def _(expr, assumptions):
    return False

@IsTruePredicate.register(AppliedPredicate)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), ask(expr, assumptions)) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  ask(expr, assumptions)                         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : Any → Any                                              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 2aee50de48670d6b           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"592adf1c69f28833","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"ask(expr, assumptions)","over":{"base":"Any"},"name":"__correct"},"guarantee":"returns ask(expr, assumptions)","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"2aee50de48670d6b","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"ask(expr, assumptions)","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":true}}
def _(expr, assumptions):
    return ask(expr, assumptions)

@IsTruePredicate.register(Not)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), <unspecified:_>) over {Any | hasattr(expr, 'args')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   requires: hasattr(expr, 'args')                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : {Any | hasattr(expr, 'args')} → Any                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 4651fdb707504875  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"0b92326fa806f2f6","in":{"base":"Any","pred":"hasattr(expr, 'args')"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"<unspecified:_>","over":{"base":"Any","pred":"hasattr(expr, 'args')"},"name":"__correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.__correct","statement":"Path(_(x), internal helper behaves correctly)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"4651fdb707504875","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","requires":["hasattr(expr, 'args')"],"pure":false,"effects":{"effect_type":"reads_state","reads":["expr.args"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def _(expr, assumptions):
    arg = expr.args[0]
    if arg.is_Symbol:
        # symbol used as abstract boolean object
        return None
    value = ask(arg, assumptions=assumptions)
    if value in (True, False):
        return not value
    else:
        return None

@IsTruePredicate.register(Or)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), <unspecified:_>) over {Any | hasattr(expr, 'args')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   requires: hasattr(expr, 'args')                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : {Any | hasattr(expr, 'args')} → Any                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | a117de5812d50d74  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"bbb9bff69e92d18d","in":{"base":"Any","pred":"hasattr(expr, 'args')"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"<unspecified:_>","over":{"base":"Any","pred":"hasattr(expr, 'args')"},"name":"__correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.__correct","statement":"Path(_(x), internal helper behaves correctly)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"a117de5812d50d74","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","requires":["hasattr(expr, 'args')"],"pure":false,"effects":{"effect_type":"reads_state","reads":["expr.args"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def _(expr, assumptions):
    result = False
    for arg in expr.args:
        p = ask(arg, assumptions=assumptions)
        if p is True:
            return True
        if p is None:
            result = None
    return result

@IsTruePredicate.register(And)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), <unspecified:_>) over {Any | hasattr(expr, 'args')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   requires: hasattr(expr, 'args')                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : {Any | hasattr(expr, 'args')} → Any                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | a85f8df92205cec8  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"729786a93acb62a2","in":{"base":"Any","pred":"hasattr(expr, 'args')"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"<unspecified:_>","over":{"base":"Any","pred":"hasattr(expr, 'args')"},"name":"__correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.__correct","statement":"Path(_(x), internal helper behaves correctly)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"a85f8df92205cec8","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","requires":["hasattr(expr, 'args')"],"pure":false,"effects":{"effect_type":"reads_state","reads":["expr.args"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def _(expr, assumptions):
    result = True
    for arg in expr.args:
        p = ask(arg, assumptions=assumptions)
        if p is False:
            return False
        if p is None:
            result = None
    return result

@IsTruePredicate.register(Implies)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), ask(~p | q, assumptions=assumptions)) over {Any | hasattr(expr, 'args')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   requires: hasattr(expr, 'args')                          ║
# ║   returns:  ask(~p | q, assumptions=assumptions)           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : {Any | hasattr(expr, 'args')} → Any                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.0ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 7824403d50c73307  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"ef5eb7d37d2ba6eb","in":{"base":"Any","pred":"hasattr(expr, 'args')"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"ask(~p | q, assumptions=assumptions)","over":{"base":"Any","pred":"hasattr(expr, 'args')"},"name":"__correct"},"guarantee":"returns ask(~p | q, assumptions=assumptions)","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.__correct","statement":"Path(_(x), returns ask(~p | q, assumptions=assumptions))"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"7824403d50c73307","spec_source":"static","formal_spec":{"source":"static","strength":"formal","requires":["hasattr(expr, 'args')"],"returns_expr":"ask(~p | q, assumptions=assumptions)","pure":false,"effects":{"effect_type":"reads_state","reads":["expr.args"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.0,"verdict_class":"assumed","binding":true}}
def _(expr, assumptions):
    p, q = expr.args
    return ask(~p | q, assumptions=assumptions)

@IsTruePredicate.register(Equivalent)
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_(expr, assumptions), <unspecified:_>) over {Any | hasattr(expr, 'args')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   requires: hasattr(expr, 'args')                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _ : {Any | hasattr(expr, 'args')} → Any                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | ec4ac032b752d4d3  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common._","kind":"function","src_hash":"06cd6be231e9a94c","in":{"base":"Any","pred":"hasattr(expr, 'args')"},"out":{"base":"Any"},"spec":{"lhs":"_(expr, assumptions)","rhs":"<unspecified:_>","over":{"base":"Any","pred":"hasattr(expr, 'args')"},"name":"__correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.__correct","statement":"Path(_(x), internal helper behaves correctly)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"ec4ac032b752d4d3","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","requires":["hasattr(expr, 'args')"],"pure":false,"effects":{"effect_type":"reads_state","reads":["expr.args"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def _(expr, assumptions):
    p, q = expr.args
    pt = ask(p, assumptions=assumptions)
    if pt is None:
        return None
    qt = ask(q, assumptions=assumptions)
    if qt is None:
        return None
    return pt == qt


#### Helper methods
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_closed_group(expr, assumptions, key), _fuzzy_group((ask(key(a), assumptions) for a in expr.args), quick_exit=True)) over {Any | hasattr(expr, 'args')} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   requires: hasattr(expr, 'args')                          ║
# ║   returns:  _fuzzy_group((ask(key(a), assumptions) fo...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_closed_group : {Any | hasattr(expr, 'args')} → Any    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | dc5949969be2a1b5  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.test_closed_group","kind":"function","src_hash":"4933e93a47c93193","in":{"base":"Any","pred":"hasattr(expr, 'args')"},"out":{"base":"Any"},"spec":{"lhs":"test_closed_group(expr, assumptions, key)","rhs":"_fuzzy_group((ask(key(a), assumptions) for a in expr.args), quick_exit=True)","over":{"base":"Any","pred":"hasattr(expr, 'args')"},"name":"test_closed_group_correct"},"guarantee":"returns _fuzzy_group((ask(key(a), assumptions) for a in expr.args), quick_exit=True)","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.test_closed_group_correct","statement":"Path(test_closed_group(x), returns _fuzzy_group((ask(key(a), assumptions) for a in expr.args), quick_exit=True))"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"dc5949969be2a1b5","spec_source":"static","formal_spec":{"source":"static","strength":"formal","requires":["hasattr(expr, 'args')"],"returns_expr":"_fuzzy_group((ask(key(a), assumptions) for a in expr.args), quick_exit=True)","pure":false,"effects":{"effect_type":"reads_state","reads":["expr.args"]}},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_closed_group(expr, assumptions, key):
    """
    Test for membership in a group with respect
    to the current operation.
    """
    return _fuzzy_group(
        (ask(key(a), assumptions) for a in expr.args), quick_exit=True)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(ask_all(*queries, assumptions), fuzzy_and((ask(query, assumptions) for query in queries))) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  fuzzy_and((ask(query, assumptions) for qu...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ ask_all : Any → Any                                        ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 952a249df0d4844f  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.ask_all","kind":"function","src_hash":"80e7233bf5badbe4","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"ask_all(*queries, assumptions)","rhs":"fuzzy_and((ask(query, assumptions) for query in queries))","over":{"base":"Any"},"name":"ask_all_correct"},"guarantee":"returns fuzzy_and((ask(query, assumptions) for query in queries))","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.ask_all_correct","statement":"Path(ask_all(x), returns fuzzy_and((ask(query, assumptions) for query in queries)))"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"952a249df0d4844f","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"fuzzy_and((ask(query, assumptions) for query in queries))","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":false,"binding_errors":["Param mismatch: code=[], spec=['*queries', 'assumptions']"]}}
def ask_all(*queries, assumptions):
    return fuzzy_and(
        (ask(query, assumptions) for query in queries))

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(ask_any(*queries, assumptions), fuzzy_or((ask(query, assumptions) for query in queries))) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  fuzzy_or((ask(query, assumptions) for que...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ ask_any : Any → Any                                        ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | f87c3c71c3d4cc94  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.assumptions.handlers.common.ask_any","kind":"function","src_hash":"7bef7c141f74c3d9","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"ask_any(*queries, assumptions)","rhs":"fuzzy_or((ask(query, assumptions) for query in queries))","over":{"base":"Any"},"name":"ask_any_correct"},"guarantee":"returns fuzzy_or((ask(query, assumptions) for query in queries))","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.assumptions.handlers.common.ask_any_correct","statement":"Path(ask_any(x), returns fuzzy_or((ask(query, assumptions) for query in queries)))"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"f87c3c71c3d4cc94","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"fuzzy_or((ask(query, assumptions) for query in queries))","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":false,"binding_errors":["Param mismatch: code=[], spec=['*queries', 'assumptions']"]}}
def ask_any(*queries, assumptions):
    return fuzzy_or(
        (ask(query, assumptions) for query in queries))
