"""DepPy types — sheaf-descent semantic typing for Python.

This package provides a complete type system including:
- Base Python types and container types  (:mod:`.base`)
- Type variables and unification          (:mod:`.variables`)
- Refinement types ``{v: τ | φ}``        (:mod:`.refinement`)
- Dependent types (Π, Σ, indexed families)(:mod:`.dependent`)
- Subtyping checker                       (:mod:`.subtyping`)
- Carrier types for sheaf sections        (:mod:`.carriers`)
- Indexed type families                   (:mod:`.indexed`)
- Witness-bearing result types            (:mod:`.witnesses`)
"""
from __future__ import annotations

# ── base types ─────────────────────────────────────────────────────────────
from .base import (
    TypeBase,
    PrimitiveKind,
    PrimitiveType,
    AnyType,
    NeverType,
    ListType,
    DictType,
    TupleType,
    SetType,
    FrozenSetType,
    OptionalType,
    UnionType,
    IntersectionType,
    CallableType,
    ClassType,
    ProtocolMember,
    ProtocolType,
    ModuleType,
    LiteralType,
    TypeAliasType,
    TensorType,
    # Singletons
    INT_TYPE,
    FLOAT_TYPE,
    STR_TYPE,
    BOOL_TYPE,
    BYTES_TYPE,
    NONE_TYPE,
    COMPLEX_TYPE,
    ANY_TYPE,
    NEVER_TYPE,
    # Utilities
    type_from_python,
    type_join,
    type_meet,
)

# ── variables ──────────────────────────────────────────────────────────────
from .variables import (
    Variance,
    TypeVariable,
    RowVariable,
    SkolemVariable,
    ExistentialVariable,
    UnificationError,
    UnificationState,
)

# ── refinement types ───────────────────────────────────────────────────────
from .refinement import (
    Predicate,
    TruePred,
    FalsePred,
    ComparisonOp,
    ComparisonPred,
    NotPred,
    ConjunctionPred,
    DisjunctionPred,
    ImplicationPred,
    VarPred,
    IsInstancePred,
    IsNonePred,
    IsNotNonePred,
    MembershipPred,
    LengthPred,
    CallPred,
    RefinementType,
    Qualifier,
    NonNull,
    Positive,
    NonNegative,
    Negative,
    NonEmpty,
    Sorted,
    Unique,
    Bounded,
    MaxLength,
    MinLength,
    Immutable,
    Trusted,
    QualifiedType,
    refine,
    positive_int,
    non_negative_int,
    bounded_int,
    non_empty_list,
    non_null,
)

# ── dependent types ────────────────────────────────────────────────────────
from .dependent import (
    PiType,
    MultiPiType,
    SigmaType,
    IndexedFamily,
    WitnessType,
    IdentityType,
    ForallType,
    ExistsType,
    DependentRecordType,
    telescope_to_pi,
    telescope_to_sigma,
)

# ── subtyping ──────────────────────────────────────────────────────────────
from .subtyping import (
    VCKind,
    VerificationCondition,
    SubtypingResult,
    SubtypingChecker,
    is_subtype,
    check_subtype,
    are_equivalent,
)

# ── carriers ───────────────────────────────────────────────────────────────
from .carriers import (
    CarrierType,
    SchemaConstraint,
    CarrierSchema,
    CarrierProjection,
    MergeStrategy,
    CarrierMerger,
    carriers_compatible,
    carrier_from_type,
)

# ── indexed type families ──────────────────────────────────────────────────
from .indexed import (
    TypeFamily,
    FamilyApplication,
    ConstantFamily,
    TypeFamilyComposition,
    DependentRecord,
    IndexedUnion,
    IndexedIntersection,
)

# ── witnesses ──────────────────────────────────────────────────────────────
from .witnesses import (
    ProofTerm,
    ReflProof,
    AssumptionProof,
    RuntimeCheckProof,
    StaticProof,
    CompositeProof,
    TransitivityProof,
    SymmetryProof,
    CongruenceProof,
    WitnessCarrier,
    ExistentialWitness,
    TransportWitness,
    RefinementWitness,
    CompositeWitness,
    WitnessRegistry,
)

__all__ = [
    # base
    "TypeBase",
    "PrimitiveKind",
    "PrimitiveType",
    "AnyType",
    "NeverType",
    "ListType",
    "DictType",
    "TupleType",
    "SetType",
    "FrozenSetType",
    "OptionalType",
    "UnionType",
    "IntersectionType",
    "CallableType",
    "ClassType",
    "ProtocolMember",
    "ProtocolType",
    "ModuleType",
    "LiteralType",
    "TypeAliasType",
    "TensorType",
    "INT_TYPE",
    "FLOAT_TYPE",
    "STR_TYPE",
    "BOOL_TYPE",
    "BYTES_TYPE",
    "NONE_TYPE",
    "COMPLEX_TYPE",
    "ANY_TYPE",
    "NEVER_TYPE",
    "type_from_python",
    "type_join",
    "type_meet",
    # variables
    "Variance",
    "TypeVariable",
    "RowVariable",
    "SkolemVariable",
    "ExistentialVariable",
    "UnificationError",
    "UnificationState",
    # refinement
    "Predicate",
    "TruePred",
    "FalsePred",
    "ComparisonOp",
    "ComparisonPred",
    "NotPred",
    "ConjunctionPred",
    "DisjunctionPred",
    "ImplicationPred",
    "VarPred",
    "IsInstancePred",
    "IsNonePred",
    "IsNotNonePred",
    "MembershipPred",
    "LengthPred",
    "CallPred",
    "RefinementType",
    "Qualifier",
    "NonNull",
    "Positive",
    "NonNegative",
    "Negative",
    "NonEmpty",
    "Sorted",
    "Unique",
    "Bounded",
    "MaxLength",
    "MinLength",
    "Immutable",
    "Trusted",
    "QualifiedType",
    "refine",
    "positive_int",
    "non_negative_int",
    "bounded_int",
    "non_empty_list",
    "non_null",
    # dependent
    "PiType",
    "MultiPiType",
    "SigmaType",
    "IndexedFamily",
    "WitnessType",
    "IdentityType",
    "ForallType",
    "ExistsType",
    "DependentRecordType",
    "telescope_to_pi",
    "telescope_to_sigma",
    # subtyping
    "VCKind",
    "VerificationCondition",
    "SubtypingResult",
    "SubtypingChecker",
    "is_subtype",
    "check_subtype",
    "are_equivalent",
    # carriers
    "CarrierType",
    "SchemaConstraint",
    "CarrierSchema",
    "CarrierProjection",
    "MergeStrategy",
    "CarrierMerger",
    "carriers_compatible",
    "carrier_from_type",
    # indexed
    "TypeFamily",
    "FamilyApplication",
    "ConstantFamily",
    "TypeFamilyComposition",
    "DependentRecord",
    "IndexedUnion",
    "IndexedIntersection",
    # witnesses
    "ProofTerm",
    "ReflProof",
    "AssumptionProof",
    "RuntimeCheckProof",
    "StaticProof",
    "CompositeProof",
    "TransitivityProof",
    "SymmetryProof",
    "CongruenceProof",
    "WitnessCarrier",
    "ExistentialWitness",
    "TransportWitness",
    "RefinementWitness",
    "CompositeWitness",
    "WitnessRegistry",
]
