# ════════════════════════════════════════════════════════════════════
# CCTT Proof-Annotated Source — sympy
# Generated by Cohomological Cubical Type Theory Library Proof Orchestrator
#
# Every spec is a PATH THEOREM: Path(f(x), expected(x)) over {x : InputType}
# Every proof inhabits the path type.
# Every annotation is COMPILABLE: @cctt_verify JSON is machine-checkable.
#
# Trust levels:
#   🟢 KERNEL   — Refl / Z3 (machine-checked path)
#   🔵 MATHLIB  — Lean4/Mathlib theorem (proof-assistant verified path)
#   🟡 LIBRARY  — LibraryAxiom (sound if dependency correct)
#   🟠 INFERRED — LLM-selected strategy, checker-verified
#   🔴 ASSUMED  — explicitly assumed
#   ❌ FAILED   — proof did not compile
# ════════════════════════════════════════════════════════════════════

"""Tests for homomorphisms."""

from sympy.core.singleton import S
from sympy.polys.domains.rationalfield import QQ
from sympy.abc import x, y
from sympy.polys.agca import homomorphism
from sympy.testing.pytest import raises


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_printing(), test_printing produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_printing : Any → Any                                  ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 0a4b6b94d357d0f6  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.agca.tests.test_homomorphisms.test_printing","kind":"function","src_hash":"834429a177b70ff5","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"test_printing()","rhs":"test_printing produces the expected output","over":{"base":"Any"},"name":"test_printing_correct"},"guarantee":"test_printing produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.polys.agca.tests.test_homomorphisms.test_printing_correct","statement":"Path(test_printing(x), test_printing produces the expected output)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"0a4b6b94d357d0f6"}
def test_printing():
    R = QQ.old_poly_ring(x)

    assert str(homomorphism(R.free_module(1), R.free_module(1), [0])) == \
        'Matrix([[0]]) : QQ[x]**1 -> QQ[x]**1'
    assert str(homomorphism(R.free_module(2), R.free_module(2), [0, 0])) == \
        'Matrix([                       \n[0, 0], : QQ[x]**2 -> QQ[x]**2\n[0, 0]])                       '
    assert str(homomorphism(R.free_module(1), R.free_module(1) / [[x]], [0])) == \
        'Matrix([[0]]) : QQ[x]**1 -> QQ[x]**1/<[x]>'
    assert str(R.free_module(0).identity_hom()) == 'Matrix(0, 0, []) : QQ[x]**0 -> QQ[x]**0'

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_operations(), test_operations produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_operations : Any → {Any | f == f and f != g and ...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | c6fca8611adadc59  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.agca.tests.test_homomorphisms.test_operations","kind":"function","src_hash":"cba36dbcd5cb4e6b","in":{"base":"Any"},"out":{"base":"Any","pred":"f == f and f != g and f != i and (f != F.identity_hom()) is False and 2 * f == f * 2 == homomorphism(F, F, [[2, 0], [0, 2]]) and f / 2 == homomorphism(F, F, [[S.Half, 0], [0, S.Half]]) and f + g == homomorphism(F, F, [[1, 0], [1, x + 1]]) and f - g == homomorphism(F, F, [[1, 0], [-1, 1 - x]]) and f * g == g == g * f and h * g == homomorphism(F, F, [0, [1, 0]]) and g * h == homomorphism(F, F, [0, 0]) and i * f == i and f([1, 2]) == [1, 2] and g([1, 2]) == [2, 2 * x] and i.restrict_domain(F.submodule([x, x]))([x, x]) == i([x, x]) and h1([1, 0]) == h([1, 0]) and h1.restrict_domain(h1.domain.submodule([x, 0]))([x, 0]) == h([x, 0])"},"spec":{"lhs":"test_operations()","rhs":"test_operations produces the expected output","over":{"base":"Any"},"name":"test_operations_correct"},"guarantee":"test_operations produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.polys.agca.tests.test_homomorphisms.test_operations_correct","statement":"Path(test_operations(x), test_operations produces the expected output)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"c6fca8611adadc59"}
def test_operations():
    F = QQ.old_poly_ring(x).free_module(2)
    G = QQ.old_poly_ring(x).free_module(3)
    f = F.identity_hom()
    g = homomorphism(F, F, [0, [1, x]])
    h = homomorphism(F, F, [[1, 0], 0])
    i = homomorphism(F, G, [[1, 0, 0], [0, 1, 0]])

    assert f == f
    assert f != g
    assert f != i
    assert (f != F.identity_hom()) is False
    assert 2*f == f*2 == homomorphism(F, F, [[2, 0], [0, 2]])
    assert f/2 == homomorphism(F, F, [[S.Half, 0], [0, S.Half]])
    assert f + g == homomorphism(F, F, [[1, 0], [1, x + 1]])
    assert f - g == homomorphism(F, F, [[1, 0], [-1, 1 - x]])
    assert f*g == g == g*f
    assert h*g == homomorphism(F, F, [0, [1, 0]])
    assert g*h == homomorphism(F, F, [0, 0])
    assert i*f == i
    assert f([1, 2]) == [1, 2]
    assert g([1, 2]) == [2, 2*x]

    assert i.restrict_domain(F.submodule([x, x]))([x, x]) == i([x, x])
    h1 = h.quotient_domain(F.submodule([0, 1]))
    assert h1([1, 0]) == h([1, 0])
    assert h1.restrict_domain(h1.domain.submodule([x, 0]))([x, 0]) == h([x, 0])

    raises(TypeError, lambda: f/g)
    raises(TypeError, lambda: f + 1)
    raises(TypeError, lambda: f + i)
    raises(TypeError, lambda: f - 1)
    raises(TypeError, lambda: f*i)


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_creation(), test_creation produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_creation : Any → {Any | h.quotient_domain(SM) ==...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 0df30ca6e545b11d  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.agca.tests.test_homomorphisms.test_creation","kind":"function","src_hash":"6ccb65236f7b55eb","in":{"base":"Any"},"out":{"base":"Any","pred":"h.quotient_domain(SM) == h2 and h2.restrict_domain(SQ) == homomorphism(SQ, G, matrix) and SM.inclusion_hom() == homomorphism(SM, F, im) and SQ.inclusion_hom() == homomorphism(SQ, Q, im) and Q.quotient_hom() == homomorphism(F, Q, im) and SQ.quotient_hom() == homomorphism(SQ.base, SQ, im) and M.identity_hom() == homomorphism(M, M, im)"},"spec":{"lhs":"test_creation()","rhs":"test_creation produces the expected output","over":{"base":"Any"},"name":"test_creation_correct"},"guarantee":"test_creation produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.polys.agca.tests.test_homomorphisms.test_creation_correct","statement":"Path(test_creation(x), test_creation produces the expected output)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"0df30ca6e545b11d"}
def test_creation():
    F = QQ.old_poly_ring(x).free_module(3)
    G = QQ.old_poly_ring(x).free_module(2)
    SM = F.submodule([1, 1, 1])
    Q = F / SM
    SQ = Q.submodule([1, 0, 0])

    matrix = [[1, 0], [0, 1], [-1, -1]]
    h = homomorphism(F, G, matrix)
    h2 = homomorphism(Q, G, matrix)
    assert h.quotient_domain(SM) == h2
    raises(ValueError, lambda: h.quotient_domain(F.submodule([1, 0, 0])))
    assert h2.restrict_domain(SQ) == homomorphism(SQ, G, matrix)
    raises(ValueError, lambda: h.restrict_domain(G))
    raises(ValueError, lambda: h.restrict_codomain(G.submodule([1, 0])))
    raises(ValueError, lambda: h.quotient_codomain(F))

    im = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    for M in [F, SM, Q, SQ]:
        assert M.identity_hom() == homomorphism(M, M, im)
    assert SM.inclusion_hom() == homomorphism(SM, F, im)
    assert SQ.inclusion_hom() == homomorphism(SQ, Q, im)
    assert Q.quotient_hom() == homomorphism(F, Q, im)
    assert SQ.quotient_hom() == homomorphism(SQ.base, SQ, im)

    class conv:
        def convert(x, y=None):
            return x

    class dummy:
        container = conv()

        def submodule(*args):
            return None
    raises(TypeError, lambda: homomorphism(dummy(), G, matrix))
    raises(TypeError, lambda: homomorphism(F, dummy(), matrix))
    raises(
        ValueError, lambda: homomorphism(QQ.old_poly_ring(x, y).free_module(3), G, matrix))
    raises(ValueError, lambda: homomorphism(F, G, [0, 0]))


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_properties(), test_properties produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_properties : Any → {Any | h.kernel() == F.submod...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 56f5acf603210ec1  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.agca.tests.test_homomorphisms.test_properties","kind":"function","src_hash":"487ce6acf8d5d25d","in":{"base":"Any"},"out":{"base":"Any","pred":"h.kernel() == F.submodule([-y, x]) and h.image() == F.submodule([x, 0], [y, 0]) and not h.is_injective() and not h.is_surjective() and h.restrict_codomain(h.image()).is_surjective() and h.restrict_domain(F.submodule([1, 0])).is_injective() and h.quotient_domain(h.kernel()).restrict_codomain(h.image()).is_isomorphism() and h.is_isomorphism()"},"spec":{"lhs":"test_properties()","rhs":"test_properties produces the expected output","over":{"base":"Any"},"name":"test_properties_correct"},"guarantee":"test_properties produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.polys.agca.tests.test_homomorphisms.test_properties_correct","statement":"Path(test_properties(x), test_properties produces the expected output)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"56f5acf603210ec1"}
def test_properties():
    R = QQ.old_poly_ring(x, y)
    F = R.free_module(2)
    h = homomorphism(F, F, [[x, 0], [y, 0]])
    assert h.kernel() == F.submodule([-y, x])
    assert h.image() == F.submodule([x, 0], [y, 0])
    assert not h.is_injective()
    assert not h.is_surjective()
    assert h.restrict_codomain(h.image()).is_surjective()
    assert h.restrict_domain(F.submodule([1, 0])).is_injective()
    assert h.quotient_domain(
        h.kernel()).restrict_codomain(h.image()).is_isomorphism()

    R2 = QQ.old_poly_ring(x, y, order=(("lex", x), ("ilex", y))) / [x**2 + 1]
    F = R2.free_module(2)
    h = homomorphism(F, F, [[x, 0], [y, y + 1]])
    assert h.is_isomorphism()
