# ════════════════════════════════════════════════════════════════════
# CCTT Proof-Annotated Source — sympy
# Generated by Cohomological Cubical Type Theory Library Proof Orchestrator
#
# Every spec is a PATH THEOREM: Path(f(x), expected(x)) over {x : InputType}
# Every proof inhabits the path type.
# Every annotation is COMPILABLE: @cctt_verify JSON is machine-checkable.
#
# Trust levels:
#   🟢 KERNEL   — Refl / Z3 (machine-checked path)
#   🔵 MATHLIB  — Lean4/Mathlib theorem (proof-assistant verified path)
#   🟡 LIBRARY  — LibraryAxiom (sound if dependency correct)
#   🟠 INFERRED — LLM-selected strategy, checker-verified
#   🔴 ASSUMED  — explicitly assumed
#   ❌ FAILED   — proof did not compile
# ════════════════════════════════════════════════════════════════════

from sympy.core.numbers import (Float, I, Integer)
from sympy.matrices.dense import Matrix
from sympy.external import import_module
from sympy.testing.pytest import skip

from sympy.physics.quantum.dagger import Dagger
from sympy.physics.quantum.represent import (represent, rep_innerproduct,
                                             rep_expectation, enumerate_states)
from sympy.physics.quantum.state import Bra, Ket
from sympy.physics.quantum.operator import Operator, OuterProduct
from sympy.physics.quantum.tensorproduct import TensorProduct
from sympy.physics.quantum.tensorproduct import matrix_tensor_product
from sympy.physics.quantum.commutator import Commutator
from sympy.physics.quantum.anticommutator import AntiCommutator
from sympy.physics.quantum.innerproduct import InnerProduct
from sympy.physics.quantum.matrixutils import (numpy_ndarray,
                                               scipy_sparse_matrix, to_numpy,
                                               to_scipy_sparse, to_sympy)
from sympy.physics.quantum.cartesian import XKet, XOp, XBra
from sympy.physics.quantum.qapply import qapply
from sympy.physics.quantum.operatorset import operators_to_state
from sympy.testing.pytest import raises

Amat = Matrix([[1, I], [-I, 1]])
Bmat = Matrix([[1, 2], [3, 4]])
Avec = Matrix([[1], [I]])


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(AKet(*args), correctly constructs a AKet instance) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  isinstance(self, Ket)                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ AKet : Any → {Any | result satisfies: isinstance(self...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | aeb2c9ee436cc266  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.AKet","kind":"class","src_hash":"5eb6f25903b389b3","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: isinstance(self, Ket)"},"spec":{"lhs":"AKet(*args)","rhs":"correctly constructs a AKet instance","over":{"base":"Any"},"name":"AKet_class_invariant"},"guarantee":"isinstance(self, Ket)","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"aeb2c9ee436cc266","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["isinstance(self, Ket)"]},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":false,"binding_errors":["Function AKet not found in source"]}}
class AKet(Ket):

    @classmethod
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(dual_class(), <unspecified:dual_class>) over Any      ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ dual_class : Any → Any                                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 1edcb81cb0e5ecbd           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.AKet.dual_class","kind":"classmethod","src_hash":"567e38edfab8b9ed","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"dual_class()","rhs":"<unspecified:dual_class>","over":{"base":"Any"},"name":"dual_class_correct"},"guarantee":"dual_class produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"1edcb81cb0e5ecbd","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def dual_class(self):
        return ABra

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_represent_default_basis(**options), self._represent_AOp(None, **options)) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  self._represent_AOp(None, **options)           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _represent_default_basis : Any → Any                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 58358d4b9bccd205           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.AKet._represent_default_basis","kind":"method","src_hash":"71673c136a3bd0a8","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_represent_default_basis(**options)","rhs":"self._represent_AOp(None, **options)","over":{"base":"Any"},"name":"_represent_default_basis_correct"},"guarantee":"returns self._represent_AOp(None, **options)","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"58358d4b9bccd205","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"self._represent_AOp(None, **options)","pure":false,"effects":{"effect_type":"reads_state","reads":["self._represent_AOp"]}},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def _represent_default_basis(self, **options):
        return self._represent_AOp(None, **options)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_represent_AOp(basis, **options), <unspecified:_represent_AOp>) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _represent_AOp : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 13118b9299cf71b8           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.AKet._represent_AOp","kind":"method","src_hash":"760f08e70147bb07","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_represent_AOp(basis, **options)","rhs":"<unspecified:_represent_AOp>","over":{"base":"Any"},"name":"_represent_AOp_correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"13118b9299cf71b8","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def _represent_AOp(self, basis, **options):
        return Avec


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(ABra(*args), correctly constructs a ABra instance) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  isinstance(self, Bra)                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ ABra : Any → {Any | result satisfies: isinstance(self...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.0ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 2c14a7c9b12a462a  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.ABra","kind":"class","src_hash":"81d67fb6350d9e74","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: isinstance(self, Bra)"},"spec":{"lhs":"ABra(*args)","rhs":"correctly constructs a ABra instance","over":{"base":"Any"},"name":"ABra_class_invariant"},"guarantee":"isinstance(self, Bra)","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"2c14a7c9b12a462a","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["isinstance(self, Bra)"]},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.0,"verdict_class":"assumed","binding":false,"binding_errors":["Function ABra not found in source"]}}
class ABra(Bra):

    @classmethod
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(dual_class(), <unspecified:dual_class>) over Any      ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ dual_class : Any → Any                                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | c03a9865508c40bd           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.ABra.dual_class","kind":"classmethod","src_hash":"7f9b658bb63e2ac0","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"dual_class()","rhs":"<unspecified:dual_class>","over":{"base":"Any"},"name":"dual_class_correct"},"guarantee":"dual_class produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"c03a9865508c40bd","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def dual_class(self):
        return AKet


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(AOp(*args), correctly constructs a AOp instance) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  isinstance(self, Operator)                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ AOp : Any → {Any | result satisfies: isinstance(self,...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | f4ef70b58bad039c  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.AOp","kind":"class","src_hash":"6a2ff0ff0886328c","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: isinstance(self, Operator)"},"spec":{"lhs":"AOp(*args)","rhs":"correctly constructs a AOp instance","over":{"base":"Any"},"name":"AOp_class_invariant"},"guarantee":"isinstance(self, Operator)","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"f4ef70b58bad039c","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["isinstance(self, Operator)"]},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":false,"binding_errors":["Function AOp not found in source"]}}
class AOp(Operator):

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_represent_default_basis(**options), self._represent_AOp(None, **options)) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  self._represent_AOp(None, **options)           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _represent_default_basis : Any → Any                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | a6df34f1c8f027c5           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.AOp._represent_default_basis","kind":"method","src_hash":"71673c136a3bd0a8","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_represent_default_basis(**options)","rhs":"self._represent_AOp(None, **options)","over":{"base":"Any"},"name":"_represent_default_basis_correct"},"guarantee":"returns self._represent_AOp(None, **options)","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"a6df34f1c8f027c5","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"self._represent_AOp(None, **options)","pure":false,"effects":{"effect_type":"reads_state","reads":["self._represent_AOp"]}},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def _represent_default_basis(self, **options):
        return self._represent_AOp(None, **options)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_represent_AOp(basis, **options), <unspecified:_represent_AOp>) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _represent_AOp : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 28959d9e9c5336ef           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.AOp._represent_AOp","kind":"method","src_hash":"5c07c922d1d80580","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_represent_AOp(basis, **options)","rhs":"<unspecified:_represent_AOp>","over":{"base":"Any"},"name":"_represent_AOp_correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"28959d9e9c5336ef","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def _represent_AOp(self, basis, **options):
        return Amat


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(BOp(*args), correctly constructs a BOp instance) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  isinstance(self, Operator)                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ BOp : Any → {Any | result satisfies: isinstance(self,...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 65b2c0387e7e1a40  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.BOp","kind":"class","src_hash":"e28de204b72e807e","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: isinstance(self, Operator)"},"spec":{"lhs":"BOp(*args)","rhs":"correctly constructs a BOp instance","over":{"base":"Any"},"name":"BOp_class_invariant"},"guarantee":"isinstance(self, Operator)","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"65b2c0387e7e1a40","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["isinstance(self, Operator)"]},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":false,"binding_errors":["Function BOp not found in source"]}}
class BOp(Operator):

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_represent_default_basis(**options), self._represent_AOp(None, **options)) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   returns:  self._represent_AOp(None, **options)           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _represent_default_basis : Any → Any                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | b94dfcd1e1d8b150           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.BOp._represent_default_basis","kind":"method","src_hash":"71673c136a3bd0a8","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_represent_default_basis(**options)","rhs":"self._represent_AOp(None, **options)","over":{"base":"Any"},"name":"_represent_default_basis_correct"},"guarantee":"returns self._represent_AOp(None, **options)","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"b94dfcd1e1d8b150","spec_source":"static","formal_spec":{"source":"static","strength":"formal","returns_expr":"self._represent_AOp(None, **options)","pure":false,"effects":{"effect_type":"reads_state","reads":["self._represent_AOp"]}},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def _represent_default_basis(self, **options):
        return self._represent_AOp(None, **options)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(_represent_AOp(basis, **options), <unspecified:_represent_AOp>) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ _represent_AOp : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓0 ?0 ✗1 VCs | 0.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | f9ea98b5c1de0656           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.BOp._represent_AOp","kind":"method","src_hash":"448fa0d534e7b6af","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"_represent_AOp(basis, **options)","rhs":"<unspecified:_represent_AOp>","over":{"base":"Any"},"name":"_represent_AOp_correct"},"guarantee":"internal helper behaves correctly","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"f9ea98b5c1de0656","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":false,"n_vcs":1,"n_verified":0,"n_assumed":0,"n_failed":1,"trust_level":"KERNEL","compile_ms":0.0,"verdict_class":"failed","binding":false,"binding_errors":["Parse error: unexpected indent (<unknown>, line 1)"]}}
    def _represent_AOp(self, basis, **options):
        return Bmat


k = AKet('a')
b = ABra('a')
A = AOp('A')
B = BOp('B')

_tests = [
    # Bra
    (b, Dagger(Avec)),
    (Dagger(b), Avec),
    # Ket
    (k, Avec),
    (Dagger(k), Dagger(Avec)),
    # Operator
    (A, Amat),
    (Dagger(A), Dagger(Amat)),
    # OuterProduct
    (OuterProduct(k, b), Avec*Avec.H),
    # TensorProduct
    (TensorProduct(A, B), matrix_tensor_product(Amat, Bmat)),
    # Pow
    (A**2, Amat**2),
    # Add/Mul
    (A*B + 2*A, Amat*Bmat + 2*Amat),
    # Commutator
    (Commutator(A, B), Amat*Bmat - Bmat*Amat),
    # AntiCommutator
    (AntiCommutator(A, B), Amat*Bmat + Bmat*Amat),
    # InnerProduct
    (InnerProduct(b, k), (Avec.H*Avec)[0])
]


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_format_sympy(), <unspecified:test_format_sympy>) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_format_sympy : Any → {Any | lhs == rhs}               ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 3cb6147fbc1f4417  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_format_sympy","kind":"function","src_hash":"e022f2787f5c4168","in":{"base":"Any"},"out":{"base":"Any","pred":"lhs == rhs"},"spec":{"lhs":"test_format_sympy()","rhs":"<unspecified:test_format_sympy>","over":{"base":"Any"},"name":"test_format_sympy_correct"},"guarantee":"test_format_sympy produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_format_sympy_correct","statement":"Path(test_format_sympy(x), test_format_sympy produces the expected output)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"3cb6147fbc1f4417","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_format_sympy():
    for test in _tests:
        lhs = represent(test[0], basis=A, format='sympy')
        rhs = to_sympy(test[1])
        assert lhs == rhs


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_scalar_sympy(), represent(Integer(1)) == Integer(1) and represent(Float(1.0)) == Float(1.0) and represent(1.0 + I) == 1.0 + I) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  represent(Integer(1)) == Integer(1)            ║
# ║   ensures:  represent(Float(1.0)) == Float(1.0)            ║
# ║   ensures:  represent(1.0 + I) == 1.0 + I                  ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_scalar_sympy : Any → {Any | result satisfies: re...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 1c459d8dd09f0a69  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_scalar_sympy","kind":"function","src_hash":"a2c23e2a457a8b47","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: represent(Integer(1)) == Integer(1) and represent(Float(1.0)) == Float(1.0) and represent(1.0 + I) == 1.0 + I"},"spec":{"lhs":"test_scalar_sympy()","rhs":"represent(Integer(1)) == Integer(1) and represent(Float(1.0)) == Float(1.0) and represent(1.0 + I) == 1.0 + I","over":{"base":"Any"},"name":"test_scalar_sympy_correct"},"guarantee":"represent(Integer(1)) == Integer(1); represent(Float(1.0)) == Float(1.0); represent(1.0 + I) == 1.0 + I","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_scalar_sympy_correct","statement":"Path(test_scalar_sympy(x), represent(Integer(1)) == Integer(1); represent(Float(1.0)) == Float(1.0); represent(1.0 + I) == 1.0 + I)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"1c459d8dd09f0a69","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["represent(Integer(1)) == Integer(1)","represent(Float(1.0)) == Float(1.0)","represent(1.0 + I) == 1.0 + I"],"pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_scalar_sympy():
    assert represent(Integer(1)) == Integer(1)
    assert represent(Float(1.0)) == Float(1.0)
    assert represent(1.0 + I) == 1.0 + I


np = import_module('numpy')


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_format_numpy(), <unspecified:test_format_numpy>) over {Any | isinstance(lhs, numpy_ndarray)} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_format_numpy : {Any | isinstance(lhs, numpy_ndar...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Čech Cover:                                                ║
# ║   numpy_ndarray: {isinstance(lhs, numpy_ndarray)} → l...   ║
# ║   H¹ = 0 (globally proved)                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Descent.descent_soundness                        ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓1 ?1 ✗1 VCs | 1.3ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refinement_descent | Compiled: ✓ | ca76625b...  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_format_numpy","kind":"function","src_hash":"c0d561e7d9e31c08","in":{"base":"Any","pred":"isinstance(lhs, numpy_ndarray)"},"out":{"base":"Any","pred":"(lhs == rhs).all() and lhs == rhs"},"spec":{"lhs":"test_format_numpy()","rhs":"<unspecified:test_format_numpy>","over":{"base":"Any","pred":"isinstance(lhs, numpy_ndarray)"},"name":"test_format_numpy_correct"},"guarantee":"test_format_numpy produces the expected output","fibers":[{"name":"numpy_ndarray","pred":"isinstance(lhs, numpy_ndarray)","path":{"lhs":"test_format_numpy(x)","rhs":"test_format_numpy produces the expected output","over":{"base":"numpy_ndarray","pred":"isinstance(lhs, numpy_ndarray)"},"name":"test_format_numpy_numpy_ndarray_case"},"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_format_numpy_numpy_ndarray_correct","statement":"test_format_numpy satisfies spec on numpy_ndarray inputs"},"trust":"LIBRARY"}],"h1":0,"paths":[],"strategy":"refinement_descent","details":{"exhaustiveness":"z3_proved","n_fibers":1,"h1":0},"assumes":[],"trust":["lean.C4.Descent.descent_soundness","z3.Solver.check"],"compiled":true,"vhash":"ca76625bdfec4c71","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":false,"n_vcs":3,"n_verified":1,"n_assumed":1,"n_failed":1,"trust_level":"LIBRARY_ASSUMED","compile_ms":1.3,"verdict_class":"failed","binding":false,"binding_errors":["Poor branch-fiber coverage: 0% (branches={'isinstance(lhs, numpy_ndarray)'}, fibers={'numpy_ndarray'})"]}}
def test_format_numpy():
    if not np:
        skip("numpy not installed.")

    for test in _tests:
        lhs = represent(test[0], basis=A, format='numpy')
        rhs = to_numpy(test[1])
        if isinstance(lhs, numpy_ndarray):
            assert (lhs == rhs).all()
        else:
            assert lhs == rhs


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_scalar_numpy(), represent(Integer(1), format='numpy') == 1 and represent(Float(1.0), format='numpy') == 1.0 and represent(1.0 + I, format='numpy') == 1.0 + 1j) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  represent(Integer(1), format='numpy') == 1     ║
# ║   ensures:  represent(Float(1.0), format='numpy') == 1.0   ║
# ║   ensures:  represent(1.0 + I, format='numpy') == 1.0...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_scalar_numpy : Any → {Any | result satisfies: re...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 65a78e558d8edab3  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_scalar_numpy","kind":"function","src_hash":"803045d7c8c48b4e","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: represent(Integer(1), format='numpy') == 1 and represent(Float(1.0), format='numpy') == 1.0 and represent(1.0 + I, format='numpy') == 1.0 + 1j"},"spec":{"lhs":"test_scalar_numpy()","rhs":"represent(Integer(1), format='numpy') == 1 and represent(Float(1.0), format='numpy') == 1.0 and represent(1.0 + I, format='numpy') == 1.0 + 1j","over":{"base":"Any"},"name":"test_scalar_numpy_correct"},"guarantee":"represent(Integer(1), format='numpy') == 1; represent(Float(1.0), format='numpy') == 1.0; represent(1.0 + I, format='numpy') == 1.0 + 1j","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_scalar_numpy_correct","statement":"Path(test_scalar_numpy(x), represent(Integer(1), format='numpy') == 1; represent(Float(1.0), format='numpy') == 1.0; represent(1.0 + I, format='numpy') == 1.0 + 1j)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"65a78e558d8edab3","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["represent(Integer(1), format='numpy') == 1","represent(Float(1.0), format='numpy') == 1.0","represent(1.0 + I, format='numpy') == 1.0 + 1j"],"pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_scalar_numpy():
    if not np:
        skip("numpy not installed.")

    assert represent(Integer(1), format='numpy') == 1
    assert represent(Float(1.0), format='numpy') == 1.0
    assert represent(1.0 + I, format='numpy') == 1.0 + 1.0j


scipy = import_module('scipy', import_kwargs={'fromlist': ['sparse']})


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_format_scipy_sparse(), <unspecified:test_format_scipy_sparse>) over {Any | isinstance(lhs, scipy_sparse_matrix)} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=trivial                          ║
# ║   ⚠ UNSPECIFIED — no formal spec; proof is vacuous         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_format_scipy_sparse : {Any | isinstance(lhs, sci...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Čech Cover:                                                ║
# ║   scipy_sparse_matrix: {isinstance(lhs, scipy_sparse_...   ║
# ║   H¹ = 0 (globally proved)                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Descent.descent_soundness                        ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: failed | ✓1 ?1 ✗1 VCs | 1.0ms                          ║
# ║   F* binding: ✗                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refinement_descent | Compiled: ✓ | c16457d7...  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_format_scipy_sparse","kind":"function","src_hash":"11f8285a07db56df","in":{"base":"Any","pred":"isinstance(lhs, scipy_sparse_matrix)"},"out":{"base":"Any","pred":"np.linalg.norm((lhs - rhs).todense()) == 0.0 and lhs == rhs"},"spec":{"lhs":"test_format_scipy_sparse()","rhs":"<unspecified:test_format_scipy_sparse>","over":{"base":"Any","pred":"isinstance(lhs, scipy_sparse_matrix)"},"name":"test_format_scipy_sparse_correct"},"guarantee":"test_format_scipy_sparse produces the expected output","fibers":[{"name":"scipy_sparse_matrix","pred":"isinstance(lhs, scipy_sparse_matrix)","path":{"lhs":"test_format_scipy_sparse(x)","rhs":"test_format_scipy_sparse produces the expected output","over":{"base":"scipy_sparse_matrix","pred":"isinstance(lhs, scipy_sparse_matrix)"},"name":"test_format_scipy_sparse_scipy_sparse_matrix_case"},"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_format_scipy_sparse_scipy_sparse_matrix_correct","statement":"test_format_scipy_sparse satisfies spec on scipy_sparse_matrix inputs"},"trust":"LIBRARY"}],"h1":0,"paths":[],"strategy":"refinement_descent","details":{"exhaustiveness":"z3_proved","n_fibers":1,"h1":0},"assumes":[],"trust":["lean.C4.Descent.descent_soundness","z3.Solver.check"],"compiled":true,"vhash":"c16457d7498bb19b","spec_source":"static","formal_spec":{"source":"static","strength":"trivial","pure":true},"c4_verdict":{"valid":false,"n_vcs":3,"n_verified":1,"n_assumed":1,"n_failed":1,"trust_level":"LIBRARY_ASSUMED","compile_ms":1.0,"verdict_class":"failed","binding":false,"binding_errors":["Poor branch-fiber coverage: 0% (branches={'isinstance(lhs, scipy_sparse_matrix)'}, fibers={'scipy_sparse_matrix'})"]}}
def test_format_scipy_sparse():
    if not np:
        skip("numpy not installed.")
    if not scipy:
        skip("scipy not installed.")

    for test in _tests:
        lhs = represent(test[0], basis=A, format='scipy.sparse')
        rhs = to_scipy_sparse(test[1])
        if isinstance(lhs, scipy_sparse_matrix):
            assert np.linalg.norm((lhs - rhs).todense()) == 0.0
        else:
            assert lhs == rhs


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_scalar_scipy_sparse(), represent(Integer(1), format='scipy.sparse') == 1 and represent(Float(1.0), format='scipy.sparse') == 1.0 and represent(1.0 + I, format='scipy.sparse') == 1.0 + 1j) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  represent(Integer(1), format='scipy.spars...   ║
# ║   ensures:  represent(Float(1.0), format='scipy.spars...   ║
# ║   ensures:  represent(1.0 + I, format='scipy.sparse')...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_scalar_scipy_sparse : Any → {Any | result satisf...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 11b84e516fc3b733  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_scalar_scipy_sparse","kind":"function","src_hash":"e3926d8f966ab683","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: represent(Integer(1), format='scipy.sparse') == 1 and represent(Float(1.0), format='scipy.sparse') == 1.0 and represent(1.0 + I, format='scipy.sparse') == 1.0 + 1j"},"spec":{"lhs":"test_scalar_scipy_sparse()","rhs":"represent(Integer(1), format='scipy.sparse') == 1 and represent(Float(1.0), format='scipy.sparse') == 1.0 and represent(1.0 + I, format='scipy.sparse') == 1.0 + 1j","over":{"base":"Any"},"name":"test_scalar_scipy_sparse_correct"},"guarantee":"represent(Integer(1), format='scipy.sparse') == 1; represent(Float(1.0), format='scipy.sparse') == 1.0; represent(1.0 + I, format='scipy.sparse') == 1.0 + 1j","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_scalar_scipy_sparse_correct","statement":"Path(test_scalar_scipy_sparse(x), represent(Integer(1), format='scipy.sparse') == 1; represent(Float(1.0), format='scipy.sparse') == 1.0; represent(1.0 + I, format='scipy.sparse') == 1.0 + 1j)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"11b84e516fc3b733","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["represent(Integer(1), format='scipy.sparse') == 1","represent(Float(1.0), format='scipy.sparse') == 1.0","represent(1.0 + I, format='scipy.sparse') == 1.0 + 1j"],"pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_scalar_scipy_sparse():
    if not np:
        skip("numpy not installed.")
    if not scipy:
        skip("scipy not installed.")

    assert represent(Integer(1), format='scipy.sparse') == 1
    assert represent(Float(1.0), format='scipy.sparse') == 1.0
    assert represent(1.0 + I, format='scipy.sparse') == 1.0 + 1.0j

x_ket = XKet('x')
x_bra = XBra('x')
x_op = XOp('X')


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_innerprod_represent(), rep_innerproduct(x_ket) == InnerProduct(XBra('x_1'), x_ket).doit() and rep_innerproduct(x_bra) == InnerProduct(x_bra, XKet('x_1')).doit()) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  rep_innerproduct(x_ket) == InnerProduct(X...   ║
# ║   ensures:  rep_innerproduct(x_bra) == InnerProduct(x...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_innerprod_represent : Any → {Any | result satisf...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | df719e0d02da4509  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_innerprod_represent","kind":"function","src_hash":"69cdedcb9f37c1f3","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: rep_innerproduct(x_ket) == InnerProduct(XBra('x_1'), x_ket).doit() and rep_innerproduct(x_bra) == InnerProduct(x_bra, XKet('x_1')).doit()"},"spec":{"lhs":"test_innerprod_represent()","rhs":"rep_innerproduct(x_ket) == InnerProduct(XBra('x_1'), x_ket).doit() and rep_innerproduct(x_bra) == InnerProduct(x_bra, XKet('x_1')).doit()","over":{"base":"Any"},"name":"test_innerprod_represent_correct"},"guarantee":"rep_innerproduct(x_ket) == InnerProduct(XBra('x_1'), x_ket).doit(); rep_innerproduct(x_bra) == InnerProduct(x_bra, XKet('x_1')).doit()","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_innerprod_represent_correct","statement":"Path(test_innerprod_represent(x), rep_innerproduct(x_ket) == InnerProduct(XBra('x_1'), x_ket).doit(); rep_innerproduct(x_bra) == InnerProduct(x_bra, XKet('x_1')).doit())"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"df719e0d02da4509","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["rep_innerproduct(x_ket) == InnerProduct(XBra('x_1'), x_ket).doit()","rep_innerproduct(x_bra) == InnerProduct(x_bra, XKet('x_1')).doit()"],"pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_innerprod_represent():
    assert rep_innerproduct(x_ket) == InnerProduct(XBra("x_1"), x_ket).doit()
    assert rep_innerproduct(x_bra) == InnerProduct(x_bra, XKet("x_1")).doit()
    raises(TypeError, lambda: rep_innerproduct(x_op))


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_operator_represent(), rep_expectation(x_op) == qapply(basis_kets[1].dual * x_op * basis_kets[0])) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  rep_expectation(x_op) == qapply(basis_ket...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_operator_represent : Any → {Any | result satisfi...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 7f509ebbd53ab2e9  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_operator_represent","kind":"function","src_hash":"ffecb19f416434ef","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: rep_expectation(x_op) == qapply(basis_kets[1].dual * x_op * basis_kets[0])"},"spec":{"lhs":"test_operator_represent()","rhs":"rep_expectation(x_op) == qapply(basis_kets[1].dual * x_op * basis_kets[0])","over":{"base":"Any"},"name":"test_operator_represent_correct"},"guarantee":"rep_expectation(x_op) == qapply(basis_kets[1].dual * x_op * basis_kets[0])","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_operator_represent_correct","statement":"Path(test_operator_represent(x), rep_expectation(x_op) == qapply(basis_kets[1].dual * x_op * basis_kets[0]))"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"7f509ebbd53ab2e9","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["rep_expectation(x_op) == qapply(basis_kets[1].dual * x_op * basis_kets[0])"],"pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_operator_represent():
    basis_kets = enumerate_states(operators_to_state(x_op), 1, 2)
    assert rep_expectation(
        x_op) == qapply(basis_kets[1].dual*x_op*basis_kets[0])


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_enumerate_states(), enumerate_states(test, 1, 1) == [XKet('foo_1')] and enumerate_states(test, [1, 2, 4]) == [XKet('foo_1'), XKet('foo_2'), XKet('foo_4')]) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  enumerate_states(test, 1, 1) == [XKet('fo...   ║
# ║   ensures:  enumerate_states(test, [1, 2, 4]) == [XKe...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_enumerate_states : Any → {Any | result satisfies...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 6a9de7c6248928f3  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.physics.quantum.tests.test_represent.test_enumerate_states","kind":"function","src_hash":"322c433009cdef70","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: enumerate_states(test, 1, 1) == [XKet('foo_1')] and enumerate_states(test, [1, 2, 4]) == [XKet('foo_1'), XKet('foo_2'), XKet('foo_4')]"},"spec":{"lhs":"test_enumerate_states()","rhs":"enumerate_states(test, 1, 1) == [XKet('foo_1')] and enumerate_states(test, [1, 2, 4]) == [XKet('foo_1'), XKet('foo_2'), XKet('foo_4')]","over":{"base":"Any"},"name":"test_enumerate_states_correct"},"guarantee":"enumerate_states(test, 1, 1) == [XKet('foo_1')]; enumerate_states(test, [1, 2, 4]) == [XKet('foo_1'), XKet('foo_2'), XKet('foo_4')]","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.physics.quantum.tests.test_represent.test_enumerate_states_correct","statement":"Path(test_enumerate_states(x), enumerate_states(test, 1, 1) == [XKet('foo_1')]; enumerate_states(test, [1, 2, 4]) == [XKet('foo_1'), XKet('foo_2'), XKet('foo_4')])"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"6a9de7c6248928f3","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["enumerate_states(test, 1, 1) == [XKet('foo_1')]","enumerate_states(test, [1, 2, 4]) == [XKet('foo_1'), XKet('foo_2'), XKet('foo_4')]"],"pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_enumerate_states():
    test = XKet("foo")
    assert enumerate_states(test, 1, 1) == [XKet("foo_1")]
    assert enumerate_states(
        test, [1, 2, 4]) == [XKet("foo_1"), XKet("foo_2"), XKet("foo_4")]
