"""Equivalence checking pipeline.

Orchestrates the full equivalence analysis from source files to verdict:

    parse_both -> harvest_both -> align_covers -> local_check -> glue -> report

This follows the same staged architecture as the main deppy pipeline
(pipeline/pipeline.py) but adds paired analysis and fiber-product
construction.

The pipeline can be used programmatically or via the CLI.
"""

from __future__ import annotations

import ast as _stdlib_ast
import hashlib as _hashlib
import textwrap


def _canonical_function_signature(func_node: _stdlib_ast.FunctionDef) -> str:
    """Compute a SEMANTIC SIGNATURE for a function via deep Python semantics.

    This implements the QUOTIENT PRESHEAF Sem / ∼ where ∼ is the equivalence
    relation generated by Python's semantic laws:

    1. Alpha-equivalence (variable renaming)
    2. Commutativity of + and * (a+b = b+a)
    3. Loop ↔ comprehension (for-append = list comprehension)
    4. Accumulator ↔ builtin reduction (manual sum = sum())
    5. Ternary ↔ if/else (x if c else y = if c: return x; return y)
    6. Early return ↔ else (if c: return a; return b = if c: a else: b)
    7. Guard reorder (if !c: A else: B = if c: B else: A)
    8. Dict assignment loop ↔ dict comprehension
    9. String concatenation ↔ join
    10. max/min/any/all builtins ↔ manual loops

    The semantic signature is a NORMAL FORM: a canonical representation
    of the computation that is invariant under all the above equivalences.

    Architecture:
    - Phase 1: Extract the SEMANTIC EFFECT (what the function computes)
               as a set of (guard_condition, return_value) pairs
    - Phase 2: Normalize each pair under Python's algebraic laws
    - Phase 3: Recognize COMPUTATION PATTERNS (reduce, filter, map, etc.)
    - Phase 4: Assemble the canonical signature from the normal form
    """
    import ast
    import copy

    params = [a.arg for a in func_node.args.args]
    param_map = {name: f'p{i}' for i, name in enumerate(params)}

    # ====================================================================
    # Phase 0: Expression normalizer with deep Python semantics
    # ====================================================================

    def _norm(expr: ast.AST) -> str:
        """Normalize an expression to canonical form."""
        if isinstance(expr, ast.Name):
            return param_map.get(expr.id, '_loc')
        if isinstance(expr, ast.Constant):
            return repr(expr.value)
        if isinstance(expr, ast.BinOp):
            op = type(expr.op).__name__
            left = _norm(expr.left)
            right = _norm(expr.right)
            # ── General algebraic normalization ──
            # Apply Python's algebraic laws to produce a canonical form.
            # The key principle: we express each BinOp in terms of a
            # CANONICAL OPERATION SET and simplify using identities.
            #
            # Laws applied:
            # 1. x op x (self-application): x+x → 2·x, x*x → x², x-x → 0
            # 2. Constant folding: 2*3 → 6
            # 3. Identity elements: x+0 → x, x*1 → x, x*0 → 0, x**1 → x
            # 4. Commutativity: a+b = b+a, a*b = b*a
            # 5. Constant-param canonicalization: const op param → CANONICAL(const, op, param)

            # Self-application identities
            if left == right:
                if isinstance(expr.op, ast.Add):
                    return f'SCALE(2,{left})'
                if isinstance(expr.op, ast.Mult):
                    return f'POW({left},2)'
                if isinstance(expr.op, ast.Sub):
                    return '0'

            # Constant folding
            if (isinstance(expr.left, ast.Constant) and isinstance(expr.right, ast.Constant)
                    and isinstance(expr.left.value, (int, float))
                    and isinstance(expr.right.value, (int, float))):
                try:
                    op_fn = {ast.Add: lambda a, b: a + b, ast.Sub: lambda a, b: a - b,
                             ast.Mult: lambda a, b: a * b, ast.FloorDiv: lambda a, b: a // b if b else None,
                             ast.Mod: lambda a, b: a % b if b else None,
                             ast.Pow: lambda a, b: a ** b}.get(type(expr.op))
                    if op_fn:
                        val = op_fn(expr.left.value, expr.right.value)
                        if val is not None:
                            return repr(val)
                except (ZeroDivisionError, OverflowError, TypeError):
                    pass

            # Constant * variable → SCALE(const, var)
            # This makes 2*x, x*2, x+x all produce SCALE(2,x)
            if isinstance(expr.op, ast.Mult):
                if isinstance(expr.left, ast.Constant) and isinstance(expr.left.value, (int, float)):
                    return f'SCALE({expr.left.value},{right})'
                if isinstance(expr.right, ast.Constant) and isinstance(expr.right.value, (int, float)):
                    return f'SCALE({expr.right.value},{left})'

            # Identity elements: x+0→x, 0+x→x, x*1→x, 1*x→x, x*0→0, x**0→1, x**1→x
            if isinstance(expr.op, (ast.Add, ast.Sub)):
                if right == '0': return left
                if left == '0' and isinstance(expr.op, ast.Add): return right
            if isinstance(expr.op, ast.Mult):
                if right == '1': return left
                if left == '1': return right
                if right == '0' or left == '0': return '0'
            if isinstance(expr.op, ast.Pow):
                if right == '0': return '1'
                if right == '1': return left
                if right == repr(0.5): return f'sqrt({left})'

            # Commutativity: sort operands for +, *
            # BUT: list/tuple concatenation is NOT commutative!
            # [a] + [b] ≠ [b] + [a]. Only sort when BOTH operands
            # are atomic (not list/tuple literals).
            _both_atomic = not (left.startswith('[') or right.startswith('['))
            if isinstance(expr.op, (ast.Add, ast.Mult, ast.BitOr,
                                    ast.BitAnd, ast.BitXor)) and _both_atomic:
                operands = sorted([left, right])
                return f'({operands[0]} {op} {operands[1]})'
            return f'({left} {op} {right})'
        if isinstance(expr, ast.UnaryOp):
            return f'({type(expr.op).__name__} {_norm(expr.operand)})'
        if isinstance(expr, ast.Compare):
            left = _norm(expr.left)
            parts = [left]
            for op, comp in zip(expr.ops, expr.comparators):
                parts.append(type(op).__name__)
                parts.append(_norm(comp))
            return ' '.join(parts)
        if isinstance(expr, ast.BoolOp):
            op = type(expr.op).__name__
            vals = sorted(_norm(v) for v in expr.values)
            return f'({op} {" ".join(vals)})'
        if isinstance(expr, ast.Call):
            func_name = ""
            if isinstance(expr.func, ast.Name):
                func_name = expr.func.id
            elif isinstance(expr.func, ast.Attribute):
                func_name = f'.{expr.func.attr}'
            args = [_norm(a) for a in expr.args]
            # Include keyword arguments — they change semantics
            # (e.g., sorted(lst) vs sorted(lst, reverse=True))
            for kw in expr.keywords:
                key = kw.arg or '**'
                args.append(f'{key}={_norm(kw.value)}')
            # Normalize generator expressions in calls:
            # any(x < 0 for x in lst) → any(PRED for _ in p0)
            if expr.args and isinstance(expr.args[0], ast.GeneratorExp):
                gen = expr.args[0]
                elt_norm = _norm(gen.elt)
                filter_strs = []
                for g in gen.generators:
                    for if_ in g.ifs:
                        filter_strs.append(_norm(if_))
                args = [f'GEN({elt_norm}|{",".join(filter_strs)})']
            return f'{func_name}({",".join(args)})'
        if isinstance(expr, ast.Subscript):
            return f'{_norm(expr.value)}[{_norm(expr.slice)}]'
        if isinstance(expr, ast.IfExp):
            # Normalize ternary: (value_if_true, condition, value_if_false)
            test = _norm(expr.test)
            body = _norm(expr.body)
            orelse = _norm(expr.orelse)
            return f'COND({test},{body},{orelse})'
        if isinstance(expr, ast.ListComp):
            elt = _norm(expr.elt)
            filters = []
            for g in expr.generators:
                for if_ in g.ifs:
                    filters.append(_norm(if_))
            if filters:
                return f'FILTER({elt}|{",".join(filters)})'
            return f'MAP({elt})'
        if isinstance(expr, ast.DictComp):
            key = _norm(expr.key)
            val = _norm(expr.value)
            filters = []
            for g in expr.generators:
                for if_ in g.ifs:
                    filters.append(_norm(if_))
            return f'DICTMAP({key}:{val}|{",".join(filters)})'
        if isinstance(expr, (ast.List, ast.Tuple)):
            return f'[{",".join(_norm(e) for e in expr.elts)}]'
        if isinstance(expr, ast.Attribute):
            return f'{_norm(expr.value)}.{expr.attr}'
        if isinstance(expr, ast.Slice):
            parts = []
            parts.append(_norm(expr.lower) if expr.lower else '')
            parts.append(_norm(expr.upper) if expr.upper else '')
            if expr.step:
                parts.append(_norm(expr.step))
            return ':'.join(parts)
        if isinstance(expr, ast.JoinedStr):
            return 'FSTRING'
        return '_expr'

    # ====================================================================
    # Phase 1: Extract SEMANTIC EFFECT as (condition, value) pairs
    # ====================================================================
    # A function's semantics is fully characterized by:
    #   { (guard₁, return₁), (guard₂, return₂), ..., (True, default_return) }
    # where each guard is the conjunction of if-conditions on the path.
    # This is the DISJUNCTIVE NORMAL FORM of the function's behavior.

    effects: list[tuple[str, str]] = []  # (guard, return_value)

    def _extract_effects(stmts: list[ast.stmt], path_guard: str = 'True') -> bool:
        """Extract (guard, return) pairs from a statement list.
        Returns True if all paths return (no fall-through)."""
        for i, stmt in enumerate(stmts):
            if isinstance(stmt, ast.Return) and stmt.value is not None:
                effects.append((path_guard, _norm(stmt.value)))
                return True
            if isinstance(stmt, ast.Return) and stmt.value is None:
                effects.append((path_guard, 'None'))
                return True
            if isinstance(stmt, ast.If):
                test_norm = _norm(stmt.test)
                neg_test = f'NOT({test_norm})'
                # True branch
                true_guard = f'{path_guard} AND {test_norm}' if path_guard != 'True' else test_norm
                true_returns = _extract_effects(stmt.body, true_guard)
                # False branch (else)
                if stmt.orelse:
                    false_guard = f'{path_guard} AND {neg_test}' if path_guard != 'True' else neg_test
                    false_returns = _extract_effects(stmt.orelse, false_guard)
                    if true_returns and false_returns:
                        return True
                elif true_returns:
                    # If true branch returns, the rest of the function
                    # executes under the negated guard
                    remaining = stmts[i+1:]
                    if remaining:
                        new_guard = f'{path_guard} AND {neg_test}' if path_guard != 'True' else neg_test
                        if _extract_effects(remaining, new_guard):
                            return True
                    return True
            if isinstance(stmt, ast.For):
                # For loops: check for accumulation/filter/map patterns
                _analyze_loop(stmt, path_guard)
            if isinstance(stmt, ast.While):
                _analyze_loop(stmt, path_guard)
            if isinstance(stmt, ast.Expr) and isinstance(stmt.value, ast.Call):
                # Expression statement (side effect)
                pass
        return False

    # ====================================================================
    # Phase 2: Loop pattern analysis (deep Python semantics)
    # ====================================================================

    _loop_pattern = None  # Will be set if a recognizable pattern is found

    def _analyze_loop(loop_node: ast.AST, guard: str):
        nonlocal _loop_pattern

        if isinstance(loop_node, ast.For):
            body = loop_node.body
            iter_expr = _norm(loop_node.iter)

            # Pattern: result = []; for x in iter: result.append(expr)
            # This is MAP(expr) over iter
            if (len(body) == 1
                    and isinstance(body[0], ast.Expr)
                    and isinstance(body[0].value, ast.Call)
                    and isinstance(body[0].value.func, ast.Attribute)
                    and body[0].value.func.attr == 'append'):
                if body[0].value.args:
                    elt = _norm(body[0].value.args[0])
                    _loop_pattern = f'MAP({elt})'
                return

            # Pattern: result = []; for x in iter: if cond: result.append(expr)
            # This is FILTER(expr | cond) over iter
            if (len(body) == 1
                    and isinstance(body[0], ast.If)
                    and len(body[0].body) == 1
                    and isinstance(body[0].body[0], ast.Expr)
                    and isinstance(body[0].body[0].value, ast.Call)
                    and isinstance(body[0].body[0].value.func, ast.Attribute)
                    and body[0].body[0].value.func.attr == 'append'):
                cond = _norm(body[0].test)
                if body[0].body[0].value.args:
                    elt = _norm(body[0].body[0].value.args[0])
                    _loop_pattern = f'FILTER({elt}|{cond})'
                return

            # Pattern: result op= expr  (accumulator reduction)
            # Include iteration source for matching with builtin equiv
            if (len(body) == 1 and isinstance(body[0], ast.AugAssign)):
                op = type(body[0].op).__name__
                _loop_pattern = f'REDUCE({op},{iter_expr})'
                return

            # Pattern: for x in iter: if cond: result op= expr
            if (len(body) == 1 and isinstance(body[0], ast.If)
                    and len(body[0].body) == 1
                    and isinstance(body[0].body[0], ast.AugAssign)):
                op = type(body[0].body[0].op).__name__
                cond = _norm(body[0].test)
                _loop_pattern = f'REDUCE_COND({op}|{cond})'
                return

            # Pattern: manual max/min: if x > m: m = x
            if (len(body) == 1 and isinstance(body[0], ast.If)
                    and len(body[0].body) == 1
                    and isinstance(body[0].body[0], ast.Assign)):
                cond = body[0].test
                if isinstance(cond, ast.Compare) and len(cond.ops) == 1:
                    op = cond.ops[0]
                    if isinstance(op, ast.Gt):
                        _loop_pattern = f'REDUCE(max,{iter_expr})'
                    elif isinstance(op, ast.Lt):
                        _loop_pattern = f'REDUCE(min,{iter_expr})'
                return

            # Pattern: result = {}; for k, v in d.items(): result[v] = k
            # Dict inversion
            if (len(body) == 1 and isinstance(body[0], ast.Assign)
                    and isinstance(body[0].targets[0], ast.Subscript)):
                _loop_pattern = 'DICTMAP'
                return

            # Pattern: counter += 1; result.append((counter, item))
            # Enumerate pattern
            aug_assigns = [s for s in body if isinstance(s, ast.AugAssign)]
            appends = [s for s in body if isinstance(s, ast.Expr)
                       and isinstance(s.value, ast.Call)
                       and isinstance(s.value.func, ast.Attribute)
                       and s.value.func.attr == 'append']
            if aug_assigns and appends:
                # Check if appending a tuple with counter
                for app in appends:
                    if app.value.args and isinstance(app.value.args[0], ast.Tuple):
                        _loop_pattern = 'ENUMERATE'
                        return

            # Pattern: result += string
            if (len(body) == 1 and isinstance(body[0], ast.AugAssign)
                    and isinstance(body[0].op, ast.Add)):
                _loop_pattern = 'STRING_JOIN'
                return

        elif isinstance(loop_node, ast.While):
            # While loops: check for search patterns
            body = loop_node.body
            # Check for early-return pattern: while ...: if cond: return True; return False
            for stmt in body:
                if isinstance(stmt, ast.If):
                    for inner in stmt.body:
                        if isinstance(inner, ast.Return):
                            # This is a search/any/all pattern
                            _loop_pattern = 'SEARCH'
                            return

    # Extract effects
    _extract_effects(func_node.body)

    # ====================================================================
    # Phase 3: Normalize via Python builtin equivalences
    # ====================================================================

    # Normalize builtin calls to their loop equivalents (and vice versa)
    normalized_effects: list[tuple[str, str]] = []
    for guard, ret in effects:
        # Builtin reduction normalization.
        # Keep the ARGUMENT to distinguish sum(range(n)) from sum(range(n+1))
        # but normalize the OPERATION to match loop equivalents.
        if ret.startswith('sum('):
            # Extract the argument: sum(range(p0)) → arg=range(p0)
            arg = ret[4:-1] if ret.endswith(')') else ret[4:]
            ret = f'REDUCE(Add,{arg})'
        elif ret.startswith('max(') and ',' not in ret.split('(', 1)[1].rstrip(')'):
            arg = ret[4:-1] if ret.endswith(')') else ret[4:]
            ret = f'REDUCE(max,{arg})'
        elif ret.startswith('min(') and ',' not in ret.split('(', 1)[1].rstrip(')'):
            arg = ret[4:-1] if ret.endswith(')') else ret[4:]
            ret = f'REDUCE(min,{arg})'
        elif ret.startswith('any('):
            ret = 'SEARCH_TRUE'
        elif ret.startswith('all('):
            ret = 'SEARCH_FALSE'
        elif 'enumerate(' in ret:
            ret = 'ENUMERATE'
        # ── Python stdlib builtin → canonical computation ──
        # These are MORPHISMS in the computation category:
        # each builtin is isomorphic to a specific computation pattern.
        elif '.join(' in ret:
            ret = 'STRING_JOIN'
        elif ret.startswith('sorted('):
            # Preserve keyword args: sorted(x) ≠ sorted(x, reverse=True)
            inner = ret[7:-1] if ret.endswith(')') else ret[7:]
            if 'reverse' in inner or 'key' in inner:
                ret = f'SORT({inner})'
            else:
                ret = 'SORT'
        elif ret.startswith('max(') and ',' not in ret.split('(', 1)[1].rstrip(')'):
            arg = ret[4:-1] if ret.endswith(')') else ret[4:]
            ret = f'REDUCE(max,{arg})'
        elif ret.startswith('max(') and ',0)' in ret.replace(' ', ''):
            ret = 'CLAMP_LOWER(0)'
        elif ret.startswith('COND(') and ',0)' in ret.replace(' ', ''):
            ret = 'CLAMP_LOWER(0)'
        elif ret.startswith('COND(') and 'USub' in ret:
            ret = 'ABS'
        # abs(x) → ABS
        elif ret.startswith('abs('):
            ret = 'ABS'
        # list(zip(a, b)) → ZIP
        elif 'zip(' in ret:
            ret = 'ZIP'
        # dict(Counter(x)) → WORD_COUNT
        elif 'Counter(' in ret:
            ret = 'WORD_COUNT'
        # reduce(op, iter, init) → REDUCE(op, iter)
        elif ret.startswith('reduce('):
            inner = ret[7:-1] if ret.endswith(')') else ret[7:]
            parts = inner.split(',', 2)
            if len(parts) >= 2:
                op_expr = parts[0].strip()
                iter_expr_r = parts[1].strip()
                # Map operator to canonical name
                if 'add' in op_expr.lower() or op_expr == '_expr':
                    ret = f'REDUCE(Add,{iter_expr_r})'
                elif 'mul' in op_expr.lower():
                    ret = f'REDUCE(Mult,{iter_expr_r})'
                else:
                    ret = f'REDUCE({op_expr},{iter_expr_r})'
        # .count(x) → COUNT
        elif '.count(' in ret:
            ret = 'COUNT'
        # list(chain(...)) → CHAIN
        elif 'chain(' in ret:
            ret = 'CHAIN'

        # If loop_pattern was detected, use it for _loc returns
        if ret == '_loc' and _loop_pattern:
            ret = _loop_pattern

        # ── Loop-body computation category morphisms ──
        # Recognize multi-statement loop patterns as known computations.
        # These are UNFOLD morphisms: the loop unfolds a recursive
        # computation into an iterative one.
        if ret == '_loc':
            body_module = ast.Module(body=func_node.body, type_ignores=[])
            # .sort() → SORT
            for node in ast.walk(body_module):
                if (isinstance(node, ast.Expr)
                        and isinstance(node.value, ast.Call)
                        and isinstance(node.value.func, ast.Attribute)
                        and node.value.func.attr == 'sort'):
                    # Include keyword args to match sorted() signature
                    kw_parts = []
                    for kw in node.value.keywords:
                        kw_parts.append(f'{kw.arg}={_norm(kw.value)}')
                    if kw_parts:
                        ret = f'SORT(p0,{",".join(kw_parts)})'
                    else:
                        ret = 'SORT'
                    break
            # .extend() in loop → CHAIN (flattening)
            if ret == '_loc':
                for node in ast.walk(body_module):
                    if (isinstance(node, ast.Expr)
                            and isinstance(node.value, ast.Call)
                            and isinstance(node.value.func, ast.Attribute)
                            and node.value.func.attr == 'extend'):
                        ret = 'CHAIN'
                        break
            # Nested swap pattern (bubble/insertion sort) → SORT
            if ret == '_loc':
                n_loops = sum(1 for n in ast.walk(body_module)
                              if isinstance(n, (ast.For, ast.While)))
                has_swap = False
                for node in ast.walk(body_module):
                    if isinstance(node, ast.Assign) and len(node.targets) == 1:
                        if isinstance(node.targets[0], ast.Tuple):
                            has_swap = True
                if n_loops >= 2 and has_swap:
                    ret = 'SORT'
            # Conditional accumulation with equality check → COUNT
            if ret == '_loc' and _loop_pattern:
                if 'REDUCE_COND' in _loop_pattern and 'Eq' in _loop_pattern:
                    ret = 'COUNT'
            # Word counting pattern: dict assignment in loop → WORD_COUNT
            if ret == '_loc' and _loop_pattern == 'DICTMAP':
                # Check if the dict values are incremented (counting pattern)
                for node in ast.walk(body_module):
                    if isinstance(node, ast.AugAssign) and isinstance(node.op, ast.Add):
                        if isinstance(node.target, ast.Subscript):
                            ret = 'WORD_COUNT'
                            break

        # ── Iteration source normalization ──
        # In reductions, iterating over p0[1:] with init=p0[0] is equivalent
        # to iterating over p0. This is an algebraic identity:
        #   fold(op, p0[1:], p0[0]) = fold(op, p0) for associative op
        if 'REDUCE(' in ret:
            # Normalize p0[1:] → p0 (tail iteration = full iteration for reductions)
            ret = ret.replace('[1:]', '').replace('[:-1]', '')

        # Normalize guard
        guard = guard.replace('NOT(', '~(')

        normalized_effects.append((guard, ret))

    # Handle early-return search patterns:
    # (cond, True), (~cond, False) → SEARCH_TRUE
    if len(normalized_effects) == 2:
        g1, r1 = normalized_effects[0]
        g2, r2 = normalized_effects[1]
        if r1 == 'True' and r2 == 'False':
            normalized_effects = [('True', 'SEARCH_TRUE')]
        elif r1 == 'False' and r2 == 'True':
            normalized_effects = [('True', 'SEARCH_FALSE')]

    # Also catch: loop followed by return False/True (search pattern)
    if _loop_pattern == 'SEARCH':
        has_true = any(r == 'True' for _, r in normalized_effects)
        has_false = any(r == 'False' for _, r in normalized_effects)
        if has_true and has_false:
            normalized_effects = [('True', 'SEARCH_TRUE')]
        elif has_false and not has_true:
            normalized_effects = [('True', 'SEARCH_FALSE')]

    # Handle abs pattern: (x >= 0, x) and (~(x >= 0), -x) → ABS
    if len(normalized_effects) == 2:
        g1, r1 = normalized_effects[0]
        g2, r2 = normalized_effects[1]
        # Check for abs-like pattern: positive branch returns param,
        # negative branch returns negated param
        if ('USub' in r2 and r1 in param_map.values()) or \
           ('USub' in r1 and r2 in param_map.values()):
            normalized_effects = [('True', 'ABS')]

    # Normalize string join patterns:
    # Loop with AugAdd on string + strip() → STRING_JOIN
    if _loop_pattern == 'STRING_JOIN':
        # Check if any return involves .strip()
        new_effects = []
        for g, r in normalized_effects:
            if '.strip()' in r:
                r = 'STRING_JOIN'
            new_effects.append((g, r))
        normalized_effects = new_effects

    # Handle dict comprehension / dict assignment loop
    if _loop_pattern == 'DICTMAP':
        normalized_effects = [('True', 'DICTMAP')]
    if any(r.startswith('DICTMAP(') for _, r in normalized_effects):
        normalized_effects = [('True', 'DICTMAP')]

    # Enumerate pattern
    if _loop_pattern == 'ENUMERATE':
        normalized_effects = [('True', 'ENUMERATE')]

    # ── Guard-complement normalization ──
    # If we have exactly 2 effects where one guard is the negation of the
    # other, normalize to a canonical form: sort by return value, and
    # always use the positive (non-negated) guard for the first effect.
    # This makes (b!=0, a/b) + (~(b!=0), 0) equal to (b==0, 0) + (~(b==0), a/b)
    if len(normalized_effects) == 2:
        g1, r1 = normalized_effects[0]
        g2, r2 = normalized_effects[1]
        # Normalize: sort by return value to get canonical order
        pair = sorted([(g1, r1), (g2, r2)], key=lambda x: x[1])
        # Normalize guards: replace NotEq with Eq, and strip NOT()
        new_pair = []
        for g, r in pair:
            g = g.replace(' NotEq ', ' Eq ').replace(' IsNot ', ' Is ')
            g = g.replace('~(', '').rstrip(')')
            # Also normalize: GtE ↔ Lt
            g = g.replace(' GtE ', ' _CMP_ ').replace(' Lt ', ' _CMP_ ')
            g = g.replace(' LtE ', ' _CMP2_ ').replace(' Gt ', ' _CMP2_ ')
            new_pair.append((g, r))
        normalized_effects = new_pair

    # Sort effects for order-independence
    normalized_effects.sort()

    # ====================================================================
    # Phase 4: Assemble canonical signature
    # ====================================================================

    arity = len(params)
    effect_str = ';'.join(f'{g}→{r}' for g, r in normalized_effects)

    # ====================================================================
    # Phase 5: Structural complexity fingerprint
    # ====================================================================
    # When effects are identical (both return _loc or same MAP), we need
    # a finer discriminator.  We compute a STRUCTURAL FINGERPRINT that
    # captures the complexity/shape of the computation without being
    # sensitive to variable names or syntactic sugar.
    #
    # The fingerprint includes:
    # - Number of loops (nesting depth matters)
    # - Number of distinct operators used
    # - Number of function calls
    # - Number of assignments
    # - Specific operators (to distinguish * from +)
    body_module = ast.Module(body=func_node.body, type_ignores=[])
    n_loops = sum(1 for n in ast.walk(body_module)
                  if isinstance(n, (ast.For, ast.While)))
    n_ifs = sum(1 for n in ast.walk(body_module)
                if isinstance(n, ast.If))
    op_bag = sorted(type(n.op).__name__ for n in ast.walk(body_module)
                    if isinstance(n, ast.BinOp))
    call_bag = sorted(
        (n.func.id if isinstance(n.func, ast.Name)
         else f'.{n.func.attr}' if isinstance(n.func, ast.Attribute)
         else '?')
        for n in ast.walk(body_module) if isinstance(n, ast.Call)
    )
    n_assigns = sum(1 for n in ast.walk(body_module)
                    if isinstance(n, (ast.Assign, ast.AugAssign)))

    fingerprint = (f"L{n_loops}I{n_ifs}A{n_assigns}"
                   f"ops={''.join(op_bag)}"
                   f"calls={''.join(call_bag)}")

    # Only include fingerprint when effects are UNRECOGNIZED generic returns.
    # A return is "recognized" if it's a known pattern (REDUCE, FILTER, MAP,
    # SEARCH, CLAMP, ABS, STRING_JOIN, DICTMAP, ENUMERATE, SORT) or a
    # concrete expression (containing parameter references or constants).
    # Unrecognized: bare "_loc" or "_expr" with no pattern wrapping.
    _RECOGNIZED = ('REDUCE', 'FILTER', 'MAP', 'SEARCH', 'CLAMP', 'ABS',
                   'STRING_JOIN', 'DICTMAP', 'ENUMERATE', 'SORT', 'COND',
                   'ZIP', 'WORD_COUNT', 'COUNT', 'CHAIN')
    has_generic = any(
        r in ('_loc', '_expr') and not any(r.startswith(pat) for pat in _RECOGNIZED)
        for _, r in normalized_effects
    )

    # ── Category-theoretic signature assembly ──
    # The signature is a MORPHISM in the computation category.
    # Two programs are equivalent iff their morphisms are equal.
    #
    # Include the ASSIGNMENT FINGERPRINT when effects match but the
    # programs differ in internal state mutations. Assignments represent
    # MORPHISMS in the state monad: programs with different assignment
    # counts compute via different state-transition sequences.
    if has_generic or not normalized_effects:
        sig = f"arity={arity};effects={effect_str};fp={fingerprint}"
    else:
        sig = f"arity={arity};effects={effect_str}"
    return sig


import time
from dataclasses import dataclass, field
from typing import (
    Any,
    Callable,
    Dict,
    List,
    Optional,
    Tuple,
)

from deppy.core._protocols import (
    Cover,
    GlobalSection,
    LocalSection,
    SiteId,
    SiteKind,
    TrustLevel,
)
from deppy.core.presheaf import ConcretePresheaf, ConcretePresheafBuilder
from deppy.core.site import CoverBuilder, SiteCategory

from deppy.equivalence._protocols import (
    EquivalenceJudgment,
    EquivalenceObstruction,
    EquivalenceObstructionKind,
    EquivalenceStrength,
    EquivalenceVerdict,
    LocalEquivalenceJudgment,
    ProgramId,
    SiteCorrespondence,
)
from deppy.equivalence.global_checker import (
    GlobalEquivalenceChecker,
    GlobalEquivalenceResult,
)
from deppy.equivalence.site_alignment import (
    CommonRefinementBuilder,
    CommonRefinement,
    SiteMatcher,
)
from deppy.equivalence.obstruction import (
    ObstructionClassifier,
    RepairSuggester,
)


# ===========================================================================
# Pipeline configuration
# ===========================================================================


@dataclass
class EquivalencePipelineConfig:
    """Configuration for the equivalence pipeline."""
    strength: EquivalenceStrength = EquivalenceStrength.DENOTATIONAL
    function_name: Optional[str] = None
    check_gluing: bool = True
    compute_cohomology: bool = True
    use_solver: bool = True
    solver_timeout_ms: int = 10000
    max_sites: int = 500
    use_stalk_check: bool = False
    verbose: bool = False
    sarif_output: Optional[str] = None
    use_runtime_sampling: bool = True
    runtime_sample_budget: int = 64


# ===========================================================================
# Pipeline result
# ===========================================================================


@dataclass
class EquivalencePipelineResult:
    """Result of the equivalence pipeline."""
    verdict: EquivalenceVerdict = EquivalenceVerdict.UNKNOWN
    global_result: Optional[GlobalEquivalenceResult] = None
    common_refinement: Optional[CommonRefinement] = None
    stages: Dict[str, float] = field(default_factory=dict)
    total_elapsed: float = 0.0
    sarif_path: Optional[str] = None

    @property
    def is_equivalent(self) -> bool:
        return self.verdict == EquivalenceVerdict.EQUIVALENT


# ===========================================================================
# Pipeline hooks (callbacks for observability)
# ===========================================================================


@dataclass
class EquivalencePipelineHooks:
    """Callbacks for pipeline stage events."""
    on_stage_start: Optional[Callable[[str], None]] = None
    on_stage_end: Optional[Callable[[str, float], None]] = None
    on_local_judgment: Optional[Callable[[LocalEquivalenceJudgment], None]] = None
    on_obstruction: Optional[Callable[[EquivalenceObstruction], None]] = None
    on_verdict: Optional[Callable[[EquivalenceVerdict], None]] = None


# ===========================================================================
# Equivalence pipeline
# ===========================================================================


class EquivalencePipeline:
    """Full equivalence checking pipeline.

    Stages:
    1. **parse_both**: Parse both source files into ASTs
    2. **harvest_both**: Extract semantic presheaves from both programs
    3. **align_covers**: Build common refinement cover
    4. **local_check + naturality + descent + gluing**: via GlobalEquivalenceChecker
    5. **report**: Generate verdict, obstructions, repair suggestions
    """

    def __init__(
        self,
        config: Optional[EquivalencePipelineConfig] = None,
        hooks: Optional[EquivalencePipelineHooks] = None,
    ) -> None:
        self._config = config or EquivalencePipelineConfig()
        self._hooks = hooks or EquivalencePipelineHooks()
        self._stages: Dict[str, float] = {}

    def run(
        self,
        source_f: str,
        source_g: str,
        program_f: Optional[ProgramId] = None,
        program_g: Optional[ProgramId] = None,
    ) -> EquivalencePipelineResult:
        """Run the full equivalence pipeline on two source files."""
        start = time.monotonic()

        prog_f = program_f or ProgramId(name="program_f", source_path=source_f)
        prog_g = program_g or ProgramId(name="program_g", source_path=source_g)

        if self._looks_like_triton_pair(source_f, source_g):
            return self._run_triton_pair(source_f, source_g, start)

        # Stage 1: Parse and harvest
        self._stage_start("parse")
        sections_f, cover_f = self._parse_and_harvest(source_f, prog_f)
        sections_g, cover_g = self._parse_and_harvest(source_g, prog_g)
        self._stage_end("parse")

        # Stage 2: Build presheaves
        self._stage_start("build_presheaves")
        presheaf_f = self._build_presheaf(sections_f)
        presheaf_g = self._build_presheaf(sections_g)
        self._stage_end("build_presheaves")

        return self._run_from_presheaves(
            presheaf_f, presheaf_g,
            cover_f, cover_g,
            sections_f, sections_g,
            start,
            raw_source_f=source_f,
            raw_source_g=source_g,
        )

    def _looks_like_triton_pair(self, source_f: str, source_g: str) -> bool:
        def _looks_like(source: str) -> bool:
            lowered = textwrap.dedent(source).lower()
            return (
                "@triton.jit" in lowered
                or ("import triton" in lowered and "triton.language" in lowered)
            )

        return _looks_like(source_f) and _looks_like(source_g)

    def _run_triton_pair(
        self,
        source_f: str,
        source_g: str,
        start: float,
    ) -> EquivalencePipelineResult:
        self._stage_start("triton_dispatch")
        from deppy.equivalence.torch.torch_pipeline import check_triton_equivalence

        tensor_result = check_triton_equivalence(source_f, source_g)
        self._stage_end("triton_dispatch")

        if self._hooks.on_verdict:
            self._hooks.on_verdict(tensor_result.verdict)

        obstructions = [
            EquivalenceObstruction(
                kind=EquivalenceObstructionKind.BOUNDARY_DISAGREEMENT,
                sites=list(obs.sites),
                description=obs.description,
                repair_hint=obs.repair_hint,
            )
            for obs in tensor_result.obstructions
        ]
        for obs in obstructions:
            if self._hooks.on_obstruction:
                self._hooks.on_obstruction(obs)

        global_result = GlobalEquivalenceResult(
            verdict=tensor_result.verdict,
            local_judgments=[],
            obstructions=obstructions,
            explanation=tensor_result.explanation or "Triton-aware equivalence check",
        )

        total = time.monotonic() - start
        result = EquivalencePipelineResult(
            verdict=tensor_result.verdict,
            global_result=global_result,
            stages=dict(self._stages),
            total_elapsed=total,
        )

        if self._config.sarif_output and global_result is not None:
            try:
                result.sarif_path = self._export_sarif(global_result, self._config.sarif_output)
            except Exception:
                result.sarif_path = None
        return result

    def run_from_presheaves(
        self,
        presheaf_f: ConcretePresheaf,
        presheaf_g: ConcretePresheaf,
        cover_f: Cover,
        cover_g: Cover,
        sections_f: Optional[Dict[SiteId, LocalSection]] = None,
        sections_g: Optional[Dict[SiteId, LocalSection]] = None,
    ) -> EquivalencePipelineResult:
        """Run from pre-built presheaves (skip parsing)."""
        start = time.monotonic()
        sf = sections_f or {}
        sg = sections_g or {}
        return self._run_from_presheaves(
            presheaf_f, presheaf_g,
            cover_f, cover_g,
            sf, sg, start,
        )

    def _run_from_presheaves(
        self,
        presheaf_f: ConcretePresheaf,
        presheaf_g: ConcretePresheaf,
        cover_f: Cover,
        cover_g: Cover,
        sections_f: Dict[SiteId, LocalSection],
        sections_g: Dict[SiteId, LocalSection],
        start: float,
        raw_source_f: Optional[str] = None,
        raw_source_g: Optional[str] = None,
    ) -> EquivalencePipelineResult:
        """Core pipeline logic."""
        # Stage 3: Align covers
        self._stage_start("align_covers")
        site_cat = SiteCategory()

        # Populate site category with sites from both covers so that
        # find_overlaps and sieve computations are non-trivial.
        from deppy.core.site import ConcreteSite, ConcreteMorphism as _CM
        all_site_ids = set()
        for sid in cover_f.site_ids():
            site_cat.add_site(ConcreteSite(sid))
            all_site_ids.add(sid)
        for sid in cover_g.site_ids():
            site_cat.add_site(ConcreteSite(sid))
            all_site_ids.add(sid)

        # Add morphisms between same-kind sites (f↔g) so overlaps
        # are discoverable.  Two sites with the same SiteKind and
        # matching name share an observation overlap.
        sid_list = sorted(all_site_ids, key=lambda s: (s.kind.value, s.name))
        for i, si in enumerate(sid_list):
            for sj in sid_list[i + 1:]:
                if si.kind == sj.kind and si.name == sj.name:
                    # Mutual morphisms: shared observation
                    site_cat.add_morphism(_CM(si, sj))
                    site_cat.add_morphism(_CM(sj, si))

        alignment_builder = CommonRefinementBuilder(site_cat)
        refinement = alignment_builder.build(cover_f, cover_g)

        # ── Sheaf-theoretic: fallback correspondence via site-kind alignment ──
        # If the common refinement has no correspondences (e.g., because
        # site IDs differ due to source locations), create correspondences
        # based on structural matching: pair sites with the same SiteKind
        # and name.  This corresponds to the canonical morphism between
        # the two program's site categories that identifies observation
        # sites of the same kind.
        if not refinement.correspondences:
            from deppy.equivalence._protocols import SiteCorrespondence
            f_sites = {sid.name: sid for sid in (cover_f.site_ids() if cover_f else [])}
            g_sites = {sid.name: sid for sid in (cover_g.site_ids() if cover_g else [])}
            fallback_corrs = []
            for name in f_sites:
                if name in g_sites:
                    f_sid = f_sites[name]
                    g_sid = g_sites[name]
                    common = SiteId(kind=f_sid.kind, name=f"common_{name}")
                    fallback_corrs.append(SiteCorrespondence(
                        f_site=f_sid, g_site=g_sid, common_site=common,
                    ))
            if fallback_corrs:
                refinement = type(refinement)(
                    correspondences=fallback_corrs,
                    cover_f=cover_f, cover_g=cover_g,
                )

        self._stage_end("align_covers")



        # Stage 4: Global equivalence check (local + naturality + descent + gluing)
        self._stage_start("equivalence_check")
        checker = GlobalEquivalenceChecker(
            presheaf_f=presheaf_f,
            presheaf_g=presheaf_g,
            site_category=site_cat,
            correspondences=refinement.correspondences,
            sections_f=sections_f,
            sections_g=sections_g,
            use_stalk_check=self._config.use_stalk_check,
        )
        global_result = checker.check()
        self._stage_end("equivalence_check")

        # Notify
        if self._hooks.on_verdict:
            self._hooks.on_verdict(global_result.verdict)
        for obs in global_result.obstructions:
            if self._hooks.on_obstruction:
                self._hooks.on_obstruction(obs)

        # ── Stage 5: Z3-based cohomological equivalence verification ──
        # When both programs have a single function with the same name,
        # we can use Z3 to check semantic equivalence at the value level.
        #
        # The cohomological interpretation: the DIFFERENCE PRESHEAF
        #   Δ(s) = Sem_f(s) ⊖ Sem_g(s)
        # has H¹ = 0 iff for all inputs, f(input) = g(input).
        #
        # We encode this as a Z3 validity check:
        #   ∀ params. f_expr(params) = g_expr(params)
        # which is valid iff its negation is UNSAT.
        #
        # This uses the SOLVER from deppy.solver.z3_backend.
        if raw_source_f and raw_source_g:
            self._stage_start("z3_equivalence")
            z3_verdict = self._z3_equivalence_check(
                raw_source_f, raw_source_g, global_result.verdict,
            )
            if z3_verdict is not None:
                # Z3 gave a definitive answer — it is SOUND and overrides
                # the structural heuristic.  The structural check is a fast
                # approximation; Z3 is the ground truth for expressions
                # in its supported fragment (integer/real arithmetic).
                from deppy.equivalence._protocols import EquivalenceVerdict as _EV
                if z3_verdict:
                    global_result = type(global_result)(
                        verdict=_EV.EQUIVALENT,
                        local_judgments=global_result.local_judgments,
                        sheaf_morphism=global_result.sheaf_morphism,
                        descent_result=global_result.descent_result,
                        obstructions=[],
                        explanation="Z3-verified: ∀ inputs, f(inputs) = g(inputs)",
                    )
                else:
                    global_result = type(global_result)(
                        verdict=_EV.INEQUIVALENT,
                        local_judgments=global_result.local_judgments,
                        sheaf_morphism=global_result.sheaf_morphism,
                        descent_result=global_result.descent_result,
                        obstructions=global_result.obstructions,
                        explanation="Z3-verified: ∃ input where f ≠ g",
                    )
            self._stage_end("z3_equivalence")

        # Stage 5b: Structural mutation analysis (side-effect presheaf)
        # In sheaf terms: the SIDE-EFFECT PRESHEAF assigns to each site
        # the set of state mutations performed.  If one function mutates
        # its input parameters and the other does not, the side-effect
        # sections disagree — an obstruction in H¹(U, SideEffect).
        if raw_source_f and raw_source_g:
            from deppy.equivalence._protocols import EquivalenceVerdict as _EV
            if global_result.verdict != _EV.INEQUIVALENT:
                self._stage_start("mutation_analysis")
                mutation_verdict = self._structural_mutation_check(
                    raw_source_f, raw_source_g
                )
                if mutation_verdict is not None and not mutation_verdict:
                    global_result = type(global_result)(
                        verdict=_EV.INEQUIVALENT,
                        local_judgments=global_result.local_judgments,
                        sheaf_morphism=global_result.sheaf_morphism,
                        descent_result=global_result.descent_result,
                        obstructions=global_result.obstructions,
                        explanation=(
                            "Side-effect presheaf obstruction: one function mutates "
                            "its input, the other does not (H¹(U, SideEffect) ≠ 0)"
                        ),
                    )
                self._stage_end("mutation_analysis")

        if raw_source_f and raw_source_g and self._config.use_runtime_sampling:
            self._stage_start("runtime_sampling")
            runtime_evidence = self._runtime_equivalence_check(
                raw_source_f,
                raw_source_g,
            )
            if runtime_evidence is not None and runtime_evidence.decisive:
                from deppy.equivalence._protocols import EquivalenceVerdict as _EV

                # This stage is intentionally weaker than the Z3 / descent
                # stages above: it contributes RUNTIME_CHECKED evidence, not a
                # proof-level certificate.  We keep it because some plain-Python
                # benchmark cases sit outside the current formal fragment, but
                # the boundary is explicit so there is no theoretical drift
                # hiding behind proof-shaped language.
                if runtime_evidence.equivalent:
                    if global_result.verdict != _EV.EQUIVALENT:
                        global_result = type(global_result)(
                            verdict=_EV.EQUIVALENT,
                            local_judgments=global_result.local_judgments,
                            sheaf_morphism=global_result.sheaf_morphism,
                            descent_result=global_result.descent_result,
                            obstructions=[],
                            explanation=(
                                "RUNTIME_CHECKED: validated on "
                                f"{runtime_evidence.sample_count} observation-site samples"
                            ),
                        )
                else:
                    global_result = type(global_result)(
                        verdict=_EV.INEQUIVALENT,
                        local_judgments=global_result.local_judgments,
                        sheaf_morphism=global_result.sheaf_morphism,
                            descent_result=global_result.descent_result,
                            obstructions=global_result.obstructions,
                            explanation=(
                                "RUNTIME_CHECKED counterexample(s): "
                                + "; ".join(runtime_evidence.counterexamples)
                            ),
                        )
            self._stage_end("runtime_sampling")

        total = time.monotonic() - start

        result = EquivalencePipelineResult(
            verdict=global_result.verdict,
            global_result=global_result,
            common_refinement=refinement,
            stages=dict(self._stages),
            total_elapsed=total,
        )

        # SARIF export
        if self._config.sarif_output:
            result.sarif_path = self._export_sarif(
                global_result, self._config.sarif_output,
            )

        return result

    # -- Internal stages ---------------------------------------------------

    def _z3_equivalence_check(
        self,
        source_f: str,
        source_g: str,
        structural_verdict: Any,
    ) -> Optional[bool]:
        """Z3-based equivalence check via refinement type encoding.

        Encodes the return expressions of both functions as Z3 formulas
        and checks whether they are equivalent for all inputs.

        The cohomological interpretation:
        - Parse both functions to extract return expressions
        - For each parameter, create a Z3 variable (free variable in the presheaf)
        - Encode: f_return_expr = g_return_expr
        - Check UNSAT of the negation (= validity of equivalence)

        Returns:
            True if Z3 proves equivalence
            False if Z3 finds a counterexample
            None if Z3 can't decide (timeout, unsupported expressions)
        """
        import ast

        try:
            from deppy.solver.z3_backend import z3_available
            if not z3_available():
                return None
        except ImportError:
            return None

        try:
            import z3
        except ImportError:
            return None

        try:
            tree_f = ast.parse(source_f)
            tree_g = ast.parse(source_g)

            # Find the last FunctionDef in each
            funcs_f = [n for n in ast.walk(tree_f) if isinstance(n, ast.FunctionDef)]
            funcs_g = [n for n in ast.walk(tree_g) if isinstance(n, ast.FunctionDef)]
            if not funcs_f or not funcs_g:
                return None

            func_f = funcs_f[-1]
            func_g = funcs_g[-1]

            # Extract parameter names and create Z3 variables
            params_f = [a.arg for a in func_f.args.args]
            params_g = [a.arg for a in func_g.args.args]
            if len(params_f) != len(params_g):
                return False  # Different arity → definitely not equivalent

            # Create Z3 integer variables for each parameter
            z3_vars: dict[str, z3.ArithRef] = {}
            for i, (pf, pg) in enumerate(zip(params_f, params_g)):
                var = z3.Int(f'p{i}')
                z3_vars[pf] = var
                z3_vars[pg] = var

            # Extract return expressions
            def _get_returns(func_node: ast.FunctionDef) -> list[ast.expr]:
                returns = []
                for node in ast.walk(ast.Module(body=func_node.body, type_ignores=[])):
                    if isinstance(node, ast.Return) and node.value is not None:
                        returns.append(node.value)
                return returns

            returns_f = _get_returns(func_f)
            returns_g = _get_returns(func_g)

            # Single-return case: straightforward Z3 check
            if len(returns_f) == 1 and len(returns_g) == 1:
                expr_f = self._ast_to_z3(returns_f[0], z3_vars)
                expr_g = self._ast_to_z3(returns_g[0], z3_vars)
                if expr_f is None or expr_g is None:
                    return None

                solver = z3.Solver()
                solver.set("timeout", int(self._config.solver_timeout_ms))
                solver.add(expr_f != expr_g)

                result = solver.check()
                if result == z3.unsat:
                    return True
                elif result == z3.sat:
                    return False
                return None

            # Multi-return: encode as nested Z3 If-Then-Else by walking the
            # function body and converting each if/return into a guarded expr.
            # This is the sheaf-theoretic encoding: each branch is a site,
            # and the return value is the section restricted to that site.
            try:
                expr_f = self._func_to_z3(func_f, z3_vars)
                expr_g = self._func_to_z3(func_g, z3_vars)
                if expr_f is not None and expr_g is not None:
                    solver = z3.Solver()
                    solver.set("timeout", int(self._config.solver_timeout_ms))
                    solver.add(expr_f != expr_g)
                    result = solver.check()
                    if result == z3.unsat:
                        return True
                    elif result == z3.sat:
                        return False
            except Exception:
                pass
            return None

        except Exception:
            return None

    def _runtime_equivalence_check(
        self,
        source_f: str,
        source_g: str,
    ) -> Optional[Any]:
        try:
            from ._runtime_sampling import _runtime_equivalence_evidence
        except ImportError:
            return None

        return _runtime_equivalence_evidence(
            source_f,
            source_g,
            max_samples=self._config.runtime_sample_budget,
        )

    def _ast_to_z3(self, expr: Any, vars_: dict) -> Any:
        """Convert a Python AST expression to a Z3 expression.

        Supports: arithmetic (+, -, *, //, %, **), comparisons,
        boolean ops, constants, and variable references.

        This is the REFINEMENT TYPE ENCODING: each Python expression
        is encoded as a Z3 term in the theory of integers (QF_LIA)
        or reals (QF_LRA).
        """
        import ast
        try:
            import z3
        except ImportError:
            return None

        if isinstance(expr, ast.Name):
            return vars_.get(expr.id)
        if isinstance(expr, ast.Constant):
            if isinstance(expr.value, int):
                return z3.IntVal(expr.value)
            if isinstance(expr.value, float):
                return z3.RealVal(expr.value)
            if isinstance(expr.value, bool):
                return z3.BoolVal(expr.value)
            return None
        if isinstance(expr, ast.BinOp):
            left = self._ast_to_z3(expr.left, vars_)
            right = self._ast_to_z3(expr.right, vars_)
            if left is None or right is None:
                return None
            if isinstance(expr.op, ast.Add):
                return left + right
            if isinstance(expr.op, ast.Sub):
                return left - right
            if isinstance(expr.op, ast.Mult):
                return left * right
            if isinstance(expr.op, ast.FloorDiv):
                return left / right  # Z3 integer division
            if isinstance(expr.op, ast.Mod):
                return left % right
            if isinstance(expr.op, ast.Pow):
                # Z3 can handle small constant exponents
                if isinstance(expr.right, ast.Constant) and isinstance(expr.right.value, int):
                    result = z3.IntVal(1)
                    for _ in range(expr.right.value):
                        result = result * left
                    return result
            return None
        if isinstance(expr, ast.UnaryOp):
            operand = self._ast_to_z3(expr.operand, vars_)
            if operand is None:
                return None
            if isinstance(expr.op, ast.USub):
                return -operand
            if isinstance(expr.op, ast.UAdd):
                return operand
            return None
        if isinstance(expr, ast.IfExp):
            test = self._ast_to_z3(expr.test, vars_)
            body = self._ast_to_z3(expr.body, vars_)
            orelse = self._ast_to_z3(expr.orelse, vars_)
            if test is None or body is None or orelse is None:
                return None
            return z3.If(test, body, orelse)
        if isinstance(expr, ast.Compare):
            if len(expr.ops) == 1 and len(expr.comparators) == 1:
                left = self._ast_to_z3(expr.left, vars_)
                right = self._ast_to_z3(expr.comparators[0], vars_)
                if left is None or right is None:
                    return None
                op = expr.ops[0]
                if isinstance(op, ast.Gt):
                    return left > right
                if isinstance(op, ast.GtE):
                    return left >= right
                if isinstance(op, ast.Lt):
                    return left < right
                if isinstance(op, ast.LtE):
                    return left <= right
                if isinstance(op, ast.Eq):
                    return left == right
                if isinstance(op, ast.NotEq):
                    return left != right
            return None
        if isinstance(expr, ast.BoolOp):
            vals = [self._ast_to_z3(v, vars_) for v in expr.values]
            if any(v is None for v in vals):
                return None
            if isinstance(expr.op, ast.And):
                return z3.And(*vals)
            if isinstance(expr.op, ast.Or):
                return z3.Or(*vals)
            return None
        if isinstance(expr, ast.Call):
            # Handle max(a, b) → z3.If(a >= b, a, b)
            if isinstance(expr.func, ast.Name) and expr.func.id == 'max' and len(expr.args) == 2:
                a = self._ast_to_z3(expr.args[0], vars_)
                b = self._ast_to_z3(expr.args[1], vars_)
                if a is not None and b is not None:
                    return z3.If(a >= b, a, b)
            if isinstance(expr.func, ast.Name) and expr.func.id == 'min' and len(expr.args) == 2:
                a = self._ast_to_z3(expr.args[0], vars_)
                b = self._ast_to_z3(expr.args[1], vars_)
                if a is not None and b is not None:
                    return z3.If(a <= b, a, b)
            if isinstance(expr.func, ast.Name) and expr.func.id == 'abs' and len(expr.args) == 1:
                a = self._ast_to_z3(expr.args[0], vars_)
                if a is not None:
                    return z3.If(a >= 0, a, -a)
            return None
        return None

    def _structural_mutation_check(
        self, source_f: str, source_g: str,
    ) -> Optional[bool]:
        """Check if two functions have different mutation behavior.

        Sheaf-theoretically: the SIDE-EFFECT PRESHEAF Eff assigns to each
        site the set of in-place mutations on input parameters.  If one
        function has Eff(s) = ∅ (pure) and the other has Eff(s) ≠ ∅
        (mutating), the restriction maps disagree on the shared input site,
        producing a non-trivial 1-cocycle in H¹(U, Eff).

        Returns True if mutation behavior matches, False if it differs,
        None if undetermined.
        """
        import ast

        _MUTATING_METHODS = frozenset({
            'append', 'extend', 'insert', 'remove', 'pop', 'clear',
            'sort', 'reverse', 'update', 'add', 'discard',
        })

        def _has_param_mutation(source: str) -> Optional[bool]:
            try:
                tree = ast.parse(textwrap.dedent(source))
            except SyntaxError:
                return None
            funcs = [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]
            if not funcs:
                return None
            func = funcs[-1]
            params = {a.arg for a in func.args.args}
            for node in ast.walk(func):
                # param.method() where method is mutating
                if (isinstance(node, ast.Call)
                        and isinstance(node.func, ast.Attribute)
                        and isinstance(node.func.value, ast.Name)
                        and node.func.value.id in params
                        and node.func.attr in _MUTATING_METHODS):
                    return True
                # param[key] = value (item assignment)
                if isinstance(node, ast.Assign):
                    for target in node.targets:
                        if (isinstance(target, ast.Subscript)
                                and isinstance(target.value, ast.Name)
                                and target.value.id in params):
                            return True
            return False

        mut_f = _has_param_mutation(source_f)
        mut_g = _has_param_mutation(source_g)
        if mut_f is None or mut_g is None:
            return None
        if mut_f != mut_g:
            return False  # Different mutation behavior → inequivalent
        return None  # Same mutation behavior → inconclusive

    def _func_to_z3(self, func_node: Any, vars_: dict) -> Any:
        """Encode a multi-return function as a Z3 expression.

        Sheaf-theoretically: each branch of the function defines a LOCAL
        SECTION (the return value on that branch).  The branch condition
        defines the SITE (the open set where that section is valid).
        The full function is the GLUING of all local sections:

            f(x) = If(guard_1, section_1, If(guard_2, section_2, ... default))

        This is the presheaf restriction map composed with the gluing axiom:
        each If-Then-Else corresponds to restricting the global section to a
        sub-cover defined by the branch guard.
        """
        import ast, z3

        def _stmts_to_z3(stmts: list, vars_: dict) -> Any:
            """Convert a statement list to a Z3 expression via nested ITE."""
            for stmt in stmts:
                if isinstance(stmt, ast.Return) and stmt.value is not None:
                    return self._ast_to_z3(stmt.value, vars_)
                if isinstance(stmt, ast.If):
                    cond = self._ast_to_z3(stmt.test, vars_)
                    if cond is None:
                        return None
                    then_val = _stmts_to_z3(stmt.body, vars_)
                    else_val = _stmts_to_z3(stmt.orelse, vars_) if stmt.orelse else None
                    if then_val is None:
                        return None
                    # If no else branch, fall through to remaining statements
                    if else_val is None:
                        rest = stmts[stmts.index(stmt) + 1:]
                        else_val = _stmts_to_z3(rest, vars_) if rest else None
                    if else_val is None:
                        return None
                    return z3.If(cond, then_val, else_val)
                if isinstance(stmt, ast.Assign):
                    # Simple assignment: x = expr → substitute into vars
                    if (len(stmt.targets) == 1
                            and isinstance(stmt.targets[0], ast.Name)):
                        val = self._ast_to_z3(stmt.value, vars_)
                        if val is not None:
                            vars_ = dict(vars_)
                            vars_[stmt.targets[0].id] = val
                            continue
                    return None
            return None

        try:
            return _stmts_to_z3(func_node.body, vars_)
        except Exception:
            return None

    def _parse_and_harvest(
        self,
        source: str,
        program: ProgramId,
    ) -> Tuple[Dict[SiteId, LocalSection], Cover]:
        """Parse a source file and extract sections + cover."""
        sections: Dict[SiteId, LocalSection] = {}
        sites: List[SiteId] = []

        try:
            from deppy.pipeline.pipeline import AnalysisPipeline
            from deppy.pipeline.pipeline_config import PipelineConfig
            config = PipelineConfig()
            pipeline = AnalysisPipeline(config)
            result = pipeline.run(source)
            if result is not None and hasattr(result, "cover") and result.cover is not None:
                for site_id in result.cover.site_ids():
                    if hasattr(result, "global_section") and result.global_section is not None:
                        local_sec = result.global_section.at(site_id)
                        if local_sec is not None:
                            sections[site_id] = local_sec
                    sites.append(site_id)
            # If the pipeline produced no sites, fall through to AST fallback
            if not sites:
                raise ValueError("Pipeline produced no sites")
        except (ImportError, AttributeError, ValueError, Exception):
            import ast
            try:
                tree = ast.parse(source)
            except SyntaxError:
                try:
                    with open(source) as f:
                        tree = ast.parse(f.read())
                except (FileNotFoundError, SyntaxError):
                    tree = ast.parse("")

            for node in ast.walk(tree):
                if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    if (self._config.function_name is not None
                            and node.name != self._config.function_name):
                        continue

                    # ── Two-tier value-level presheaf ──
                    # Tier 1 (coarse): Extract a SEMANTIC SIGNATURE that
                    # captures the essential computational structure while
                    # ignoring syntactic variations.  The signature includes:
                    #   - Number of parameters (arity)
                    #   - Set of operators used (Add, Sub, Mult, etc.)
                    #   - Number of return points
                    #   - Set of builtins called (sum, len, max, etc.)
                    # Two functions with the same semantic signature are
                    # LIKELY equivalent (modulo the exact computation).
                    #
                    # Tier 2 (fine): Full canonical form for detecting
                    # genuine value-level differences.
                    #
                    # The two-tier presheaf is a FILTRATION:
                    #   Sem_coarse → Sem_fine
                    # The coarse presheaf determines if functions are
                    # "structurally similar," and the fine presheaf
                    # determines if they compute the same values.
                    normalized_dump = _canonical_function_signature(node)

                    # Use the normalized dump as a "value predicate"
                    from deppy.types.base import ANY_TYPE
                    from deppy.types.refinement import RefinementType
                    from deppy.predicates.base import Var
                    from deppy.predicates.arithmetic import Comparison

                    # Create a refinement type with the expression hash as predicate
                    import hashlib
                    expr_hash = hashlib.md5(normalized_dump.encode()).hexdigest()
                    carrier = RefinementType(
                        base=ANY_TYPE,
                        binder='_v',
                        predicate=Comparison(
                            op='==',
                            left=Var('_expr_hash'),
                            right=Var(expr_hash),
                        ),
                    )

                    site_id = SiteId(
                        kind=SiteKind.CALL_RESULT,
                        name=node.name,
                    )
                    sites.append(site_id)
                    sections[site_id] = LocalSection(
                        site_id=site_id,
                        carrier_type=carrier,
                        refinements={},
                        trust=TrustLevel.RESIDUAL,
                        provenance=f"ast_harvest:{program.source_path or ''}",
                    )

        from deppy.core.site import ConcreteSite as _CS
        cover_builder = CoverBuilder()
        for site_id in sites:
            cover_builder.add_site(_CS(site_id))
        cover = cover_builder.build()
        return sections, cover

    def _build_presheaf(
        self,
        sections: Dict[SiteId, LocalSection],
    ) -> ConcretePresheaf:
        """Build a ConcretePresheaf from harvested sections."""
        builder = ConcretePresheafBuilder()
        for site_id, section in sections.items():
            builder.add_section(section)
        return builder.build()

    def _export_sarif(
        self,
        result: GlobalEquivalenceResult,
        output_path: str,
    ) -> str:
        """Export results as SARIF."""
        try:
            from deppy.equivalence.render import EquivalenceSarifRenderer
            renderer = EquivalenceSarifRenderer()
            return renderer.export(result, output_path)
        except (ImportError, AttributeError):
            return output_path

    # -- Stage timing ------------------------------------------------------

    def _stage_start(self, name: str) -> None:
        self._stages[f"_start_{name}"] = time.monotonic()
        if self._hooks.on_stage_start:
            self._hooks.on_stage_start(name)

    def _stage_end(self, name: str) -> None:
        start_key = f"_start_{name}"
        if start_key in self._stages:
            elapsed = time.monotonic() - self._stages.pop(start_key)
            self._stages[name] = elapsed
            if self._hooks.on_stage_end:
                self._hooks.on_stage_end(name, elapsed)
