"""deppy.static_analysis — sheaf-theoretic program analysis.

This package implements the site-theoretic static analysis foundation:
observation site construction, restriction maps, cover synthesis,
sparsification, value lineage, and section gluing.

No classical CFG/SSA/dominator infrastructure is introduced; the only
structural notion is the observation site category S and its presheaf
of local semantic sections.
"""

from deppy.static_analysis.observation_sites import (
    ArgumentBoundarySiteData,
    BranchGuardSiteData,
    CallResultSiteData,
    ErrorKind,
    ErrorSiteData,
    HeapProtocolSiteData,
    LoopInvariantSiteData,
    ModuleSummarySiteData,
    ProofSiteData,
    ReturnBoundarySiteData,
    SSAValueSiteData,
    SitePayloadSpec,
    SourceSpan,
    TensorIndexingSiteData,
    TensorOrderSiteData,
    TensorShapeSiteData,
    TraceSiteData,
    make_argument_boundary_site,
    make_branch_guard_site,
    make_call_result_site,
    make_error_site,
    make_heap_protocol_site,
    make_loop_invariant_site,
    make_module_summary_site,
    make_proof_site,
    make_return_boundary_site,
    make_ssa_value_site,
    make_tensor_indexing_site,
    make_tensor_order_site,
    make_tensor_shape_site,
    make_trace_site,
)
from deppy.static_analysis.restriction_maps import (
    RestrictionData,
    RestrictionKind,
    apply_restriction,
    find_overlaps,
    make_actual_to_formal_restriction,
    make_alias_chain_restriction,
    make_control_restriction,
    make_error_pullback_restriction,
    make_error_viability_restriction,
    make_field_init_restriction,
    make_input_projection,
    make_lineage_restriction,
    make_output_projection,
    make_pack_transport,
    make_phi_merge_restriction,
    make_proof_transport,
    make_return_to_caller_restriction,
    make_witness_flow_restriction,
    sites_overlap,
)
from deppy.static_analysis.cover_builder import (
    CoverBuilder,
    build_cover,
    build_cover_from_file,
)
from deppy.static_analysis.cover_sparsifier import (
    CompositeSparsifier,
    CoverStats,
    KeepBoundaryAndErrors,
    RemoveDisconnectedSites,
    RemoveRedundantSSASites,
    SparsificationStrategy,
    SummarizeDeepChains,
    TheoryPackSparsifier,
    compute_cover_stats,
    sparsify_cover,
)
from deppy.static_analysis.value_lineage import (
    LineageGraph,
    TransparencyResult,
    analyze_wrapper_transparency,
    error_sites_reachable_from,
    input_sites_influencing_error,
)
from deppy.static_analysis.section_gluing import (
    GluingCheckResult,
    ObstructionBasis,
    ResolutionCandidate,
    assemble_global_section,
    check_gluing_condition,
    extract_obstruction_basis,
    recheck_after_new_section,
)

__all__ = [
    # observation_sites
    "SourceSpan",
    "SitePayloadSpec",
    "ArgumentBoundarySiteData",
    "ReturnBoundarySiteData",
    "SSAValueSiteData",
    "BranchGuardSiteData",
    "CallResultSiteData",
    "TensorShapeSiteData",
    "TensorOrderSiteData",
    "TensorIndexingSiteData",
    "HeapProtocolSiteData",
    "ProofSiteData",
    "TraceSiteData",
    "ErrorKind",
    "ErrorSiteData",
    "LoopInvariantSiteData",
    "ModuleSummarySiteData",
    "make_argument_boundary_site",
    "make_return_boundary_site",
    "make_ssa_value_site",
    "make_branch_guard_site",
    "make_call_result_site",
    "make_tensor_shape_site",
    "make_tensor_order_site",
    "make_tensor_indexing_site",
    "make_heap_protocol_site",
    "make_proof_site",
    "make_trace_site",
    "make_error_site",
    "make_loop_invariant_site",
    "make_module_summary_site",
    # restriction_maps
    "RestrictionKind",
    "RestrictionData",
    "apply_restriction",
    "find_overlaps",
    "sites_overlap",
    "make_lineage_restriction",
    "make_control_restriction",
    "make_phi_merge_restriction",
    "make_actual_to_formal_restriction",
    "make_return_to_caller_restriction",
    "make_pack_transport",
    "make_error_viability_restriction",
    "make_error_pullback_restriction",
    "make_input_projection",
    "make_output_projection",
    "make_proof_transport",
    "make_field_init_restriction",
    "make_alias_chain_restriction",
    "make_witness_flow_restriction",
    # cover_builder
    "CoverBuilder",
    "build_cover",
    "build_cover_from_file",
    # cover_sparsifier
    "SparsificationStrategy",
    "KeepBoundaryAndErrors",
    "RemoveDisconnectedSites",
    "RemoveRedundantSSASites",
    "SummarizeDeepChains",
    "TheoryPackSparsifier",
    "CompositeSparsifier",
    "sparsify_cover",
    "CoverStats",
    "compute_cover_stats",
    # value_lineage
    "LineageGraph",
    "TransparencyResult",
    "analyze_wrapper_transparency",
    "error_sites_reachable_from",
    "input_sites_influencing_error",
    # section_gluing
    "GluingCheckResult",
    "ObstructionBasis",
    "ResolutionCandidate",
    "check_gluing_condition",
    "assemble_global_section",
    "extract_obstruction_basis",
    "recheck_after_new_section",
]
