# ════════════════════════════════════════════════════════════════════
# CCTT Proof-Annotated Source — sympy
# Generated by Cohomological Cubical Type Theory Library Proof Orchestrator
#
# Every spec is a PATH THEOREM: Path(f(x), expected(x)) over {x : InputType}
# Every proof inhabits the path type.
# Every annotation is COMPILABLE: @cctt_verify JSON is machine-checkable.
#
# Trust levels:
#   🟢 KERNEL   — Refl / Z3 (machine-checked path)
#   🔵 MATHLIB  — Lean4/Mathlib theorem (proof-assistant verified path)
#   🟡 LIBRARY  — LibraryAxiom (sound if dependency correct)
#   🟠 INFERRED — LLM-selected strategy, checker-verified
#   🔴 ASSUMED  — explicitly assumed
#   ❌ FAILED   — proof did not compile
# ════════════════════════════════════════════════════════════════════

from sympy.combinatorics.group_constructs import DirectProduct
from sympy.combinatorics.named_groups import CyclicGroup, DihedralGroup


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(test_direct_product_n(), G.order() == 64 and G.degree == 12 and len(G.orbits()) == 3 and G.is_abelian is True and H.order() == 32 and H.is_abelian is False) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4 Spec [static] strength=formal                           ║
# ║   ensures:  G.order() == 64                                ║
# ║   ensures:  G.degree == 12                                 ║
# ║   ensures:  len(G.orbits()) == 3                           ║
# ╠════════════════════════════════════════════════════════════╣
# ║ test_direct_product_n : Any → {Any | result satisfies...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ C4: assumed | ✓0 ?1 ✗0 VCs | 0.1ms                         ║
# ║   F* binding: ✓                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | dc262ed2a0475f83  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.combinatorics.tests.test_group_constructs.test_direct_product_n","kind":"function","src_hash":"a8a93a1292f50675","in":{"base":"Any"},"out":{"base":"Any","pred":"result satisfies: G.order() == 64 and G.degree == 12 and len(G.orbits()) == 3 and G.is_abelian is True and H.order() == 32 and H.is_abelian is False"},"spec":{"lhs":"test_direct_product_n()","rhs":"G.order() == 64 and G.degree == 12 and len(G.orbits()) == 3 and G.is_abelian is True and H.order() == 32 and H.is_abelian is False","over":{"base":"Any"},"name":"test_direct_product_n_correct"},"guarantee":"G.order() == 64; G.degree == 12; len(G.orbits()) == 3","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.combinatorics.tests.test_group_constructs.test_direct_product_n_correct","statement":"Path(test_direct_product_n(x), G.order() == 64; G.degree == 12; len(G.orbits()) == 3)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"dc262ed2a0475f83","spec_source":"static","formal_spec":{"source":"static","strength":"formal","ensures":["G.order() == 64","G.degree == 12","len(G.orbits()) == 3","G.is_abelian is True","H.order() == 32","H.is_abelian is False"],"pure":true},"c4_verdict":{"valid":true,"n_vcs":1,"n_verified":0,"n_assumed":1,"n_failed":0,"trust_level":"LIBRARY_ASSUMED","compile_ms":0.1,"verdict_class":"assumed","binding":true}}
def test_direct_product_n():
    C = CyclicGroup(4)
    D = DihedralGroup(4)
    G = DirectProduct(C, C, C)
    assert G.order() == 64
    assert G.degree == 12
    assert len(G.orbits()) == 3
    assert G.is_abelian is True
    H = DirectProduct(D, C)
    assert H.order() == 32
    assert H.is_abelian is False
