# ════════════════════════════════════════════════════════════════════
# CCTT Proof-Annotated Source — sympy
# Generated by Cohomological Cubical Type Theory Library Proof Orchestrator
#
# Every spec is a PATH THEOREM: Path(f(x), expected(x)) over {x : InputType}
# Every proof inhabits the path type.
# Every annotation is COMPILABLE: @cctt_verify JSON is machine-checkable.
#
# Trust levels:
#   🟢 KERNEL   — Refl / Z3 (machine-checked path)
#   🔵 MATHLIB  — Lean4/Mathlib theorem (proof-assistant verified path)
#   🟡 LIBRARY  — LibraryAxiom (sound if dependency correct)
#   🟠 INFERRED — LLM-selected strategy, checker-verified
#   🔴 ASSUMED  — explicitly assumed
#   ❌ FAILED   — proof did not compile
# ════════════════════════════════════════════════════════════════════

"""Singleton mechanism"""

from __future__ import annotations

from typing import TYPE_CHECKING

from .core import Registry
from .sympify import sympify


if TYPE_CHECKING:
    from sympy.core.numbers import (
        Zero as _Zero,
        One as _One,
        NegativeOne as _NegativeOne,
        Half as _Half,
        Infinity as _Infinity,
        NegativeInfinity as _NegativeInfinity,
        ComplexInfinity as _ComplexInfinity,
        NaN as _NaN,
    )


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Invariant(correctly constructs a SingletonRegistry instance) preserved by SingletonRegistry(*args) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ SingletonRegistry : Any → Any                              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 12a0f5fcf7b996a8  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.core.singleton.SingletonRegistry","kind":"class","src_hash":"72fef474c4bfbb73","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"SingletonRegistry(*args)","rhs":"correctly constructs a SingletonRegistry instance","over":{"base":"Any"},"name":"SingletonRegistry_class_invariant","kind":"invariant"},"guarantee":"correctly constructs a SingletonRegistry instance","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"invariants":[{"name":"representation","pred":"hasattr(self, '_classes_to_install')","kind":"class","induction":"structural on _classes_to_install"}],"methods_preserving":["__init__","register","__getattr__","__repr__"]},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"12a0f5fcf7b996a8"}
class SingletonRegistry(Registry):
    """
    The registry for the singleton classes (accessible as ``S``).

    Explanation
    ===========

    This class serves as two separate things.

    The first thing it is is the ``SingletonRegistry``. Several classes in
    SymPy appear so often that they are singletonized, that is, using some
    metaprogramming they are made so that they can only be instantiated once
    (see the :class:`sympy.core.singleton.Singleton` class for details). For
    instance, every time you create ``Integer(0)``, this will return the same
    instance, :class:`sympy.core.numbers.Zero`. All singleton instances are
    attributes of the ``S`` object, so ``Integer(0)`` can also be accessed as
    ``S.Zero``.

    Singletonization offers two advantages: it saves memory, and it allows
    fast comparison. It saves memory because no matter how many times the
    singletonized objects appear in expressions in memory, they all point to
    the same single instance in memory. The fast comparison comes from the
    fact that you can use ``is`` to compare exact instances in Python
    (usually, you need to use ``==`` to compare things). ``is`` compares
    objects by memory address, and is very fast.

    Examples
    ========

    >>> from sympy import S, Integer
    >>> a = Integer(0)
    >>> a is S.Zero
    True

    For the most part, the fact that certain objects are singletonized is an
    implementation detail that users should not need to worry about. In SymPy
    library code, ``is`` comparison is often used for performance purposes
    The primary advantage of ``S`` for end users is the convenient access to
    certain instances that are otherwise difficult to type, like ``S.Half``
    (instead of ``Rational(1, 2)``).

    When using ``is`` comparison, make sure the argument is sympified. For
    instance,

    >>> x = 0
    >>> x is S.Zero
    False

    This problem is not an issue when using ``==``, which is recommended for
    most use-cases:

    >>> 0 == S.Zero
    True

    The second thing ``S`` is is a shortcut for
    :func:`sympy.core.sympify.sympify`. :func:`sympy.core.sympify.sympify` is
    the function that converts Python objects such as ``int(1)`` into SymPy
    objects such as ``Integer(1)``. It also converts the string form of an
    expression into a SymPy expression, like ``sympify("x**2")`` ->
    ``Symbol("x")**2``. ``S(1)`` is the same thing as ``sympify(1)``
    (basically, ``S.__call__`` has been defined to call ``sympify``).

    This is for convenience, since ``S`` is a single letter. It's mostly
    useful for defining rational numbers. Consider an expression like ``x +
    1/2``. If you enter this directly in Python, it will evaluate the ``1/2``
    and give ``0.5``, because both arguments are ints (see also
    :ref:`tutorial-gotchas-final-notes`). However, in SymPy, you usually want
    the quotient of two integers to give an exact rational number. The way
    Python's evaluation works, at least one side of an operator needs to be a
    SymPy object for the SymPy evaluation to take over. You could write this
    as ``x + Rational(1, 2)``, but this is a lot more typing. A shorter
    version is ``x + S(1)/2``. Since ``S(1)`` returns ``Integer(1)``, the
    division will return a ``Rational`` type, since it will call
    ``Integer.__truediv__``, which knows how to return a ``Rational``.

    """
    __slots__ = ()

    Zero: _Zero
    One: _One
    NegativeOne: _NegativeOne
    Half: _Half
    Infinity: _Infinity
    NegativeInfinity: _NegativeInfinity
    ComplexInfinity: _ComplexInfinity
    NaN: _NaN

    # Also allow things like S(5)
    __call__ = staticmethod(sympify)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__init__(), initializes the instance correctly) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __init__ : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | f250d84b4260ea90           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.core.singleton.SingletonRegistry.__init__","kind":"method","src_hash":"e2073f34d068facc","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__init__()","rhs":"initializes the instance correctly","over":{"base":"Any"},"name":"__init___correct"},"guarantee":"initializes the instance correctly","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"f250d84b4260ea90"}
    def __init__(self):
        self._classes_to_install = {}
        # Dict of classes that have been registered, but that have not have been
        # installed as an attribute of this SingletonRegistry.
        # Installation automatically happens at the first attempt to access the
        # attribute.
        # The purpose of this is to allow registration during class
        # initialization during import, but not trigger object creation until
        # actual use (which should not happen until after all imports are
        # finished).

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(register(cls), register produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ register : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 9daa56b1cf98bccc  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.core.singleton.SingletonRegistry.register","kind":"method","src_hash":"03712d1ce225cb98","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"register(cls)","rhs":"register produces the expected output","over":{"base":"Any"},"name":"register_correct"},"guarantee":"register produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.core.singleton.SingletonRegistry.register_correct","statement":"Path(register(x), register produces the expected output)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"9daa56b1cf98bccc"}
    def register(self, cls):
        # Make sure a duplicate class overwrites the old one
        if hasattr(self, cls.__name__):
            delattr(self, cls.__name__)
        self._classes_to_install[cls.__name__] = cls

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__getattr__(nam), python calls __getattr__ if no attribute of that name was installed yet) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __getattr__ : Any → Any                                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 8c17f6a234f31144           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.core.singleton.SingletonRegistry.__getattr__","kind":"method","src_hash":"41ade3ffbb66439d","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__getattr__(nam)","rhs":"python calls __getattr__ if no attribute of that name was installed yet","over":{"base":"Any"},"name":"__getattr___correct"},"guarantee":"python calls __getattr__ if no attribute of that name was installed yet","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"8c17f6a234f31144"}
    def __getattr__(self, name):
        """Python calls __getattr__ if no attribute of that name was installed
        yet.

        Explanation
        ===========

        This __getattr__ checks whether a class with the requested name was
        already registered but not installed; if no, raises an AttributeError.
        Otherwise, retrieves the class, calculates its singleton value, installs
        it as an attribute of the given name, and unregisters the class."""
        if name not in self._classes_to_install:
            raise AttributeError(
                "Attribute '%s' was not installed on SymPy registry %s" % (
                name, self))
        class_to_install = self._classes_to_install[name]
        value_to_install = class_to_install()
        self.__setattr__(name, value_to_install)
        del self._classes_to_install[name]
        return value_to_install

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__repr__(), returns a faithful string representation) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __repr__ : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 0453820912b69d6d           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.core.singleton.SingletonRegistry.__repr__","kind":"method","src_hash":"c6d05dc41b4cc93b","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__repr__()","rhs":"returns a faithful string representation","over":{"base":"Any"},"name":"__repr___correct"},"guarantee":"returns a faithful string representation","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"0453820912b69d6d"}
    def __repr__(self):
        return "S"

S = SingletonRegistry()


# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(Singleton(*args), correctly constructs a Singleton instance) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Singleton : Any → Any                                      ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 920ea0d77a311575  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.core.singleton.Singleton","kind":"class","src_hash":"f48b84ae772833f1","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"Singleton(*args)","rhs":"correctly constructs a Singleton instance","over":{"base":"Any"},"name":"Singleton_class_invariant"},"guarantee":"correctly constructs a Singleton instance","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"920ea0d77a311575"}
class Singleton(type):
    """
    Metaclass for singleton classes.

    Explanation
    ===========

    A singleton class has only one instance which is returned every time the
    class is instantiated. Additionally, this instance can be accessed through
    the global registry object ``S`` as ``S.<class_name>``.

    Examples
    ========

        >>> from sympy import S, Basic
        >>> from sympy.core.singleton import Singleton
        >>> class MySingleton(Basic, metaclass=Singleton):
        ...     pass
        >>> Basic() is Basic()
        False
        >>> MySingleton() is MySingleton()
        True
        >>> S.MySingleton is MySingleton()
        True

    Notes
    =====

    Instance creation is delayed until the first time the value is accessed.
    (SymPy versions before 1.0 would create the instance during class
    creation time, which would be prone to import cycles.)
    """
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__init__(cls), initializes the instance correctly) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __init__ : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 5aac23a7e25607ff           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.core.singleton.Singleton.__init__","kind":"method","src_hash":"71e3ee33a8d6f352","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__init__(cls)","rhs":"initializes the instance correctly","over":{"base":"Any"},"name":"__init___correct"},"guarantee":"initializes the instance correctly","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"5aac23a7e25607ff"}
    def __init__(cls, *args, **kwargs):
        cls._instance = obj = Basic.__new__(cls)
        cls.__new__ = lambda cls: obj
        cls.__getnewargs__ = lambda obj: ()
        cls.__getstate__ = lambda obj: None
        S.register(cls)


# Delayed to avoid cyclic import
from .basic import Basic
