# ════════════════════════════════════════════════════════════════════
# CCTT Proof-Annotated Source — sympy
# Generated by Cohomological Cubical Type Theory Library Proof Orchestrator
#
# Every spec is a PATH THEOREM: Path(f(x), expected(x)) over {x : InputType}
# Every proof inhabits the path type.
# Every annotation is COMPILABLE: @cctt_verify JSON is machine-checkable.
#
# Trust levels:
#   🟢 KERNEL   — Refl / Z3 (machine-checked path)
#   🔵 MATHLIB  — Lean4/Mathlib theorem (proof-assistant verified path)
#   🟡 LIBRARY  — LibraryAxiom (sound if dependency correct)
#   🟠 INFERRED — LLM-selected strategy, checker-verified
#   🔴 ASSUMED  — explicitly assumed
#   ❌ FAILED   — proof did not compile
# ════════════════════════════════════════════════════════════════════

"""Implementation of :class:`ComplexField` class. """


from sympy.external.gmpy import SYMPY_INTS
from sympy.core.numbers import Float, I
from sympy.polys.domains.characteristiczero import CharacteristicZero
from sympy.polys.domains.field import Field
from sympy.polys.domains.gaussiandomains import QQ_I
from sympy.polys.domains.simpledomain import SimpleDomain
from sympy.polys.polyerrors import DomainError, CoercionFailed
from sympy.utilities import public

from mpmath import MPContext


@public
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Invariant(correctly constructs a ComplexField instance) preserved by ComplexField(*args) over {Any | isinstance(x, SYMPY_INTS) and isinstance(other, ComplexField)} ║
# ╠════════════════════════════════════════════════════════════╣
# ║ ComplexField : {Any | isinstance(x, SYMPY_INTS) and i...   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | dd99b12a34fcb2fa  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField","kind":"class","src_hash":"865b456cbeb03f93","in":{"base":"Any","pred":"isinstance(x, SYMPY_INTS) and isinstance(other, ComplexField)"},"out":{"base":"Any"},"spec":{"lhs":"ComplexField(*args)","rhs":"correctly constructs a ComplexField instance","over":{"base":"Any","pred":"isinstance(x, SYMPY_INTS) and isinstance(other, ComplexField)"},"name":"ComplexField_class_invariant","kind":"invariant"},"guarantee":"correctly constructs a ComplexField instance","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"invariants":[{"name":"representation","pred":"hasattr(self, '_context') and hasattr(self, '_dtype') and hasattr(self, 'zero') and hasattr(self, 'one') and hasattr(self, '_max_denom') and hasattr(self, '_tolerance')","kind":"class","induction":"structural on _context, _dtype, zero, one"}],"methods_preserving":["has_default_precision","precision","dps","tolerance","__init__","tp","dtype","__eq__","__hash__","to_sympy","from_sympy","from_ZZ","from_ZZ_gmpy","from_ZZ_python","from_QQ","from_QQ_python","from_QQ_gmpy","from_GaussianIntegerRing","from_GaussianRationalField","from_AlgebraicField","from_RealField","from_ComplexField","get_ring","get_exact","is_negative","is_positive","is_nonnegative","is_nonpositive","gcd","lcm","almosteq","is_square","exsqrt"]},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"dd99b12a34fcb2fa"}
class ComplexField(Field, CharacteristicZero, SimpleDomain):
    """Complex numbers up to the given precision. """

    rep = 'CC'

    is_ComplexField = is_CC = True

    is_Exact = False
    is_Numerical = True

    has_assoc_Ring = False
    has_assoc_Field = True

    _default_precision = 53

    @property
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(has_default_precision(), returns the has_default_precision attribute) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ has_default_precision : Any → Any                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | a8f390ca6bc70233           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.has_default_precision","kind":"property","src_hash":"a6adfe6144907594","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"has_default_precision()","rhs":"returns the has_default_precision attribute","over":{"base":"Any"},"name":"has_default_precision_correct"},"guarantee":"returns the has_default_precision attribute","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"a8f390ca6bc70233"}
    def has_default_precision(self):
        return self.precision == self._default_precision

    @property
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(precision(), returns the precision attribute) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ precision : Any → Any                                      ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 094b7fe983e10e68           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.precision","kind":"property","src_hash":"9e877f5631bd9af2","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"precision()","rhs":"returns the precision attribute","over":{"base":"Any"},"name":"precision_correct"},"guarantee":"returns the precision attribute","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"094b7fe983e10e68"}
    def precision(self):
        return self._context.prec

    @property
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(dps(), returns the dps attribute) over Any            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ dps : Any → Any                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 96763342a9b5d774           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.dps","kind":"property","src_hash":"37cd1a05ff3d8dbf","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"dps()","rhs":"returns the dps attribute","over":{"base":"Any"},"name":"dps_correct"},"guarantee":"returns the dps attribute","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"96763342a9b5d774"}
    def dps(self):
        return self._context.dps

    @property
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(tolerance(), returns the tolerance attribute) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ tolerance : Any → Any                                      ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 7235a05ef3eef4d9           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.tolerance","kind":"property","src_hash":"aee2c2366103395c","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"tolerance()","rhs":"returns the tolerance attribute","over":{"base":"Any"},"name":"tolerance_correct"},"guarantee":"returns the tolerance attribute","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"7235a05ef3eef4d9"}
    def tolerance(self):
        return self._tolerance

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__init__(pre), initializes the instance correctly) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __init__ : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 384ad239e346b9f0           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.__init__","kind":"method","src_hash":"0971b3d561625595","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__init__(pre)","rhs":"initializes the instance correctly","over":{"base":"Any"},"name":"__init___correct"},"guarantee":"initializes the instance correctly","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"384ad239e346b9f0"}
    def __init__(self, prec=None, dps=None, tol=None):
        # XXX: The tolerance parameter is ignored but is kept for backward
        # compatibility for now.

        context = MPContext()

        if prec is None and dps is None:
            context.prec = self._default_precision
        elif dps is None:
            context.prec = prec
        elif prec is None:
            context.dps = dps
        else:
            raise TypeError("Cannot set both prec and dps")

        self._context = context

        self._dtype = context.mpc
        self.zero = self.dtype(0)
        self.one = self.dtype(1)

        # XXX: Neither of these is actually used anywhere.
        self._max_denom = max(2**context.prec // 200, 99)
        self._tolerance = self.one / self._max_denom

    @property
# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(tp(), returns the tp attribute) over Any              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ tp : Any → Any                                             ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | c94dfedd407284b9           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.tp","kind":"property","src_hash":"1e2cb817cb906c69","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"tp()","rhs":"returns the tp attribute","over":{"base":"Any"},"name":"tp_correct"},"guarantee":"returns the tp attribute","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"c94dfedd407284b9"}
    def tp(self):
        # XXX: Domain treats tp as an alias of dtype. Here we need two separate
        # things: dtype is a callable to make/convert instances. We use tp with
        # isinstance to check if an object is an instance of the domain
        # already.
        return self._dtype

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(dtype(x, ), dtype produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ dtype : Any → Any                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 8143f8ceada13d10  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.dtype","kind":"method","src_hash":"2ca549c1c97974af","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"dtype(x, )","rhs":"dtype produces the expected output","over":{"base":"Any"},"name":"dtype_correct"},"guarantee":"dtype produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.polys.domains.complexfield.ComplexField.dtype_correct","statement":"Path(dtype(x), dtype produces the expected output)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"8143f8ceada13d10"}
    def dtype(self, x, y=0):
        # XXX: This is needed because mpmath does not recognise fmpz.
        # It might be better to add conversion routines to mpmath and if that
        # happens then this can be removed.
        if isinstance(x, SYMPY_INTS):
            x = int(x)
        if isinstance(y, SYMPY_INTS):
            y = int(y)
        return self._dtype(x, y)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__eq__(oth), correctly determines equality) over Any  ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __eq__ : Any → Any                                         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | d2f1db76c33fc346           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.__eq__","kind":"method","src_hash":"2857d6ca4b7f2280","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__eq__(oth)","rhs":"correctly determines equality","over":{"base":"Any"},"name":"__eq___correct"},"guarantee":"correctly determines equality","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"d2f1db76c33fc346"}
    def __eq__(self, other):
        return isinstance(other, ComplexField) and self.precision == other.precision

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(__hash__(), returns a consistent hash value) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ __hash__ : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | b3a0859da4cfb93a           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.__hash__","kind":"method","src_hash":"511145f7d0943809","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"__hash__()","rhs":"returns a consistent hash value","over":{"base":"Any"},"name":"__hash___correct"},"guarantee":"returns a consistent hash value","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"b3a0859da4cfb93a"}
    def __hash__(self):
        return hash((self.__class__.__name__, self._dtype, self.precision))

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(to_sympy(ele), convert ``element`` to sympy number) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ to_sympy : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 8df91764515a53d2           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.to_sympy","kind":"method","src_hash":"1efe56b167ddc30d","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"to_sympy(ele)","rhs":"convert ``element`` to sympy number","over":{"base":"Any"},"name":"to_sympy_correct"},"guarantee":"convert ``element`` to sympy number","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"8df91764515a53d2"}
    def to_sympy(self, element):
        """Convert ``element`` to SymPy number. """
        return Float(element.real, self.dps) + I*Float(element.imag, self.dps)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_sympy(exp), convert sympy's number to ``dtype``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_sympy : Any → Any                                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | e6edf914782facb0  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_sympy","kind":"method","src_hash":"7525513d65a84889","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_sympy(exp)","rhs":"convert sympy's number to ``dtype``","over":{"base":"Any"},"name":"from_sympy_correct"},"guarantee":"convert sympy's number to ``dtype``","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.polys.domains.complexfield.ComplexField.from_sympy_correct","statement":"Path(from_sympy(x), convert sympy's number to ``dtype``)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"e6edf914782facb0"}
    def from_sympy(self, expr):
        """Convert SymPy's number to ``dtype``. """
        number = expr.evalf(n=self.dps)
        real, imag = number.as_real_imag()

        if real.is_Number and imag.is_Number:
            return self.dtype(real, imag)
        else:
            raise CoercionFailed("expected complex number, got %s" % expr)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_ZZ(ele), from_ZZ produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_ZZ : Any → Any                                        ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | a6e2d29d5c714fc5           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_ZZ","kind":"method","src_hash":"1b0d7775be0da97a","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_ZZ(ele)","rhs":"from_ZZ produces the expected output","over":{"base":"Any"},"name":"from_ZZ_correct"},"guarantee":"from_ZZ produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"a6e2d29d5c714fc5"}
    def from_ZZ(self, element, base):
        return self.dtype(element)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_ZZ_gmpy(ele), from_ZZ_gmpy produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_ZZ_gmpy : Any → Any                                   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 74db69eeec4ccf12           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_ZZ_gmpy","kind":"method","src_hash":"88ef4c25c3fb0cee","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_ZZ_gmpy(ele)","rhs":"from_ZZ_gmpy produces the expected output","over":{"base":"Any"},"name":"from_ZZ_gmpy_correct"},"guarantee":"from_ZZ_gmpy produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"74db69eeec4ccf12"}
    def from_ZZ_gmpy(self, element, base):
        return self.dtype(int(element))

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_ZZ_python(ele), from_ZZ_python produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_ZZ_python : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 0ab76f7235c8eacf           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_ZZ_python","kind":"method","src_hash":"6f5ad1a1eef4d2e3","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_ZZ_python(ele)","rhs":"from_ZZ_python produces the expected output","over":{"base":"Any"},"name":"from_ZZ_python_correct"},"guarantee":"from_ZZ_python produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"0ab76f7235c8eacf"}
    def from_ZZ_python(self, element, base):
        return self.dtype(element)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_QQ(ele), from_QQ produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_QQ : Any → Any                                        ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 6ed4d0d94d3ec127           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_QQ","kind":"method","src_hash":"01d89dac51c96788","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_QQ(ele)","rhs":"from_QQ produces the expected output","over":{"base":"Any"},"name":"from_QQ_correct"},"guarantee":"from_QQ produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"6ed4d0d94d3ec127"}
    def from_QQ(self, element, base):
        return self.dtype(int(element.numerator)) / int(element.denominator)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_QQ_python(ele), from_QQ_python produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_QQ_python : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 59bd9dcfa34a0ca7           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_QQ_python","kind":"method","src_hash":"1b15197adf4c4956","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_QQ_python(ele)","rhs":"from_QQ_python produces the expected output","over":{"base":"Any"},"name":"from_QQ_python_correct"},"guarantee":"from_QQ_python produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"59bd9dcfa34a0ca7"}
    def from_QQ_python(self, element, base):
        return self.dtype(element.numerator) / element.denominator

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_QQ_gmpy(ele), from_QQ_gmpy produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_QQ_gmpy : Any → Any                                   ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 6bf06d143b55ed8e           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_QQ_gmpy","kind":"method","src_hash":"1db8f3d58062c771","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_QQ_gmpy(ele)","rhs":"from_QQ_gmpy produces the expected output","over":{"base":"Any"},"name":"from_QQ_gmpy_correct"},"guarantee":"from_QQ_gmpy produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"6bf06d143b55ed8e"}
    def from_QQ_gmpy(self, element, base):
        return self.dtype(int(element.numerator)) / int(element.denominator)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_GaussianIntegerRing(ele), from_GaussianIntegerRing produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_GaussianIntegerRing : Any → Any                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 396faab20c59fd2a           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_GaussianIntegerRing","kind":"method","src_hash":"8f3a408803000e00","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_GaussianIntegerRing(ele)","rhs":"from_GaussianIntegerRing produces the expected output","over":{"base":"Any"},"name":"from_GaussianIntegerRing_correct"},"guarantee":"from_GaussianIntegerRing produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"396faab20c59fd2a"}
    def from_GaussianIntegerRing(self, element, base):
        return self.dtype(int(element.x), int(element.y))

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_GaussianRationalField(ele), id) over Any         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_GaussianRationalField : Any → Any                     ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | path_compose | Compiled: ✓ | 9273194565e7d891   ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_GaussianRationalField","kind":"method","src_hash":"e998d26f53d3c4be","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_GaussianRationalField(ele)","rhs":"from_GaussianRationalField produces the expected output","over":{"base":"Any"},"name":"from_GaussianRationalField_correct","kind":"composition"},"guarantee":"from_GaussianRationalField produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"path_compose","details":{"steps":[{"fn":"dtype","by":"library_axiom"},{"fn":"int","by":"library_axiom"},{"fn":"int","by":"library_axiom"}]},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"9273194565e7d891"}
    def from_GaussianRationalField(self, element, base):
        x = element.x
        y = element.y
        return (self.dtype(int(x.numerator)) / int(x.denominator) +
                self.dtype(0, int(y.numerator)) / int(y.denominator))

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_AlgebraicField(ele), from_AlgebraicField produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_AlgebraicField : Any → Any                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | c3cb4c13cc1a512d           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_AlgebraicField","kind":"method","src_hash":"a9d9f3b541fbaeb4","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_AlgebraicField(ele)","rhs":"from_AlgebraicField produces the expected output","over":{"base":"Any"},"name":"from_AlgebraicField_correct"},"guarantee":"from_AlgebraicField produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"c3cb4c13cc1a512d"}
    def from_AlgebraicField(self, element, base):
        return self.from_sympy(base.to_sympy(element).evalf(self.dps))

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_RealField(ele), from_RealField produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_RealField : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | e3b0787eba7056de           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_RealField","kind":"method","src_hash":"60fb4af6af36a537","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_RealField(ele)","rhs":"from_RealField produces the expected output","over":{"base":"Any"},"name":"from_RealField_correct"},"guarantee":"from_RealField produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"e3b0787eba7056de"}
    def from_RealField(self, element, base):
        return self.dtype(element)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(from_ComplexField(ele), from_ComplexField produces the expected output) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ from_ComplexField : Any → Any                              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 464abfa94ab382a4           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.from_ComplexField","kind":"method","src_hash":"4551d1165b2f53fe","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"from_ComplexField(ele)","rhs":"from_ComplexField produces the expected output","over":{"base":"Any"},"name":"from_ComplexField_correct"},"guarantee":"from_ComplexField produces the expected output","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"464abfa94ab382a4"}
    def from_ComplexField(self, element, base):
        return self.dtype(element)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(get_ring(), returns a ring associated with ``self``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ get_ring : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   z3.Solver.check                                          ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | library_axiom | Compiled: ✓ | 1ca3faa0d40e62d0  ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.get_ring","kind":"method","src_hash":"d106ec6feb80353e","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"get_ring()","rhs":"returns a ring associated with ``self``","over":{"base":"Any"},"name":"get_ring_correct"},"guarantee":"returns a ring associated with ``self``","fibers":[],"h1":0,"paths":[],"strategy":"library_axiom","details":{"library":"sympy","axiom_name":"sympy.polys.domains.complexfield.ComplexField.get_ring_correct","statement":"Path(get_ring(x), returns a ring associated with ``self``)"},"assumes":[],"trust":["z3.Solver.check"],"compiled":true,"vhash":"1ca3faa0d40e62d0"}
    def get_ring(self):
        """Returns a ring associated with ``self``. """
        raise DomainError("there is no ring associated with %s" % self)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(get_exact(), returns an exact domain associated with ``self``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ get_exact : Any → Any                                      ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | c4eadd39d3cb611e           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.get_exact","kind":"method","src_hash":"65927e06c1115139","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"get_exact()","rhs":"returns an exact domain associated with ``self``","over":{"base":"Any"},"name":"get_exact_correct"},"guarantee":"returns an exact domain associated with ``self``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"c4eadd39d3cb611e"}
    def get_exact(self):
        """Returns an exact domain associated with ``self``. """
        return QQ_I

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(is_negative(ele), returns ``false`` for any ``complexelement``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ is_negative : Any → Any                                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 76ef16ce0af5449d           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.is_negative","kind":"method","src_hash":"07f6070ffbd04351","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"is_negative(ele)","rhs":"returns ``false`` for any ``complexelement``","over":{"base":"Any"},"name":"is_negative_correct"},"guarantee":"returns ``false`` for any ``complexelement``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"76ef16ce0af5449d"}
    def is_negative(self, element):
        """Returns ``False`` for any ``ComplexElement``. """
        return False

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(is_positive(ele), returns ``false`` for any ``complexelement``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ is_positive : Any → Any                                    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 8080961b51b37bb5           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.is_positive","kind":"method","src_hash":"2dfce4e0ab05cb15","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"is_positive(ele)","rhs":"returns ``false`` for any ``complexelement``","over":{"base":"Any"},"name":"is_positive_correct"},"guarantee":"returns ``false`` for any ``complexelement``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"8080961b51b37bb5"}
    def is_positive(self, element):
        """Returns ``False`` for any ``ComplexElement``. """
        return False

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(is_nonnegative(ele), returns ``false`` for any ``complexelement``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ is_nonnegative : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 50c22d44b05b2370           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.is_nonnegative","kind":"method","src_hash":"042fec5d2a198433","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"is_nonnegative(ele)","rhs":"returns ``false`` for any ``complexelement``","over":{"base":"Any"},"name":"is_nonnegative_correct"},"guarantee":"returns ``false`` for any ``complexelement``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"50c22d44b05b2370"}
    def is_nonnegative(self, element):
        """Returns ``False`` for any ``ComplexElement``. """
        return False

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(is_nonpositive(ele), returns ``false`` for any ``complexelement``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ is_nonpositive : Any → Any                                 ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 28207195ea60cb15           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.is_nonpositive","kind":"method","src_hash":"f800bbe17dfeec57","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"is_nonpositive(ele)","rhs":"returns ``false`` for any ``complexelement``","over":{"base":"Any"},"name":"is_nonpositive_correct"},"guarantee":"returns ``false`` for any ``complexelement``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"28207195ea60cb15"}
    def is_nonpositive(self, element):
        """Returns ``False`` for any ``ComplexElement``. """
        return False

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(gcd(a, ), returns gcd of ``a`` and ``b``) over Any    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ gcd : Any → Any                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | 5912e2163499282a           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.gcd","kind":"method","src_hash":"4269c7c670071b88","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"gcd(a, )","rhs":"returns gcd of ``a`` and ``b``","over":{"base":"Any"},"name":"gcd_correct"},"guarantee":"returns gcd of ``a`` and ``b``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"5912e2163499282a"}
    def gcd(self, a, b):
        """Returns GCD of ``a`` and ``b``. """
        return self.one

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(lcm(a, ), returns lcm of ``a`` and ``b``) over Any    ║
# ╠════════════════════════════════════════════════════════════╣
# ║ lcm : Any → Any                                            ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | b7deb426fad6a57d           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.lcm","kind":"method","src_hash":"50d02a3e32102e41","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"lcm(a, )","rhs":"returns lcm of ``a`` and ``b``","over":{"base":"Any"},"name":"lcm_correct"},"guarantee":"returns lcm of ``a`` and ``b``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"b7deb426fad6a57d"}
    def lcm(self, a, b):
        """Returns LCM of ``a`` and ``b``. """
        return a*b

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(almosteq(a, ), check if ``a`` and ``b`` are almost equal) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ almosteq : Any → Any                                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | d9f3125bad0d5176           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.almosteq","kind":"method","src_hash":"82f6ce6c3d7ba53c","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"almosteq(a, )","rhs":"check if ``a`` and ``b`` are almost equal","over":{"base":"Any"},"name":"almosteq_correct"},"guarantee":"check if ``a`` and ``b`` are almost equal","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"d9f3125bad0d5176"}
    def almosteq(self, a, b, tolerance=None):
        """Check if ``a`` and ``b`` are almost equal. """
        return self._context.almosteq(a, b, tolerance)

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(is_square(a), returns ``true``) over Any              ║
# ╠════════════════════════════════════════════════════════════╣
# ║ is_square : Any → Any                                      ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | d2fb197c98067050           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.is_square","kind":"method","src_hash":"fc7d453c96f05c18","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"is_square(a)","rhs":"returns ``true``","over":{"base":"Any"},"name":"is_square_correct"},"guarantee":"returns ``true``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"d2fb197c98067050"}
    def is_square(self, a):
        """Returns ``True``. Every complex number has a complex square root."""
        return True

# ╔══ CCTT ══════════════════════════════════════════════════╗
# ║ Path(exsqrt(a), returns the principal complex square root of ``a``) over Any ║
# ╠════════════════════════════════════════════════════════════╣
# ║ exsqrt : Any → Any                                         ║
# ╠════════════════════════════════════════════════════════════╣
# ║ Trusted:                                                   ║
# ║   lean.C4.Reduction.ReducesStar.refl                       ║
# ╠════════════════════════════════════════════════════════════╣
# ║ 🟢 KERNEL | refl | Compiled: ✓ | e4df1737edf9cbdf           ║
# ╚════════════════════════════════════════════════════════════╝
# @cctt_verify {"v":2,"sym":"sympy.polys.domains.complexfield.ComplexField.exsqrt","kind":"method","src_hash":"ed2450dd858e1a73","in":{"base":"Any"},"out":{"base":"Any"},"spec":{"lhs":"exsqrt(a)","rhs":"returns the principal complex square root of ``a``","over":{"base":"Any"},"name":"exsqrt_correct"},"guarantee":"returns the principal complex square root of ``a``","fibers":[],"h1":0,"paths":[],"strategy":"refl","details":{},"assumes":[],"trust":["lean.C4.Reduction.ReducesStar.refl"],"compiled":true,"vhash":"e4df1737edf9cbdf"}
    def exsqrt(self, a):
        r"""Returns the principal complex square root of ``a``.

        Explanation
        ===========
        The argument of the principal square root is always within
        $(-\frac{\pi}{2}, \frac{\pi}{2}]$. The square root may be
        slightly inaccurate due to floating point rounding error.
        """
        return a ** 0.5

CC = ComplexField()
