"""Mathlib theorems that could not be translated to OTerm rewrites.

Contains 68993 theorems stored for reference.
"""
from __future__ import annotations

from typing import List, Tuple
from cctt.denotation import OTerm
from cctt.path_search import FiberCtx


AXIOM_NAME = "mathlib_ml_untranslatable"
AXIOM_CATEGORY = "mathlib"
REQUIRES: List[str] = []
COMPOSES_WITH: List[str] = []


def recognizes(term: OTerm) -> bool:
    return False


def relevance_score(term: OTerm, other: OTerm) -> float:
    return 0.0


def apply(term: OTerm, ctx: FiberCtx) -> List[Tuple[OTerm, str]]:
    return []


def apply_inverse(term: OTerm, ctx: FiberCtx) -> List[Tuple[OTerm, str]]:
    return []


TOTAL_UNTRANSLATABLE = 68993

# Sample of untranslatable theorems (first 500):
UNTRANSLATABLE_SAMPLE = [
    ("AddConstMapClass_semiconj", "Semiconj_f_plus_a_plus_b", "Not an equality or iff proposition"),
    ("AddConstMapClass_map_add_nat", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_add_ofNat", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_nat", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_ofNat", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_nat_add", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_ofNat_add", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_sub_nat", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_sub_ofNat", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_add_int", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_sub_int", "_unknown", "Empty proposition"),
    ("AddConstMapClass_map_int_add", "_unknown", "Empty proposition"),
    ("AddConstMapClass_rel_map_of_Icc", "lt_R_f_f", "Not an equality or iff proposition"),
    ("AddConstMap_coe_mk", "mk_f_hf_colon_G_to_plus_c_a_b_H_eq_f", "Not an equality or iff proposition"),
    ("AddConstMap_one_def", "_1_colon_G_to_plus_c_a_a_G_eq_id", "Not an equality or iff proposition"),
    ("AddConstMap_coe_one", "_1_colon_G_to_plus_c_a_a_G_eq_id", "Not an equality or iff proposition"),
    ("AddConstEquiv_toEquiv_injective", "Injective_toEquiv_colon_G_plus_c_a_b_H_to_G_H_pipe_rfl_eq_gt_rfl_in", "Not an equality or iff proposition"),
    ("Submonoid_FG_finite_irreducible_mem_submonoidClosure", "p_in_S_pipe_Irreducible_p_Finite", "Not an equality or iff proposition"),
    ("algebraMap_ofSubsemiring", "algebraMap_S_R_colon_S_to_plus_star_R_eq_S_subtype", "Not an equality or iff proposition"),
    ("coe_algebraMap_ofSubsemiring", "algebraMap_S_R_colon_S_to_R_eq_Subtype_val", "Not an equality or iff proposition"),
    ("algebraMap_ofSubring", "algebraMap_S_R_colon_S_to_plus_star_R_eq_S_subtype", "Not an equality or iff proposition"),
    ("coe_algebraMap_ofSubring", "algebraMap_S_R_colon_S_to_R_eq_Subtype_val", "Not an equality or iff proposition"),
    ("mem_algebraMapSubmonoid_of_mem", "algebraMap_R_S_x_in_algebraMapSubmonoid_S_M", "Not an equality or iff proposition"),
    ("Module_End_algebraMap_isUnit_inv_apply_eq_iff", "_unknown", "Empty proposition"),
    ("FaithfulSMul_algebraMap_injective", "Injective_algebraMap_R_A", "Not an equality or iff proposition"),
    ("IsDomain_of_faithfulSMul", "IsDomain_R", "Not an equality or iff proposition"),
    ("Module_IsTorsionFree_of_faithfulSMul", "IsTorsionFree_S_R", "Not an equality or iff proposition"),
    ("Module_IsTorsionFree_trans_faithfulSMul", "IsTorsionFree_R_M", "Not an equality or iff proposition"),
    ("IsUnit_algebraMap_of_algebraMap", "IsUnit_algebraMap_R_B_r", "Not an equality or iff proposition"),
    ("injective_algebraMap_of_linearMap", "Injective_algebraMap_F_E", "Not an equality or iff proposition"),
    ("surjective_algebraMap_of_linearMap", "Surjective_algebraMap_F_E", "Not an equality or iff proposition"),
    ("bijective_algebraMap_of_linearMap", "Bijective_algebraMap_F_E", "Not an equality or iff proposition"),
    ("bijective_algebraMap_of_linearEquiv", "Bijective_algebraMap_F_E", "Not an equality or iff proposition"),
    ("LinearMap_mul_apply", "_unknown", "Empty proposition"),
    ("LinearMap_mul", "_unknown", "Empty proposition"),
    ("Algebra_lmul_injective", "Function_Injective_Algebra_lmul_R_A", "Not an equality or iff proposition"),
    ("mul", "_unknown", "Empty proposition"),
    ("mul", "_unknown", "Empty proposition"),
    ("NonUnitalAlgHom_comp_mul", "_unknown", "Empty proposition"),
    ("AlgHom_comp_mul", "_unknown", "Empty proposition"),
    ("Algebra_subsingleton", "Subsingleton_A", "Not an equality or iff proposition"),
    ("RingHom_smul_toAlgebra", "_unknown", "Empty proposition"),
    ("RingHom_algebraMap_toAlgebra", "_unknown", "Empty proposition"),
    ("RingHom_smul_toAlgebra", "let", "Not an equality or iff proposition"),
    ("Algebra_algebraMap_eq_smul_one", "_unknown", "Empty proposition"),
    ("Algebra_compHom_smul_def", "letI", "Not an equality or iff proposition"),
    ("Algebra_compHom_algebraMap_eq", "letI", "Not an equality or iff proposition"),
    ("Algebra_compHom_algebraMap_apply", "letI", "Not an equality or iff proposition"),
    ("algebraMap_coe_smul", "_unknown", "Empty proposition"),
    ("algebraMap_smul", "_unknown", "Empty proposition"),
    ("Algebra_isEpi_of_surjective_algebraMap", "Algebra_IsEpi_R_A", "Not an equality or iff proposition"),
    ("injective_lift_lsmul", "Injective_lift_lt_pipe_LinearMap_restrictScalars_1_2_R_R_LinearMap_lsmul_A_M", "Not an equality or iff proposition"),
    ("TensorProduct_lid", "_unknown", "Empty proposition"),
    ("TensorProduct_lid", "_unknown", "Empty proposition"),
    ("AlgEquiv_coe_fun_injective", "at_Function_Injective_A_1_R_A_2_A_1_to_A_2_fun_e_eq_gt_e_colon_A_1_to_A_2", "Not an equality or iff proposition"),
    ("AlgEquiv_coe_toEquiv", "e_colon_A_1_A_2_colon_A_1_to_A_2_eq_e", "Not an equality or iff proposition"),
    ("AlgEquiv_toRingEquiv_toRingHom", "e_colon_A_1_plus_star_A_2_colon_A_1_to_plus_star_A_2_eq_e", "Not an equality or iff proposition"),
    ("AlgEquiv_coe_ringEquiv", "e_colon_A_1_plus_star_A_2_colon_A_1_to_A_2_eq_e", "Not an equality or iff proposition"),
    ("AlgEquiv_coe_ringEquiv", "_unknown", "Empty proposition"),
    ("AlgEquiv_coe_ringEquiv_injective", "Function_Injective_colon_A_1_R_A_2_to_A_1_plus_star_A_2", "Not an equality or iff proposition"),
    ("AlgEquiv_coe_algHom_injective", "Function_Injective_colon_A_1_R_A_2_to_A_1_to_R_A_2", "Not an equality or iff proposition"),
    ("AlgEquiv_toAlgHom_toRingHom", "e_colon_A_1_to_R_A_2_colon_A_1_to_plus_star_A_2_eq_e", "Not an equality or iff proposition"),
    ("bijective", "Function_Bijective_e", "Not an equality or iff proposition"),
    ("injective", "Function_Injective_e", "Not an equality or iff proposition"),
    ("surjective", "Function_Surjective_e", "Not an equality or iff proposition"),
    ("symm_bijective", "Function_Bijective_symm_colon_A_1_R_A_2_to_A_2_R_A_1", "Not an equality or iff proposition"),
    ("mk_coe", "_unknown", "Empty proposition"),
    ("comp_symm", "AlgHom_comp_e_colon_A_1_to_R_A_2_e_symm_eq_AlgHom_id_R_A_2", "Not an equality or iff proposition"),
    ("symm_comp", "AlgHom_comp_e_symm_e_colon_A_1_to_R_A_2_eq_AlgHom_id_R_A_1", "Not an equality or iff proposition"),
    ("leftInverse_symm", "Function_LeftInverse_e_symm_e", "Not an equality or iff proposition"),
    ("rightInverse_symm", "Function_RightInverse_e_symm_e", "Not an equality or iff proposition"),
    ("toRingHom_trans", "e_1_trans_e_2_colon_A_1_to_plus_star_A_3_eq_comp_e_2_e_1_colon_A_1_to_plus_star_A_2", "Not an equality or iff proposition"),
    ("toLinearEquiv_injective", "Function_Injective_toLinearEquiv_colon_to_A_1_R_A_2", "Not an equality or iff proposition"),
    ("toAlgHom_toLinearMap", "e_colon_A_1_to_R_A_2_toLinearMap_eq_e_toLinearMap", "Not an equality or iff proposition"),
    ("toLinearMap_injective", "Function_Injective_toLinearMap_colon_to_A_1_to_R_A_2", "Not an equality or iff proposition"),
    ("coe_ofBijective", "ofBijective_f_hf_colon_A_1_to_A_2_eq_f", "Not an equality or iff proposition"),
    ("MulSemiringAction_toAlgEquiv_injective", "Function_Injective_MulSemiringAction_toAlgEquiv_R_A_colon_G_to_A_R_A", "Not an equality or iff proposition"),
    ("AlgHomClass_toLinearMap_toAlgHom", "AlgHomClass_toAlgHom_f_colon_A_to_R_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_coe", "f_colon_A_to_R_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_mk", "f_h_colon_A_to_R_B_colon_A_to_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_mks", "f_h_1_h_2_h_3_h_4_h_5_colon_A_to_R_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_ringHom_mk", "f_h_colon_A_to_R_B_colon_A_to_plus_star_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_toRingHom", "f_colon_A_to_plus_star_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_toMonoidHom", "f_colon_A_to_star_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_toAddMonoidHom", "f_colon_A_to_plus_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_toRingHom_toMonoidHom", "f_colon_A_to_plus_star_B_colon_A_to_star_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_toRingHom_toAddMonoidHom", "f_colon_A_to_plus_star_B_colon_A_to_plus_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_fn_injective", "at_Function_Injective_A_to_R_B_A_to_B", "Not an equality or iff proposition"),
    ("AlgHom_coe_ringHom_injective", "Function_Injective_colon_A_to_R_B_to_A_to_plus_star_B", "Not an equality or iff proposition"),
    ("AlgHom_coe_monoidHom_injective", "Function_Injective_colon_A_to_R_B_to_A_to_star_B", "Not an equality or iff proposition"),
    ("AlgHom_coe_addMonoidHom_injective", "Function_Injective_colon_A_to_R_B_to_A_to_plus_B", "Not an equality or iff proposition"),
    ("AlgHom_mk_coe", "f_h_1_h_2_h_3_h_4_h_5_colon_A_to_R_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_comp_algebraMap", "phi_colon_A_to_plus_star_B_comp_algebraMap_R_A_eq_algebraMap_R_B", "Not an equality or iff proposition"),
    ("AlgHom_coe_mk", "_unknown", "Empty proposition"),
    ("AlgHom_id_toRingHom", "AlgHom_id_R_A_colon_A_to_plus_star_A_eq_RingHom_id", "Not an equality or iff proposition"),
    ("comp_toRingHom", "phi_1_comp_phi_2_colon_A_to_plus_star_C_eq_phi_1_colon_B_to_plus_star_C_comp_phi_2", "Not an equality or iff proposition"),
    ("toLinearMap_injective", "Function_Injective_toLinearMap_colon_to_A_to_R_B", "Not an equality or iff proposition"),
    ("RingHom_toIntAlgHom_injective", "Function_Injective_RingHom_toIntAlgHom_colon_R_to_plus_star_S_to", "Not an equality or iff proposition"),
    ("algebraMapSubmonoid_le_comap", "algebraMapSubmonoid_A_M_le_algebraMapSubmonoid_B_M_comap_f_toRingHom", "Not an equality or iff proposition"),
    ("MulSemiringAction_toAlgHom_injective", "Function_Injective_MulSemiringAction_toAlgHom_R_A_colon_M_to_A_to_R_A", "Not an equality or iff proposition"),
    ("AlgHom_default_apply", "default_colon_S_to_R_T_x_eq_0", "Not an equality or iff proposition"),
    ("AlgHom_toRingHom_toRatAlgHom", "f_colon_R_to_plus_star_S_toRatAlgHom_eq_f", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_coe", "f_colon_A_to_phi_B_eq_f", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_injective", "at_Function_Injective_A_to_phi_B_A_to_B", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_mk", "f_h_1_h_2_h_3_h_4_colon_A_to_phi_B_eq_f", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_mk_coe", "f_h_1_h_2_h_3_h_4_colon_A_to_phi_B_eq_f", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_to_mulHom", "f_colon_A_to_star_B_eq_f", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_mulHom_mk", "f_h_1_h_2_h_3_h_4_colon_A_to_phi_B_colon_A_to_star_B_eq_f_h_4", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_inverse", "inverse_f_g_h_1_h_2_colon_B_1_to_A_eq_g", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_inverse", "_unknown", "Empty proposition"),
    ("NonUnitalAlgHom_coe_inl", "inl_R_A_B_colon_A_to_A_times_B_eq_fun_x_eq_gt_x_0", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_inr", "inr_R_A_B_colon_B_to_A_times_B_eq_Prod_mk_0", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_restrictScalars", "f_restrictScalars_R_colon_A_to_plus_star_B_eq_f", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_coe_restrictScalars", "_unknown", "Empty proposition"),
    ("NonUnitalAlgHom_restrictScalars_injective", "Function_Injective_restrictScalars_R_colon_A_to_S_B_to_A_to_R_B", "Not an equality or iff proposition"),
    ("NonUnitalSubalgebraClass_subtype_injective", "Function_Injective_subtype_s", "Not an equality or iff proposition"),
    ("NonUnitalSubalgebraClass_coe_subtype", "subtype_s_colon_s_to_A_eq_colon_s_to_A", "Not an equality or iff proposition"),
    ("NonUnitalSubalgebra_toNonUnitalSubsemiring_injective", "toNonUnitalSubsemiring_colon_NonUnitalSubalgebra_R_A_to_NonUnitalSubsemiring_A_Inje", "Not an equality or iff proposition"),
    ("NonUnitalSubalgebra_toSubmodule_injective", "toSubmodule_colon_NonUnitalSubalgebra_R_A_to_Submodule_R_A_Injective", "Not an equality or iff proposition"),
    ("toNonUnitalSubring_injective", "Function_Injective_toNonUnitalSubring_colon_NonUnitalSubalgebra_R_A_to_NonUnitalSubr", "Not an equality or iff proposition"),
    ("map_mono", "S_1_le_S_2_to_map_f_S_1_colon_NonUnitalSubalgebra_R_B_le_map_f_S_2", "Not an equality or iff proposition"),
    ("map_injective", "Function_Injective_map_f_colon_NonUnitalSubalgebra_R_A_to_NonUnitalSubalgebra_R_B", "Not an equality or iff proposition"),
    ("gc_map_comap", "GaloisConnection_map_f_colon_NonUnitalSubalgebra_R_A_to_NonUnitalSubalgebra_R_B_co", "Not an equality or iff proposition"),
    ("Submodule_toNonUnitalSubalgebra_mk", "_unknown", "Empty proposition"),
    ("NonUnitalAlgHom_mem_range_self", "phi_x_in_NonUnitalAlgHom_range_phi_colon_NonUnitalSubalgebra_R_B", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_range_comp_le_range", "NonUnitalAlgHom_range_g_comp_f_le_NonUnitalAlgHom_range_g", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_subset_adjoin", "s_sub_adjoin_R_s", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_mem_adjoin_of_mem", "x_in_adjoin_R_s", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_self_mem_adjoin_singleton", "x_in_adjoin_R_x_colon_Set_A", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_gc", "GaloisConnection_adjoin_R_colon_Set_A_to_NonUnitalSubalgebra_R_A", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_adjoin_le", "adjoin_R_s_le_S", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_adjoin_mono", "adjoin_R_s_le_adjoin_R_t", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_adjoin_induction", "p_x_hx", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_adjoin_induction_2", "p_x_y_hx_hy", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_mem_top", "x_in_top_colon_NonUnitalSubalgebra_R_A", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_mem_sup_left", "forall_x_colon_A_x_in_S_to_x_in_S_T", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_mem_sup_right", "forall_x_colon_A_x_in_T_to_x_in_S_T", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_mul_mem_sup", "x_star_y_in_S_T", "Not an equality or iff proposition"),
    ("NonUnitalSubalgebra_prod_mono", "S_le_T_to_S_1_le_T_1_to_prod_S_S_1_le_prod_T_T_1", "Not an equality or iff proposition"),
    ("inclusion_injective", "Function_Injective_inclusion_h", "Not an equality or iff proposition"),
    ("centralizer_le", "centralizer_R_t_le_centralizer_R_s", "Not an equality or iff proposition"),
    ("NonUnitalAlgebra_adjoin_le_centralizer_centralizer", "adjoin_R_s_le_centralizer_R_centralizer_R_s", "Not an equality or iff proposition"),
    ("SubMulAction_algebraMap_mem", "algebraMap_R_A_r_in_1_colon_SubMulAction_R_A", "Not an equality or iff proposition"),
    ("Submodule_smul_mem_smul", "r_n_in_I_N", "Not an equality or iff proposition"),
    ("Submodule_smul_induction_on", "p_x", "Not an equality or iff proposition"),
    ("Submodule_smul_induction_on", "_unknown", "Empty proposition"),
    ("Submodule_smul_mono", "I_N_le_J_P", "Not an equality or iff proposition"),
    ("Submodule_smul_mono_left", "I_N_le_J_N", "Not an equality or iff proposition"),
    ("Submodule_smul_subset_smul", "I_colon_Set_A_N_colon_Set_M_sub_I_N_colon_Set_M", "Not an equality or iff proposition"),
    ("mul_mem_mul", "m_star_n_in_M_star_N", "Not an equality or iff proposition"),
    ("mul_induction_on", "C_r", "Not an equality or iff proposition"),
    ("mul_induction_on", "_unknown", "Empty proposition"),
    ("mul_subset_mul", "M_colon_Set_A_star_N_colon_Set_A_sub_M_star_N_colon_Set_A", "Not an equality or iff proposition"),
    ("pow_succ", "_unknown", "Empty proposition"),
    ("le_pow_toAddSubmonoid", "M_toAddSubmonoid_pow_n_le_M_pow_n_toAddSubmonoid", "Not an equality or iff proposition"),
    ("pow_subset_pow", "M_colon_Set_A_pow_n_sub_M_pow_n_colon_Submodule_R_A", "Not an equality or iff proposition"),
    ("pow_mem_pow", "x_pow_n_in_M_pow_n", "Not an equality or iff proposition"),
    ("algebraMap_mem", "algebraMap_R_A_r_in_1_colon_Submodule_R_A", "Not an equality or iff proposition"),
    ("map_op_one", "map_opLinearEquiv_R_colon_A_R_A_colon_A_to_R_A_1_colon_Submodule_R_A_eq_1", "Not an equality or iff proposition"),
    ("comap_op_one", "comap_opLinearEquiv_R_colon_A_R_A_colon_A_to_R_A_1_colon_Submodule_R_A", "Not an equality or iff proposition"),
    ("map_unop_one", "map_opLinearEquiv_R_colon_A_R_A_symm_colon_A_to_R_A_1_colon_Submodule_R_A", "Not an equality or iff proposition"),
    ("comap_unop_one", "comap_opLinearEquiv_R_colon_A_R_A_symm_colon_A_to_R_A_1_colon_Submodule_R_A", "Not an equality or iff proposition"),
    ("map_op_mul", "map_opLinearEquiv_R_colon_A_R_A_colon_A_to_R_A_M_star_N_eq_map_op", "Not an equality or iff proposition"),
    ("comap_unop_mul", "comap_opLinearEquiv_R_colon_A_R_A_symm_colon_A_to_R_A_M_star_N_eq_co", "Not an equality or iff proposition"),
    ("map_unop_mul", "map_opLinearEquiv_R_colon_A_R_A_symm_colon_A_to_R_A_M_star_N_eq_map", "Not an equality or iff proposition"),
    ("comap_op_mul", "comap_opLinearEquiv_R_colon_A_R_A_colon_A_to_R_A_M_star_N_eq_comap", "Not an equality or iff proposition"),
    ("mem_span_mul_finite_of_mem_span_mul", "exists_T_T_prime_colon_Finset_A_T_sub_S_and_T_prime_sub_S_prime_and_x_in_span_R_T_star_T_prime_colon_Set_A", "Not an equality or iff proposition"),
    ("mem_span_mul_finite_of_mem_mul", "exists_T_T_prime_colon_Finset_A_T_colon_Set_A_sub_P_and_T_prime_colon_Set_A_sub_Q_and_x_in_span_R_T_star_T_prime_colon_Set", "Not an equality or iff proposition"),
    ("pow_induction_on_left", "_unknown", "Empty proposition"),
    ("pow_induction_on_left", "C_x", "Not an equality or iff proposition"),
    ("comap_unop_pow", "comap_opLinearEquiv_R_colon_A_R_A_symm_colon_A_to_R_A_M_pow_n_eq_co", "Not an equality or iff proposition"),
    ("comap_op_pow", "comap_opLinearEquiv_R_colon_A_R_A_colon_A_to_R_A_M_pow_n_eq_comap", "Not an equality or iff proposition"),
    ("map_op_pow", "map_opLinearEquiv_R_colon_A_R_A_colon_A_to_R_A_M_pow_n_eq_map_op", "Not an equality or iff proposition"),
    ("map_unop_pow", "map_opLinearEquiv_R_colon_A_R_A_symm_colon_A_to_R_A_M_pow_n_eq_map", "Not an equality or iff proposition"),
    ("mul_mem_mul_rev", "n_star_m_in_M_star_N", "Not an equality or iff proposition"),
    ("smul_le_smul", "s_M_le_t_N", "Not an equality or iff proposition"),
    ("AlgHom_toRingHom_fromOpposite", "f_fromOpposite_hf_colon_A_to_plus_star_B_eq_f_colon_A_to_plus_star_B_fromOpposite_hf", "Not an equality or iff proposition"),
    ("AlgHom_toRingHom_toOpposite", "f_toOpposite_hf_colon_A_to_plus_star_B_eq_f_colon_A_to_plus_star_B_toOpposite_hf", "Not an equality or iff proposition"),
    ("AlgEquiv_piCongrLeft", "_unknown", "Empty proposition"),
    ("AlgEquiv_piCongrLeft", "_unknown", "Empty proposition"),
    ("IsScalarTower_restrictScalars", "letI", "Not an equality or iff proposition"),
    ("spectrum_subset_singleton_zero_compl", "spectrum_R_a_sub_0", "Not an equality or iff proposition"),
    ("spectrum_mem_resolventSet_of_left_right_inverse", "r_in_resolventSet_R_a", "Not an equality or iff proposition"),
    ("spectrum_inv_mem_resolventSet", "rinv_colon_R_in_resolventSet_R_ainv_colon_A", "Not an equality or iff proposition"),
    ("subset_subalgebra", "spectrum_R_a_colon_A_sub_spectrum_R_a", "Not an equality or iff proposition"),
    ("AlgHom_mem_resolventSet_apply", "r_in_resolventSet_R_phi_colon_A_to_B_a", "Not an equality or iff proposition"),
    ("AlgHom_spectrum_apply_subset", "sig_phi_colon_A_to_B_a_sub_sig_a", "Not an equality or iff proposition"),
    ("apply_mem_spectrum", "phi_a_in_sig_a", "Not an equality or iff proposition"),
    ("spectrum_units_conjugate", "_unknown", "Empty proposition"),
    ("isQuasiregular_iff", "_unknown", "Empty proposition"),
    ("IsQuasiregular_map", "IsQuasiregular_f_x", "Not an equality or iff proposition"),
    ("isQuasiregular_iff_isUnit", "_unknown", "Empty proposition"),
    ("quasispectrum_not_isUnit_mem", "r_in_quasispectrum_R_a", "Not an equality or iff proposition"),
    ("quasispectrum_nonempty", "quasispectrum_R_a_Nonempty", "Not an equality or iff proposition"),
    ("NonUnitalAlgHom_quasispectrum_apply_subset", "_unknown", "Empty proposition"),
    ("NonUnitalAlgHom_quasispectrum_apply_subset", "quasispectrum_R_phi_a_sub_quasispectrum_R_a", "Not an equality or iff proposition"),
    ("quasispectrum_mem_of_not_quasiregular", "r_colon_R_in_quasispectrum_R_a", "Not an equality or iff proposition"),
    ("spectrum_subset_quasispectrum", "spectrum_R_a_sub_quasispectrum_R_a", "Not an equality or iff proposition"),
    ("Unitization_mem_spectrum_inr_of_not_isUnit", "r_in_spectrum_R_a_colon_Unitization_R_A", "Not an equality or iff proposition"),
    ("Unitization_quasispectrum_eq_spectrum_inr", "_unknown", "Empty proposition"),
    ("NonnegSpectrumClass_nonneg_of_mem_quasispectrum", "_0_le_x", "Not an equality or iff proposition"),
    ("spectrum_nonneg_of_nonneg", "_unknown", "Empty proposition"),
    ("QuasispectrumRestricts_of_subset_range_algebraMap", "QuasispectrumRestricts_a_f", "Not an equality or iff proposition"),
    ("QuasispectrumRestricts_of_quasispectrum_eq", "QuasispectrumRestricts_b_f", "Not an equality or iff proposition"),
    ("QuasispectrumRestricts_apply_mem", "f_s_in_quasispectrum_R_a", "Not an equality or iff proposition"),
    ("QuasispectrumRestricts_subset_preimage", "quasispectrum_S_a_sub_f_inv_prime_quasispectrum_R_a", "Not an equality or iff proposition"),
    ("QuasispectrumRestricts_comp", "QuasispectrumRestricts_a_e", "Not an equality or iff proposition"),
    ("SpectrumRestricts_rightInvOn", "spectrum_S_a_RightInvOn_f_algebraMap_R_S", "Not an equality or iff proposition"),
    ("SpectrumRestricts_of_rightInvOn", "SpectrumRestricts_a_f", "Not an equality or iff proposition"),
    ("SpectrumRestricts_of_subset_range_algebraMap", "SpectrumRestricts_a_f", "Not an equality or iff proposition"),
    ("SpectrumRestricts_of_spectrum_eq", "SpectrumRestricts_b_f", "Not an equality or iff proposition"),
    ("SpectrumRestricts_apply_mem", "f_s_in_spectrum_R_a", "Not an equality or iff proposition"),
    ("SpectrumRestricts_subset_preimage", "spectrum_S_a_sub_f_inv_prime_spectrum_R_a", "Not an equality or iff proposition"),
    ("quasispectrumRestricts_iff_spectrumRestricts_inr", "_unknown", "Empty proposition"),
    ("IsStrictlyPositive_nonneg", "_0_le_a", "Not an equality or iff proposition"),
    ("IsStrictlyPositive_isUnit", "IsUnit_a", "Not an equality or iff proposition"),
    ("IsUnit_isStrictlyPositive", "IsStrictlyPositive_a", "Not an equality or iff proposition"),
    ("IsStrictlyPositive_isSelfAdjoint", "IsSelfAdjoint_a", "Not an equality or iff proposition"),
    ("Units_isStrictlyPositive_of_le", "IsStrictlyPositive_a_colon_A", "Not an equality or iff proposition"),
    ("IsStrictlyPositive_of_subsingleton", "IsStrictlyPositive_a", "Not an equality or iff proposition"),
    ("conjugate_of_isUnit_of_isSelfAdjoint", "IsStrictlyPositive_b_star_a_star_b", "Not an equality or iff proposition"),
    ("smul", "IsStrictlyPositive_c_a", "Not an equality or iff proposition"),
    ("isStrictlyPositive_algebraMap", "IsStrictlyPositive_algebraMap_A_c", "Not an equality or iff proposition"),
    ("spectrum_pos", "_0_lt_x", "Not an equality or iff proposition"),
    ("Subalgebra_toSubsemiring_injective", "Function_Injective_toSubsemiring_colon_Subalgebra_R_A_to_Subsemiring_A", "Not an equality or iff proposition"),
    ("algebraMap_mem", "algebraMap_R_A_r_in_s", "Not an equality or iff proposition"),
    ("Subalgebra_algebraMap_mem", "algebraMap_R_A_r_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_rangeS_le", "algebraMap_R_A_rangeS_le_S_toSubsemiring", "Not an equality or iff proposition"),
    ("Subalgebra_range_subset", "Set_range_algebraMap_R_A_sub_S", "Not an equality or iff proposition"),
    ("Subalgebra_range_le", "Set_range_algebraMap_R_A_le_S", "Not an equality or iff proposition"),
    ("Subalgebra_smul_mem", "r_x_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_mul_mem", "x_star_y_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_pow_mem", "x_pow_n_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_add_mem", "x_plus_y_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_nsmul_mem", "n_x_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_natCast_mem", "n_colon_A_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_list_prod_mem", "L_prod_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_list_sum_mem", "L_sum_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_multiset_sum_mem", "m_sum_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_sum_mem", "x_in_t_f_x_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_multiset_prod_mem", "m_prod_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_prod_mem", "x_in_t_f_x_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_toNonUnitalSubalgebra_injective", "Function_Injective_toNonUnitalSubalgebra_colon_Subalgebra_R_A_to_NonUnitalSubalg", "Not an equality or iff proposition"),
    ("Subalgebra_neg_mem", "minus_x_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_sub_mem", "x_minus_y_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_zsmul_mem", "n_x_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_intCast_mem", "n_colon_A_in_S", "Not an equality or iff proposition"),
    ("Subalgebra_toSubring_injective", "Function_Injective_toSubring_colon_Subalgebra_R_A_to_Subring_A", "Not an equality or iff proposition"),
    ("Subalgebra_toSubmodule_injective", "Function_Injective_toSubmodule_colon_Subalgebra_R_A_to_Submodule_R_A", "Not an equality or iff proposition"),
    ("coe_val", "S_val_colon_S_to_A_eq_colon_S_to_A", "Not an equality or iff proposition"),
    ("map_mono", "S_1_le_S_2_to_S_1_map_f_le_S_2_map_f", "Not an equality or iff proposition"),
    ("map_injective", "Function_Injective_map_f", "Not an equality or iff proposition"),
    ("gc_map_comap", "GaloisConnection_map_f_comap_f", "Not an equality or iff proposition"),
    ("SubalgebraClass_coe_val", "val_s_colon_s_to_A_eq_colon_s_to_A", "Not an equality or iff proposition"),
    ("AlgHom_mem_range_self", "phi_x_in_phi_range", "Not an equality or iff proposition"),
    ("AlgHom_range_comp_le_range", "g_comp_f_range_le_g_range", "Not an equality or iff proposition"),
    ("AlgHom_rangeRestrict_surjective", "Function_Surjective_f_rangeRestrict", "Not an equality or iff proposition"),
    ("Subalgebra_inclusion_injective", "Function_Injective_inclusion_h", "Not an equality or iff proposition"),
    ("AlgHom_subalgebraMap_surjective", "Function_Surjective_f_subalgebraMap_S", "Not an equality or iff proposition"),
    ("center_le_centralizer", "center_R_A_le_centralizer_R_s", "Not an equality or iff proposition"),
    ("centralizer_le", "centralizer_R_t_le_centralizer_R_s", "Not an equality or iff proposition"),
    ("le_centralizer_centralizer", "s_le_centralizer_R_centralizer_R_s_colon_Set_A", "Not an equality or iff proposition"),
    ("centralizer_coe_range_includeLeft_eq_center_tensorProduct", "Subalgebra_centralizer_R_Algebra_TensorProduct_includeLeft_colon_A_to_R_A", "Not an equality or iff proposition"),
    ("centralizer_range_includeRight_eq_center_tensorProduct", "Subalgebra_centralizer_R_Algebra_TensorProduct_includeRight_colon_B_to_R_A", "Not an equality or iff proposition"),
    ("Subalgebra_isSimpleOrder_of_finrank_prime", "IsSimpleOrder_Subalgebra_F_A", "Not an equality or iff proposition"),
    ("Algebra_gc", "GaloisConnection_adjoin_R_colon_Set_A_to_Subalgebra_R_A", "Not an equality or iff proposition"),
    ("Algebra_mem_top", "x_in_top_colon_Subalgebra_R_A", "Not an equality or iff proposition"),
    ("Algebra_mem_sup_left", "forall_x_colon_A_x_in_S_to_x_in_S_T", "Not an equality or iff proposition"),
    ("Algebra_mem_sup_right", "forall_x_colon_A_x_in_T_to_x_in_S_T", "Not an equality or iff proposition"),
    ("Algebra_mul_mem_sup", "x_star_y_in_S_T", "Not an equality or iff proposition"),
    ("Algebra_mem_iSup_of_mem", "x_in_iSup_S", "Not an equality or iff proposition"),
    ("Algebra_iSup_induction", "motive_x", "Not an equality or iff proposition"),
    ("Algebra_iSup_induction", "_unknown", "Empty proposition"),
    ("AlgHom_eqOn_sup", "Set_EqOn_phi_psi_S_T", "Not an equality or iff proposition"),
    ("Subalgebra_le_saturation", "s_le_s_saturation_M_H", "Not an equality or iff proposition"),
    ("Subalgebra_mem_saturation_of_mul_mem_left", "y_in_s_saturation_M_H", "Not an equality or iff proposition"),
    ("Subalgebra_mem_saturation_of_mul_mem_right", "x_in_s_saturation_M_H", "Not an equality or iff proposition"),
    ("Algebra_subset_adjoin", "s_sub_adjoin_R_s", "Not an equality or iff proposition"),
    ("Algebra_mem_adjoin_of_mem", "x_in_adjoin_R_s", "Not an equality or iff proposition"),
    ("Algebra_adjoin_le", "adjoin_R_s_le_S", "Not an equality or iff proposition"),
    ("Algebra_adjoin_singleton_le", "R_a_le_S", "Not an equality or iff proposition"),
    ("Algebra_adjoin_mono", "adjoin_R_s_le_adjoin_R_t", "Not an equality or iff proposition"),
    ("Algebra_adjoin_induction", "p_x_hx", "Not an equality or iff proposition"),
    ("Algebra_adjoin_induction_2", "p_x_y_hx_hy", "Not an equality or iff proposition"),
    ("Algebra_adjoin_adjoin_coe_preimage", "adjoin_R_colon_adjoin_R_s_to_A_inv_prime_s_eq_top", "Not an equality or iff proposition"),
    ("Algebra_span_le_adjoin", "span_R_s_le_Subalgebra_toSubmodule_adjoin_R_s", "Not an equality or iff proposition"),
    ("Algebra_mem_adjoin_of_map_mul", "f_x_in_adjoin_R_f_prime_prime_s_union_1", "Not an equality or iff proposition"),
    ("Algebra_adjoin_le_centralizer_centralizer", "adjoin_R_s_le_Subalgebra_centralizer_R_Subalgebra_centralizer_R_s", "Not an equality or iff proposition"),
    ("Algebra_self_mem_adjoin_singleton", "x_in_R_x", "Not an equality or iff proposition"),
    ("AlgHom_adjoin_le_equalizer", "adjoin_R_s_le_equalizer_phi_1_phi_2", "Not an equality or iff proposition"),
    ("AlgHom_ext_of_adjoin_eq_top", "_unknown", "Empty proposition"),
    ("AlgHom_adjoin_ext", "_unknown", "Empty proposition"),
    ("AlgHom_ext_of_eq_adjoin", "_unknown", "Empty proposition"),
    ("NonUnitalAlgebra_adjoin_le_algebra_adjoin", "adjoin_R_s_le_Algebra_adjoin_R_s_toNonUnitalSubalgebra", "Not an equality or iff proposition"),
    ("Subalgebra_mem_of_span_eq_top_of_smul_pow_mem", "x_in_S_prime", "Not an equality or iff proposition"),
    ("Subalgebra_pi_mono", "pi_s_t_1_le_pi_s_t_2", "Not an equality or iff proposition"),
    ("Subalgebra_mul_toSubmodule_le", "Subalgebra_toSubmodule_S_star_Subalgebra_toSubmodule_T_le_Subalgebra_toSubmodule_S", "Not an equality or iff proposition"),
    ("Subalgebra_isIdempotentElem_toSubmodule", "IsIdempotentElem_S_toSubmodule", "Not an equality or iff proposition"),
    ("Subalgebra_smul_mem_pointwise_smul", "r_in_S_to_m_r_in_m_S", "Not an equality or iff proposition"),
    ("Subalgebra_prod_mono", "S_le_T_to_S_1_le_T_1_to_prod_S_S_1_le_prod_T_T_1", "Not an equality or iff proposition"),
    ("Subalgebra_finrank_left_dvd_finrank_sup_of_free", "finrank_R_A_finrank_R_A_B", "Not an equality or iff proposition"),
    ("finrank_right_dvd_finrank_sup_of_free", "finrank_R_B_finrank_R_A_B", "Not an equality or iff proposition"),
    ("Subalgebra_restrictScalars_injective", "Function_Injective_restrictScalars_R_colon_Subalgebra_S_A_to_Subalgebra_R_A", "Not an equality or iff proposition"),
    ("range_isScalarTower_toAlgHom", "LinearMap_range_IsScalarTower_toAlgHom_R_S_A_colon_S_to_R_A_eq_Subalgebra_toSubmod", "Not an equality or iff proposition"),
    ("AlgHomClass_unitization_injective", "_unknown", "Empty proposition"),
    ("AlgHomClass_unitization_injective", "Function_Injective_f", "Not an equality or iff proposition"),
    ("unitization_injective", "Function_Injective_unitization_s", "Not an equality or iff proposition"),
    ("unitization_injective", "Function_Injective_unitization_s", "Not an equality or iff proposition"),
    ("Algebra_lsmul_coe", "lsmul_R_B_M_a_colon_M_to_M_eq_a", "Not an equality or iff proposition"),
    ("IsScalarTower_of_algebraMap_smul", "IsScalarTower_R_A_M", "Not an equality or iff proposition"),
    ("IsScalarTower_of_compHom", "letI", "Not an equality or iff proposition"),
    ("of_algebraMap_eq", "IsScalarTower_R_S_A", "Not an equality or iff proposition"),
    ("of_algebraMap_eq", "_unknown", "Empty proposition"),
    ("coe_toAlgHom", "_unknown", "Empty proposition"),
    ("AlgHom_comp_algebraMap_of_tower", "f_colon_A_to_plus_star_B_comp_algebraMap_R_A_eq_algebraMap_R_B", "Not an equality or iff proposition"),
    ("AlgHom_coe_restrictScalars", "f_restrictScalars_R_colon_A_to_plus_star_B_eq_f", "Not an equality or iff proposition"),
    ("AlgHom_coe_restrictScalars", "_unknown", "Empty proposition"),
    ("AlgHom_restrictScalars_injective", "Function_Injective_restrictScalars_R_colon_A_to_S_B_to_A_to_R_B", "Not an equality or iff proposition"),
    ("AlgEquiv_coe_restrictScalars", "_unknown", "Empty proposition"),
    ("AlgEquiv_restrictScalars_injective", "Function_Injective_restrictScalars_R_colon_A_S_B_to_A_R_B", "Not an equality or iff proposition"),
    ("AlgEquiv_coe_restrictScalars_symm", "_unknown", "Empty proposition"),
    ("Submodule_smul_mem_span_smul_of_mem", "k_x_in_span_R_s_t", "Not an equality or iff proposition"),
    ("Submodule_smul_mem_span_smul", "_unknown", "Empty proposition"),
    ("Submodule_smul_mem_span_smul", "k_x_in_span_R_s_t", "Not an equality or iff proposition"),
    ("map_mem_span_algebraMap_image", "algebraMap_S_T_x_in_Submodule_span_R_algebraMap_S_T_prime_prime_a", "Not an equality or iff proposition"),
    ("Algebra_lsmul_injective", "Function_Injective_lsmul_R_B_M_x", "Not an equality or iff proposition"),
    ("Unitization_toProd_injective", "toProd_colon_Unitization_R_A_to_R_times_A_Injective", "Not an equality or iff proposition"),
    ("Unitization_toProd_surjective", "toProd_colon_Unitization_R_A_to_R_times_A_Surjective", "Not an equality or iff proposition"),
    ("Unitization_toProd_bijective", "toProd_colon_Unitization_R_A_to_R_times_A_Bijective", "Not an equality or iff proposition"),
    ("Unitization_mk_injective", "mk_colon_R_times_A_to_Unitization_R_A_Injective", "Not an equality or iff proposition"),
    ("Unitization_mk_surjective", "mk_colon_R_times_A_to_Unitization_R_A_Surjective", "Not an equality or iff proposition"),
    ("Unitization_mk_bijective", "mk_colon_R_times_A_to_Unitization_R_A_Bijective", "Not an equality or iff proposition"),
    ("inl_injective", "Function_Injective_inl_colon_R_to_Unitization_R_A", "Not an equality or iff proposition"),
    ("inr_injective", "Function_Injective_colon_A_to_Unitization_R_A", "Not an equality or iff proposition"),
    ("ind", "P_x", "Not an equality or iff proposition"),
    ("linearMap_ext", "_unknown", "Empty proposition"),
    ("algHom_ext", "_unknown", "Empty proposition"),
    ("algHom_ext", "_unknown", "Empty proposition"),
    ("starMap_injective", "Function_Injective_starMap_phi", "Not an equality or iff proposition"),
    ("starMap_surjective", "Function_Surjective_starMap_phi", "Not an equality or iff proposition"),
    ("IsSelfAdjoint_inr", "IsSelfAdjoint_a_colon_Unitization_R_A", "Not an equality or iff proposition"),
    ("Algebraic_infinite_of_charZero", "x_colon_A_pipe_IsAlgebraic_R_x_Infinite", "Not an equality or iff proposition"),
    ("Algebraic_aleph0_le_cardinalMk_of_charZero", "_0_le_hash_x_colon_A_slash_slash_IsAlgebraic_R_x", "Not an equality or iff proposition"),
    ("Algebraic_cardinalMk_lift_le_mul", "Cardinal_lift_u_hash_x_colon_A_slash_slash_IsAlgebraic_R_x_le_Cardinal_lift_v_hash_R_X_star_0", "Not an equality or iff proposition"),
    ("Algebraic_cardinalMk_lift_le_max", "Cardinal_lift_u_hash_x_colon_A_slash_slash_IsAlgebraic_R_x_le_max_Cardinal_lift_v_hash_R_0", "Not an equality or iff proposition"),
    ("Algebraic_countable", "Set_Countable_x_colon_A_pipe_IsAlgebraic_R_x", "Not an equality or iff proposition"),
    ("MonoidHom_map_finprod_mem", "_unknown", "Empty proposition"),
    ("MonoidHom_functions_ext", "_unknown", "Empty proposition"),
    ("Algebra_FiniteType_exists_fgAlgCatSkeleton", "exists_P_colon_FGAlgCatSkeleton_R_Nonempty_A_R_P_eval_obj", "Not an equality or iff proposition"),
    ("AddCommGrpCat_asHom_injective", "Function_Injective_at_asHom_G", "Not an equality or iff proposition"),
    ("AddCommGrpCat_injective_of_mono", "Function_Injective_f", "Not an equality or iff proposition"),
    ("Module_Baer_of_divisible", "Module_Baer_A", "Not an equality or iff proposition"),
    ("ModuleCat_isSeparator", "IsSeparator_ModuleCat_of_v_R_Shrink_v_R", "Not an equality or iff proposition"),
    ("ModuleCat_isScalarTower_of_algebra_moduleCat", "IsScalarTower_k_A_M", "Not an equality or iff proposition"),
    ("ModuleCat_hom_bijective", "Function_Bijective_Hom_hom_colon_M_N_to_M_to_R_N", "Not an equality or iff proposition"),
    ("ModuleCat_hom_injective", "Function_Injective_Hom_hom_colon_M_N_to_M_to_R_N", "Not an equality or iff proposition"),
    ("ModuleCat_hom_surjective", "Function_Surjective_Hom_hom_colon_M_N_to_M_to_R_N", "Not an equality or iff proposition"),
    ("ModuleCat_subsingleton_of_isZero", "Subsingleton_M", "Not an equality or iff proposition"),
    ("ModuleCat_restrictScalars_smul_def", "_unknown", "Empty proposition"),
    ("ModuleCat_restrictScalarsId", "_unknown", "Empty proposition"),
    ("ModuleCat_restrictScalarsId", "_unknown", "Empty proposition"),
    ("ModuleCat_restrictScalarsId", "_unknown", "Empty proposition"),
    ("ModuleCat_restrictScalarsId", "_unknown", "Empty proposition"),
    ("ModuleCat_preservesFiniteLimits_tensorLeft_of_ringHomFlat", "PreservesFiniteLimits_lt_pipe_tensorLeft_restrictScalars_f_obj_ModuleCat_of_B_B", "Not an equality or iff proposition"),
    ("ModuleCat_preservesFiniteLimits_extendScalars_of_flat", "PreservesFiniteLimits_extendScalars_u_f", "Not an equality or iff proposition"),
    ("ModuleCat_reflectsIsomorphisms_extendScalars_of_faithfullyFlat", "extendScalars_u_f_ReflectsIsomorphisms", "Not an equality or iff proposition"),
    ("ModuleCat_enoughInjectives", "EnoughInjectives_ModuleCat_max_v_u_R", "Not an equality or iff proposition"),
    ("ModuleCat_shortExact_projectiveShortComplex", "M_projectiveShortComplex_ShortExact", "Not an equality or iff proposition"),
    ("ModuleCat_FilteredColimits_colimit_add_mk_eq", "_unknown", "Empty proposition"),
    ("ModuleCat_disjoint_span_sum", "Disjoint_span_R_range_u_comp_Sum_inl_span_R_range_u_comp_Sum_inr", "Not an equality or iff proposition"),
    ("ModuleCat_linearIndependent_leftExact", "LinearIndependent_R_u", "Not an equality or iff proposition"),
    ("Module_injective_object_of_injective_module", "CategoryTheory_Injective_ModuleCat_of_R_M", "Not an equality or iff proposition"),
    ("Module_injective_module_of_injective_object", "Module_Injective_R_M", "Not an equality or iff proposition"),
    ("ModuleCat_hasLimitsOfShape", "HasLimitsOfShape_J_ModuleCat_w_R", "Not an equality or iff proposition"),
    ("ModuleCat_hasLimitsOfSize", "HasLimitsOfSize_t_v_ModuleCat_w_R", "Not an equality or iff proposition"),
    ("ModuleCat_localizedModuleFunctor_map_exact", "T_map_ModuleCat_localizedModuleFunctor_S_Exact", "Not an equality or iff proposition"),
    ("ModuleCat_extendsScalars_map_leftUnitor_inv_one_tmul", "letI", "Not an equality or iff proposition"),
    ("ModuleCat_extendsScalars_map_rightUnitor_inv_one_tmul", "letI", "Not an equality or iff proposition"),
    ("ModuleCat_extendScalars_e", "letI", "Not an equality or iff proposition"),
    ("ModuleCat_extendScalars_eta", "letI", "Not an equality or iff proposition"),
    ("ModuleCat_extendScalars_mu", "letI", "Not an equality or iff proposition"),
    ("ModuleCat_extendScalars_d", "letI", "Not an equality or iff proposition"),
    ("ModuleCat_extendScalars_d_tmul", "letI", "Not an equality or iff proposition"),
    ("ModuleCat_tensor_ext_3", "_unknown", "Empty proposition"),
    ("PresheafOfModules_ModuleColimit_jointly_surjective_3", "_unknown", "Empty proposition"),
    ("PresheafOfModules_ModuleColimit_homEquiv", "_unknown", "Empty proposition"),
    ("PresheafOfModules_ModuleColimit_homEquiv", "_unknown", "Empty proposition"),
    ("PresheafOfModules_ModuleColimit_map_smul_homEquiv", "_unknown", "Empty proposition"),
    ("ModuleCat_piIsoPi_hom_ker_subtype", "piIsoPi_Z_hom_ofHom_LinearMap_proj_i_colon_forall_i_colon_i_Z_i_to_R_Z_i_eq_Pi_pi_Z_i", "Not an equality or iff proposition"),
    ("ModuleCat_projective_of_free", "Projective_M", "Not an equality or iff proposition"),
    ("ModuleCat_hasProjectiveDimensionLE_of_semiLinearEquiv", "HasProjectiveDimensionLE_N_n", "Not an equality or iff proposition"),
    ("ModuleCat_uliftFunctor_map_exact", "S_map_uliftFunctor_R_Exact", "Not an equality or iff proposition"),
    ("CommRingCat_isPushout_tensorProduct", "IsPushout_ofHom_lt_pipe_algebraMap_R_A_ofHom_lt_pipe_algebraMap_R_B_ofHom_S_colon_eq", "Not an equality or iff proposition"),
    ("CommRingCat_isPushout_of_isPushout", "IsPushout_ofHom_algebraMap_R_S_ofHom_algebraMap_R_A_ofHom_algebr", "Not an equality or iff proposition"),
    ("CommRingCat_isPushout_of_isLocalization", "IsPushout_CommRingCat_ofHom_f_CommRingCat_ofHom_algebraMap_R_R_Com", "Not an equality or iff proposition"),
    ("RingHom_surjective_of_epi_of_finite", "Function_Surjective_f", "Not an equality or iff proposition"),
    ("CommRingCat_FilteredColimits_nontrivial", "Nontrivial_c_pt", "Not an equality or iff proposition"),
    ("CommRingCat_preservesFilteredColimits_coyoneda", "PreservesFilteredColimits_coyoneda_obj_op_S", "Not an equality or iff proposition"),
    ("Algebra_IsCentral_baseField_essentially_unique", "Function_Bijective_algebraMap_k_K", "Not an equality or iff proposition"),
    ("Algebra_IsCentral_of_algEquiv", "IsCentral_K_D_prime", "Not an equality or iff proposition"),
    ("Algebra_TensorProduct_includeLeft_map_center_le", "Subalgebra_center_K_B_map_includeLeft_le_Subalgebra_center_K_B_K_C", "Not an equality or iff proposition"),
    ("Algebra_TensorProduct_includeRight_map_center_le", "Subalgebra_center_K_C_map_includeRight_le_Subalgebra_center_K_B_K_C", "Not an equality or iff proposition"),
    ("Algebra_IsCentral_left_of_tensor", "IsCentral_K_B", "Not an equality or iff proposition"),
    ("Algebra_IsCentral_right_of_tensor", "IsCentral_K_C", "Not an equality or iff proposition"),
    ("Algebra_IsCentral_left_of_tensor_of_field", "IsCentral_K_B", "Not an equality or iff proposition"),
    ("Algebra_IsCentral_right_of_tensor_of_field", "IsCentral_K_C", "Not an equality or iff proposition"),
    ("RingHom_charP", "CharP_R_p", "Not an equality or iff proposition"),
    ("RingHom_expChar", "ExpChar_R_p", "Not an equality or iff proposition"),
    ("Module_charP_end", "CharP_M_to_R_M_p", "Not an equality or iff proposition"),
    ("Ideal_natCast_mem_of_charP_quotient", "p_colon_R_in_I", "Not an equality or iff proposition"),
    ("Module_DirectLimit_induction_on", "C_z", "Not an equality or iff proposition"),
    ("Module_DirectLimit_lift_of", "_unknown", "Empty proposition"),
    ("Module_DirectLimit_lift_injective", "Function_Injective_lift_R_i_G_f_g_Hg", "Not an equality or iff proposition"),
    ("Module_DirectLimit_map_comp", "map_g_2_hg_2_comp_map_g_1_hg_1_colon_DirectLimit_G_f_to_R_DirectLimit_G_prime_prime_f_prime_prime_eq", "Not an equality or iff proposition"),
    ("AddCommGroup_DirectLimit_lift_injective", "Function_Injective_lift_G_f_P_g_Hg", "Not an equality or iff proposition"),
    ("AddCommGroup_DirectLimit_map_comp", "map_g_2_hg_2_comp_map_g_1_hg_1_colon_DirectLimit_G_f_to_plus_DirectLimit_G_prime_prime_f_prime_prime", "Not an equality or iff proposition"),
    ("Ring_DirectLimit_induction_on", "C_z", "Not an equality or iff proposition"),
    ("Ring_DirectLimit_lift_of", "_unknown", "Empty proposition"),
    ("Ring_DirectLimit_lift_injective", "Function_Injective_lift_G_f_P_g_Hg", "Not an equality or iff proposition"),
    ("Ring_of_injective", "Function_Injective_of_G_fun_i_j_h_f_prime_i_j_h_i", "Not an equality or iff proposition"),
    ("Ring_map_comp", "map_g_2_hg_2_comp_map_g_1_hg_1_colon_DirectLimit_G_fun_h_f_h_to_plus_star", "Not an equality or iff proposition"),
    ("AddChar_directSum_injective", "Injective_directSum_colon_forall_i_AddChar_G_i_R_to_AddChar_i_G_i_R", "Not an equality or iff proposition"),
    ("LinearMap_toMatrix_directSum_collectedBasis_eq_blockDiagonal", "_unknown", "Empty proposition"),
    ("LinearMap_trace_eq_sum_trace_restrict", "_unknown", "Empty proposition"),
    ("LinearMap_mapsTo_biSup_of_mapsTo", "MapsTo_f_i_in_s_N_i_i_in_s_N_i", "Not an equality or iff proposition"),
    ("MulHom_map_dvd", "a_b_to_f_a_f_b", "Not an equality or iff proposition"),
    ("MonoidHom_map_dvd", "a_b_to_f_a_f_b", "Not an equality or iff proposition"),
    ("MonoidHom_mulExact_of_comp_eq_one_of_ker_le_range", "MulExact_f_g", "Not an equality or iff proposition"),
    ("MonoidHom_mulExact_of_comp_of_mem_range", "MulExact_f_g", "Not an equality or iff proposition"),
    ("LinearMap_exact_of_comp_eq_zero_of_ker_le_range", "Exact_f_g", "Not an equality or iff proposition"),
    ("LinearMap_exact_of_comp_of_mem_range", "Exact_f_g", "Not an equality or iff proposition"),
    ("LinearMap_exact_subtype_mkQ", "Exact_Submodule_subtype_Q_Submodule_mkQ_Q", "Not an equality or iff proposition"),
    ("LinearMap_exact_map_mkQ_range", "Exact_f_Submodule_mkQ_range_f", "Not an equality or iff proposition"),
    ("LinearMap_exact_subtype_ker_map", "Exact_Submodule_subtype_ker_g_g", "Not an equality or iff proposition"),
    ("LinearMap_surjective_range_liftQ", "Function_Surjective_range_f_liftQ_g_h", "Not an equality or iff proposition"),
    ("LinearMap_injective_range_liftQ_of_exact", "Function_Injective_range_f_liftQ_g_h_pipe_gt_mpr", "Not an equality or iff proposition"),
    ("MulEquiv_isField", "IsField_A", "Not an equality or iff proposition"),
    ("Field_toIsField", "IsField_R", "Not an equality or iff proposition"),
    ("Subfield_list_prod_mem", "forall_x_in_l_x_in_s_to_l_prod_in_s", "Not an equality or iff proposition"),
    ("Subfield_list_sum_mem", "forall_x_in_l_x_in_s_to_l_sum_in_s", "Not an equality or iff proposition"),
    ("Subfield_multiset_sum_mem", "forall_a_in_m_a_in_s_to_m_sum_in_s", "Not an equality or iff proposition"),
    ("Subfield_sum_mem", "i_in_t_f_i_in_s", "Not an equality or iff proposition"),
    ("RingHom_mem_fieldRange_self", "f_x_in_f_fieldRange", "Not an equality or iff proposition"),
    ("Subfield_isGLB_sInf", "IsGLB_S_sInf_S", "Not an equality or iff proposition"),
    ("Subfield_subset_closure", "s_sub_closure_s", "Not an equality or iff proposition"),
    ("Subfield_mem_closure_of_mem", "x_in_closure_s", "Not an equality or iff proposition"),
    ("Subfield_subring_closure_le", "Subring_closure_s_le_closure_s_toSubring", "Not an equality or iff proposition"),
    ("Subfield_notMem_of_notMem_closure", "P_notin_s", "Not an equality or iff proposition"),
    ("Subfield_closure_mono", "_unknown", "Empty proposition"),
    ("Subfield_closure_induction", "p_x_h", "Not an equality or iff proposition"),
    ("RingHom_rangeRestrictField_bijective", "Function_Bijective_rangeRestrictField_f", "Not an equality or iff proposition"),
    ("RingHom_eqOn_field_closure", "Set_EqOn_f_g_closure_s", "Not an equality or iff proposition"),
    ("Subfield_closure_preimage_le", "closure_f_inv_prime_s_le_closure_s_comap_f", "Not an equality or iff proposition"),
    ("Subfield_multiset_prod_mem", "forall_a_in_m_a_in_s_to_m_prod_in_s", "Not an equality or iff proposition"),
    ("Subfield_prod_mem", "i_in_t_f_i_in_s", "Not an equality or iff proposition"),
    ("SubfieldClass_nnratCast_mem", "q_colon_K_in_s", "Not an equality or iff proposition"),
    ("SubfieldClass_ratCast_mem", "q_colon_K_in_s", "Not an equality or iff proposition"),
    ("SubfieldClass_nnqsmul_mem", "q_x_in_s", "Not an equality or iff proposition"),
    ("SubfieldClass_qsmul_mem", "q_x_in_s", "Not an equality or iff proposition"),
    ("SubfieldClass_ofScientific_mem", "OfScientific_ofScientific_n_b_m_colon_K_in_s", "Not an equality or iff proposition"),
    ("Subfield_mul_mem", "x_in_s_to_y_in_s_to_x_star_y_in_s", "Not an equality or iff proposition"),
    ("Subfield_add_mem", "x_in_s_to_y_in_s_to_x_plus_y_in_s", "Not an equality or iff proposition"),
    ("Subfield_neg_mem", "x_in_s_to_minus_x_in_s", "Not an equality or iff proposition"),
    ("Subfield_sub_mem", "x_in_s_to_y_in_s_to_x_minus_y_in_s", "Not an equality or iff proposition"),
    ("Subfield_inv_mem", "x_in_s_to_xinv_in_s", "Not an equality or iff proposition"),
    ("Subfield_div_mem", "x_in_s_to_y_in_s_to_x_slash_y_in_s", "Not an equality or iff proposition"),
    ("Subfield_pow_mem", "x_pow_n_in_s", "Not an equality or iff proposition"),
    ("Subfield_zsmul_mem", "n_x_in_s", "Not an equality or iff proposition"),
    ("Subfield_intCast_mem", "n_colon_K_in_s", "Not an equality or iff proposition"),
    ("MonoidHom_surjective_of_surjective_of_surjective_of_injective", "Function_Surjective_i_2", "Not an equality or iff proposition"),
    ("MonoidHom_surjective_of_surjective_of_injective_of_left_exact", "Function_Surjective_i_1", "Not an equality or iff proposition"),
    ("MonoidHom_injective_of_surjective_of_injective_of_injective", "Function_Injective_i_3", "Not an equality or iff proposition"),
    ("MonoidHom_injective_of_surjective_of_injective_of_right_exact", "Function_Injective_i_3", "Not an equality or iff proposition"),
    ("MonoidHom_bijective_of_surjective_of_bijective_of_bijective_of_injective", "Function_Bijective_i_3", "Not an equality or iff proposition"),
    ("MonoidHom_bijective_of_bijective_of_injective_of_left_exact", "Function_Bijective_i_1", "Not an equality or iff proposition"),
    ("MonoidHom_bijective_of_surjective_of_bijective_of_right_exact", "Function_Bijective_i_3", "Not an equality or iff proposition"),
    ("LinearMap_surjective_of_surjective_of_surjective_of_injective", "Function_Surjective_i_2", "Not an equality or iff proposition"),
    ("LinearMap_surjective_of_surjective_of_injective_of_left_exact", "Function_Surjective_i_1", "Not an equality or iff proposition"),
    ("LinearMap_injective_of_surjective_of_injective_of_injective", "Function_Injective_i_3", "Not an equality or iff proposition"),
    ("LinearMap_injective_of_surjective_of_injective_of_right_exact", "Function_Injective_i_3", "Not an equality or iff proposition"),
    ("LinearMap_bijective_of_surjective_of_bijective_of_bijective_of_injective", "Function_Bijective_i_3", "Not an equality or iff proposition"),
    ("LinearMap_bijective_of_bijective_of_injective_of_left_exact", "Function_Bijective_i_1", "Not an equality or iff proposition"),
    ("LinearMap_bijective_of_surjective_of_bijective_of_right_exact", "Function_Bijective_i_3", "Not an equality or iff proposition"),
    ("FreeAlgebra_i_comp_lift", "lift_R_f_colon_FreeAlgebra_R_X_to_A_comp_i_R_eq_f", "Not an equality or iff proposition"),
    ("FreeAlgebra_lift_comp_i", "lift_R_g_colon_FreeAlgebra_R_X_to_A_comp_i_R_eq_g", "Not an equality or iff proposition"),
    ("FreeAlgebra_algebraMap_leftInverse", "Function_LeftInverse_algebraMapInv_algebraMap_R_lt_pipe_FreeAlgebra_R_X", "Not an equality or iff proposition"),
    ("FreeAlgebra_i_injective", "Function_Injective_i_R_colon_X_to_FreeAlgebra_R_X", "Not an equality or iff proposition"),
    ("FreeAlgebra_i_ne_algebraMap", "i_R_x_ne_algebraMap_R_r", "Not an equality or iff proposition"),
    ("FreeAlgebra_induction", "motive_a", "Not an equality or iff proposition"),
    ("FreeAlgebra_adjoin_range_i", "Algebra_adjoin_R_Set_range_i_R_colon_X_to_FreeAlgebra_R_X_eq_top", "Not an equality or iff proposition"),
    ("FreeAlgebra_cardinalMk_le_max_lift", "hash_FreeAlgebra_R_X_le_Cardinal_lift_v_hash_R_Cardinal_lift_u_hash_X_0", "Not an equality or iff proposition"),
    ("FreeAlgebra_cardinalMk_le_max", "hash_FreeAlgebra_R_X_le_hash_R_hash_X_0", "Not an equality or iff proposition"),
    ("Algebra_lift_cardinalMk_adjoin_le", "lift_u_hash_adjoin_R_s_le_lift_v_hash_R_lift_u_hash_s_0", "Not an equality or iff proposition"),
    ("Algebra_cardinalMk_adjoin_le", "hash_adjoin_R_s_le_hash_R_hash_s_0", "Not an equality or iff proposition"),
    ("MulAction_toPerm_injective", "Function_Injective_MulAction_toPerm_colon_a_to_Equiv_Perm_b", "Not an equality or iff proposition"),
    ("MulAction_bijective", "Function_Bijective_g_colon_b_to_b", "Not an equality or iff proposition"),
    ("MulAction_injective", "Function_Injective_g_colon_b_to_b", "Not an equality or iff proposition"),
    ("MulAction_surjective", "Function_Surjective_g_colon_b_to_b", "Not an equality or iff proposition"),
    ("MulAction_compHom_smul_def", "letI_colon_MulAction_E_G", "Not an equality or iff proposition"),
    ("MulAction_isPretransitive_compHom", "letI_colon_MulAction_E_G", "Not an equality or iff proposition"),
]
