"""Interpretation of Python's builtin types in the motive framework.

Every Python type is mapped to a Sort, and every type's methods are
mapped to TypedOp specifications with precise input/output sorts,
refinements, and effects.

This is the ground truth for what sort each Python value inhabits.
"""

from __future__ import annotations

from deppy.motive.sorts import Sort
from deppy.motive.operations import Effect, Refinement


# ── Builtin name → Sort mapping ──────────────────────────────────

BUILTIN_NAME_SORTS = {
    # Type constructors
    'int': Sort.NUM,
    'float': Sort.NUM,
    'complex': Sort.NUM,
    'bool': Sort.BOOL,
    'str': Sort.STR,
    'bytes': Sort.STR,
    'bytearray': Sort.STR,
    'list': Sort.SEQ,
    'tuple': Sort.SEQ,
    'dict': Sort.MAP,
    'set': Sort.SET,
    'frozenset': Sort.SET,
    'range': Sort.SEQ,
    'memoryview': Sort.SEQ,
    'slice': Sort.TOP,
    'type': Sort.FUNC,
    'object': Sort.TOP,
    'property': Sort.FUNC,
    'staticmethod': Sort.FUNC,
    'classmethod': Sort.FUNC,
    'super': Sort.TOP,

    # Constants
    'True': Sort.BOOL,
    'False': Sort.BOOL,
    'None': Sort.NONE,
    'Ellipsis': Sort.TOP,
    'NotImplemented': Sort.TOP,
    '__name__': Sort.STR,
    '__file__': Sort.STR,
    '__doc__': Sort.STR,

    # Exception classes → TOP
    'Exception': Sort.TOP,
    'ValueError': Sort.TOP,
    'TypeError': Sort.TOP,
    'KeyError': Sort.TOP,
    'IndexError': Sort.TOP,
    'AttributeError': Sort.TOP,
    'RuntimeError': Sort.TOP,
    'StopIteration': Sort.TOP,
    'StopAsyncIteration': Sort.TOP,
    'ArithmeticError': Sort.TOP,
    'LookupError': Sort.TOP,
    'OSError': Sort.TOP,
    'IOError': Sort.TOP,
    'FileNotFoundError': Sort.TOP,
    'PermissionError': Sort.TOP,
    'NotImplementedError': Sort.TOP,
    'ZeroDivisionError': Sort.TOP,
    'OverflowError': Sort.TOP,
    'FloatingPointError': Sort.TOP,
    'UnicodeError': Sort.TOP,
    'UnicodeDecodeError': Sort.TOP,
    'UnicodeEncodeError': Sort.TOP,
    'AssertionError': Sort.TOP,
    'NameError': Sort.TOP,
    'UnboundLocalError': Sort.TOP,
    'MemoryError': Sort.TOP,
    'RecursionError': Sort.TOP,
    'SystemError': Sort.TOP,
    'SystemExit': Sort.TOP,
    'KeyboardInterrupt': Sort.TOP,
    'GeneratorExit': Sort.TOP,
    'ImportError': Sort.TOP,
    'ModuleNotFoundError': Sort.TOP,
    'SyntaxError': Sort.TOP,
    'IndentationError': Sort.TOP,
    'TabError': Sort.TOP,

    # Common stdlib names
    'math': Sort.TOP,
    'os': Sort.TOP,
    'sys': Sort.TOP,
    're': Sort.TOP,
    'json': Sort.TOP,
    'collections': Sort.TOP,
    'itertools': Sort.TOP,
    'functools': Sort.TOP,
    'typing': Sort.TOP,
    'dataclasses': Sort.TOP,
    'abc': Sort.TOP,
    'io': Sort.TOP,
    'copy': Sort.TOP,
    'heapq': Sort.TOP,
    'bisect': Sort.TOP,
    'operator': Sort.TOP,
    'decimal': Sort.TOP,
    'fractions': Sort.TOP,
    'random': Sort.TOP,
    'string': Sort.TOP,
    'textwrap': Sort.TOP,
    'enum': Sort.TOP,
    'pathlib': Sort.TOP,

    # Common third-party
    'defaultdict': Sort.MAP,
    'OrderedDict': Sort.MAP,
    'Counter': Sort.MAP,
    'deque': Sort.SEQ,
    'namedtuple': Sort.FUNC,
    'ChainMap': Sort.MAP,
}

# ── Method name → result Sort mapping ────────────────────────────

METHOD_RESULT_SORTS = {
    # ── list methods ──
    'append': Sort.NONE,
    'extend': Sort.NONE,
    'insert': Sort.NONE,
    'remove': Sort.NONE,
    'pop': Sort.TOP,
    'clear': Sort.NONE,
    'index': Sort.NUM,
    'count': Sort.NUM,
    'sort': Sort.NONE,
    'reverse': Sort.NONE,
    'copy': Sort.SEQ,

    # ── dict methods ──
    'get': Sort.TOP,
    'keys': Sort.ITER,
    'values': Sort.ITER,
    'items': Sort.ITER,
    'setdefault': Sort.TOP,
    'update': Sort.NONE,
    'popitem': Sort.SEQ,

    # ── set methods ──
    'add': Sort.NONE,
    'discard': Sort.NONE,
    'union': Sort.SET,
    'intersection': Sort.SET,
    'difference': Sort.SET,
    'symmetric_difference': Sort.SET,
    'issubset': Sort.BOOL,
    'issuperset': Sort.BOOL,
    'isdisjoint': Sort.BOOL,
    'intersection_update': Sort.NONE,
    'difference_update': Sort.NONE,
    'symmetric_difference_update': Sort.NONE,

    # ── str methods ──
    'join': Sort.STR,
    'split': Sort.SEQ,
    'rsplit': Sort.SEQ,
    'splitlines': Sort.SEQ,
    'strip': Sort.STR,
    'lstrip': Sort.STR,
    'rstrip': Sort.STR,
    'replace': Sort.STR,
    'find': Sort.NUM,
    'rfind': Sort.NUM,
    'lower': Sort.STR,
    'upper': Sort.STR,
    'title': Sort.STR,
    'capitalize': Sort.STR,
    'swapcase': Sort.STR,
    'casefold': Sort.STR,
    'center': Sort.STR,
    'ljust': Sort.STR,
    'rjust': Sort.STR,
    'zfill': Sort.STR,
    'encode': Sort.STR,
    'decode': Sort.STR,
    'format': Sort.STR,
    'format_map': Sort.STR,
    'startswith': Sort.BOOL,
    'endswith': Sort.BOOL,
    'isalpha': Sort.BOOL,
    'isalnum': Sort.BOOL,
    'isdigit': Sort.BOOL,
    'isnumeric': Sort.BOOL,
    'isdecimal': Sort.BOOL,
    'isspace': Sort.BOOL,
    'istitle': Sort.BOOL,
    'isupper': Sort.BOOL,
    'islower': Sort.BOOL,
    'isidentifier': Sort.BOOL,
    'isprintable': Sort.BOOL,
    'isascii': Sort.BOOL,
    'expandtabs': Sort.STR,
    'maketrans': Sort.MAP,
    'translate': Sort.STR,
    'partition': Sort.SEQ,
    'rpartition': Sort.SEQ,

    # ── bytes/bytearray ──
    'hex': Sort.STR,
    'fromhex': Sort.STR,

    # ── deque ──
    'appendleft': Sort.NONE,
    'popleft': Sort.TOP,
    'extendleft': Sort.NONE,
    'rotate': Sort.NONE,
    'maxlen': Sort.NUM,

    # ── Counter ──
    'most_common': Sort.SEQ,
    'elements': Sort.ITER,
    'subtract': Sort.NONE,
    'total': Sort.NUM,

    # ── io ──
    'read': Sort.STR,
    'readline': Sort.STR,
    'readlines': Sort.SEQ,
    'write': Sort.NUM,
    'writelines': Sort.NONE,
    'seek': Sort.NUM,
    'tell': Sort.NUM,
    'close': Sort.NONE,
    'flush': Sort.NONE,
    'getvalue': Sort.STR,

    # ── general ──
    '__len__': Sort.NUM,
    '__iter__': Sort.ITER,
    '__next__': Sort.TOP,
    '__contains__': Sort.BOOL,
    '__getitem__': Sort.TOP,
    '__setitem__': Sort.NONE,
    '__delitem__': Sort.NONE,
    '__eq__': Sort.BOOL,
    '__ne__': Sort.BOOL,
    '__lt__': Sort.BOOL,
    '__le__': Sort.BOOL,
    '__gt__': Sort.BOOL,
    '__ge__': Sort.BOOL,
    '__hash__': Sort.NUM,
    '__repr__': Sort.STR,
    '__str__': Sort.STR,
    '__bool__': Sort.BOOL,
    '__int__': Sort.NUM,
    '__float__': Sort.NUM,
    '__abs__': Sort.NUM,
    '__neg__': Sort.NUM,
    '__pos__': Sort.NUM,
    '__add__': Sort.TOP,
    '__sub__': Sort.NUM,
    '__mul__': Sort.TOP,
    '__truediv__': Sort.NUM,
    '__floordiv__': Sort.NUM,
    '__mod__': Sort.NUM,
    '__pow__': Sort.NUM,
    '__and__': Sort.TOP,
    '__or__': Sort.TOP,
    '__xor__': Sort.TOP,
    '__lshift__': Sort.NUM,
    '__rshift__': Sort.NUM,
    '__invert__': Sort.NUM,
    '__call__': Sort.TOP,
    '__enter__': Sort.TOP,
    '__exit__': Sort.NONE,
}

# ── Type operation specifications ─────────────────────────────────
#
# Each entry: (method_name, obj_sort, arg_sorts) → (op_name, result_sort, refinements, effect)

INT_OPS = {
    'bit_length': ('Num.bit_length', Sort.NUM, frozenset(), Effect.PURE),
    'bit_count': ('Num.bit_count', Sort.NUM, frozenset(), Effect.PURE),
    'to_bytes': ('Num.to_bytes', Sort.STR, frozenset(), Effect.PURE),
    'from_bytes': ('Num.from_bytes', Sort.NUM, frozenset(), Effect.PURE),
    'conjugate': ('Num.conjugate', Sort.NUM, frozenset(), Effect.PURE),
    'denominator': ('Num.denominator', Sort.NUM, frozenset(), Effect.PURE),
    'numerator': ('Num.numerator', Sort.NUM, frozenset(), Effect.PURE),
    'real': ('Num.real', Sort.NUM, frozenset(), Effect.PURE),
    'imag': ('Num.imag', Sort.NUM, frozenset(), Effect.PURE),
}

FLOAT_OPS = {
    'is_integer': ('Num.is_integer', Sort.BOOL, frozenset(), Effect.PURE),
    'as_integer_ratio': ('Num.as_integer_ratio', Sort.SEQ, frozenset(), Effect.PURE),
    'hex': ('Num.hex', Sort.STR, frozenset(), Effect.PURE),
    'fromhex': ('Num.fromhex', Sort.NUM, frozenset(), Effect.PURE),
}

STR_OPS = {
    'join': ('Str.join', Sort.STR, frozenset({Refinement.COMMUTATIVE}), Effect.PURE),
    'split': ('Str.split', Sort.SEQ, frozenset(), Effect.PURE),
    'rsplit': ('Str.rsplit', Sort.SEQ, frozenset(), Effect.PURE),
    'splitlines': ('Str.splitlines', Sort.SEQ, frozenset(), Effect.PURE),
    'strip': ('Str.strip', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'lstrip': ('Str.lstrip', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'rstrip': ('Str.rstrip', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'replace': ('Str.replace', Sort.STR, frozenset(), Effect.PURE),
    'find': ('Str.find', Sort.NUM, frozenset(), Effect.PURE),
    'rfind': ('Str.rfind', Sort.NUM, frozenset(), Effect.PURE),
    'index': ('Str.index', Sort.NUM, frozenset(), Effect.PURE),
    'rindex': ('Str.rindex', Sort.NUM, frozenset(), Effect.PURE),
    'count': ('Str.count', Sort.NUM, frozenset(), Effect.PURE),
    'lower': ('Str.lower', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'upper': ('Str.upper', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'title': ('Str.title', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'capitalize': ('Str.capitalize', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'swapcase': ('Str.swapcase', Sort.STR, frozenset(), Effect.PURE),
    'casefold': ('Str.casefold', Sort.STR, frozenset({Refinement.IDEMPOTENT}), Effect.PURE),
    'center': ('Str.center', Sort.STR, frozenset(), Effect.PURE),
    'ljust': ('Str.ljust', Sort.STR, frozenset(), Effect.PURE),
    'rjust': ('Str.rjust', Sort.STR, frozenset(), Effect.PURE),
    'zfill': ('Str.zfill', Sort.STR, frozenset(), Effect.PURE),
    'encode': ('Str.encode', Sort.STR, frozenset(), Effect.PURE),
    'format': ('Str.format', Sort.STR, frozenset(), Effect.PURE),
    'format_map': ('Str.format_map', Sort.STR, frozenset(), Effect.PURE),
    'startswith': ('Str.startswith', Sort.BOOL, frozenset(), Effect.PURE),
    'endswith': ('Str.endswith', Sort.BOOL, frozenset(), Effect.PURE),
    'isalpha': ('Str.isalpha', Sort.BOOL, frozenset(), Effect.PURE),
    'isalnum': ('Str.isalnum', Sort.BOOL, frozenset(), Effect.PURE),
    'isdigit': ('Str.isdigit', Sort.BOOL, frozenset(), Effect.PURE),
    'isnumeric': ('Str.isnumeric', Sort.BOOL, frozenset(), Effect.PURE),
    'isdecimal': ('Str.isdecimal', Sort.BOOL, frozenset(), Effect.PURE),
    'isspace': ('Str.isspace', Sort.BOOL, frozenset(), Effect.PURE),
    'istitle': ('Str.istitle', Sort.BOOL, frozenset(), Effect.PURE),
    'isupper': ('Str.isupper', Sort.BOOL, frozenset(), Effect.PURE),
    'islower': ('Str.islower', Sort.BOOL, frozenset(), Effect.PURE),
    'isidentifier': ('Str.isidentifier', Sort.BOOL, frozenset(), Effect.PURE),
    'isprintable': ('Str.isprintable', Sort.BOOL, frozenset(), Effect.PURE),
    'isascii': ('Str.isascii', Sort.BOOL, frozenset(), Effect.PURE),
    'expandtabs': ('Str.expandtabs', Sort.STR, frozenset(), Effect.PURE),
    'maketrans': ('Str.maketrans', Sort.MAP, frozenset(), Effect.PURE),
    'translate': ('Str.translate', Sort.STR, frozenset(), Effect.PURE),
    'partition': ('Str.partition', Sort.SEQ, frozenset(), Effect.PURE),
    'rpartition': ('Str.rpartition', Sort.SEQ, frozenset(), Effect.PURE),
    'removeprefix': ('Str.removeprefix', Sort.STR, frozenset(), Effect.PURE),
    'removesuffix': ('Str.removesuffix', Sort.STR, frozenset(), Effect.PURE),
}

LIST_OPS = {
    'append': ('Seq.push', Sort.NONE, frozenset(), Effect.MUTATE),
    'extend': ('Seq.extend', Sort.NONE, frozenset(), Effect.MUTATE),
    'insert': ('Seq.insert', Sort.NONE, frozenset(), Effect.MUTATE),
    'remove': ('Seq.remove', Sort.NONE, frozenset(), Effect.MUTATE),
    'pop': ('Seq.pop', Sort.TOP, frozenset(), Effect.MUTATE),
    'clear': ('Seq.clear', Sort.NONE, frozenset(), Effect.MUTATE),
    'index': ('Seq.index', Sort.NUM, frozenset(), Effect.PURE),
    'count': ('Seq.count', Sort.NUM, frozenset(), Effect.PURE),
    'sort': ('Seq.sort', Sort.NONE, frozenset({Refinement.SORTED}), Effect.MUTATE),
    'reverse': ('Seq.reverse', Sort.NONE, frozenset({Refinement.REVERSED}), Effect.MUTATE),
    'copy': ('Seq.copy', Sort.SEQ, frozenset(), Effect.ALLOCATE),
}

DICT_OPS = {
    'get': ('Map.get', Sort.TOP, frozenset(), Effect.PURE),
    'keys': ('Map.keys', Sort.ITER, frozenset(), Effect.PURE),
    'values': ('Map.values', Sort.ITER, frozenset(), Effect.PURE),
    'items': ('Map.items', Sort.ITER, frozenset(), Effect.PURE),
    'setdefault': ('Map.setdefault', Sort.TOP, frozenset(), Effect.MUTATE),
    'update': ('Map.update', Sort.NONE, frozenset(), Effect.MUTATE),
    'pop': ('Map.pop', Sort.TOP, frozenset(), Effect.MUTATE),
    'popitem': ('Map.popitem', Sort.SEQ, frozenset(), Effect.MUTATE),
    'clear': ('Map.clear', Sort.NONE, frozenset(), Effect.MUTATE),
    'copy': ('Map.copy', Sort.MAP, frozenset(), Effect.ALLOCATE),
    'fromkeys': ('Map.fromkeys', Sort.MAP, frozenset(), Effect.ALLOCATE),
}

SET_OPS = {
    'add': ('Set.add', Sort.NONE, frozenset(), Effect.MUTATE),
    'discard': ('Set.discard', Sort.NONE, frozenset(), Effect.MUTATE),
    'remove': ('Set.remove', Sort.NONE, frozenset(), Effect.MUTATE),
    'pop': ('Set.pop', Sort.TOP, frozenset(), Effect.MUTATE),
    'clear': ('Set.clear', Sort.NONE, frozenset(), Effect.MUTATE),
    'union': ('Set.union', Sort.SET, frozenset({Refinement.COMMUTATIVE, Refinement.ASSOCIATIVE}), Effect.PURE),
    'intersection': ('Set.intersection', Sort.SET, frozenset({Refinement.COMMUTATIVE, Refinement.ASSOCIATIVE}), Effect.PURE),
    'difference': ('Set.difference', Sort.SET, frozenset(), Effect.PURE),
    'symmetric_difference': ('Set.symmetric_difference', Sort.SET, frozenset({Refinement.COMMUTATIVE}), Effect.PURE),
    'issubset': ('Set.issubset', Sort.BOOL, frozenset(), Effect.PURE),
    'issuperset': ('Set.issuperset', Sort.BOOL, frozenset(), Effect.PURE),
    'isdisjoint': ('Set.isdisjoint', Sort.BOOL, frozenset({Refinement.COMMUTATIVE}), Effect.PURE),
    'intersection_update': ('Set.intersection_update', Sort.NONE, frozenset(), Effect.MUTATE),
    'difference_update': ('Set.difference_update', Sort.NONE, frozenset(), Effect.MUTATE),
    'symmetric_difference_update': ('Set.symmetric_difference_update', Sort.NONE, frozenset(), Effect.MUTATE),
    'copy': ('Set.copy', Sort.SET, frozenset(), Effect.ALLOCATE),
}

DEQUE_OPS = {
    'append': ('Seq.push', Sort.NONE, frozenset(), Effect.MUTATE),
    'appendleft': ('Seq.push_front', Sort.NONE, frozenset(), Effect.MUTATE),
    'pop': ('Seq.pop', Sort.TOP, frozenset(), Effect.MUTATE),
    'popleft': ('Seq.pop_front', Sort.TOP, frozenset(), Effect.MUTATE),
    'extend': ('Seq.extend', Sort.NONE, frozenset(), Effect.MUTATE),
    'extendleft': ('Seq.extend_front', Sort.NONE, frozenset(), Effect.MUTATE),
    'rotate': ('Seq.rotate', Sort.NONE, frozenset(), Effect.MUTATE),
    'clear': ('Seq.clear', Sort.NONE, frozenset(), Effect.MUTATE),
    'copy': ('Seq.copy', Sort.SEQ, frozenset(), Effect.ALLOCATE),
    'count': ('Seq.count', Sort.NUM, frozenset(), Effect.PURE),
    'index': ('Seq.index', Sort.NUM, frozenset(), Effect.PURE),
    'insert': ('Seq.insert', Sort.NONE, frozenset(), Effect.MUTATE),
    'remove': ('Seq.remove', Sort.NONE, frozenset(), Effect.MUTATE),
    'reverse': ('Seq.reverse', Sort.NONE, frozenset({Refinement.REVERSED}), Effect.MUTATE),
    'maxlen': ('Seq.maxlen', Sort.NUM, frozenset(), Effect.PURE),
}

COUNTER_OPS = {
    'most_common': ('Map.most_common', Sort.SEQ, frozenset({Refinement.SORTED}), Effect.PURE),
    'elements': ('Map.elements', Sort.ITER, frozenset(), Effect.PURE),
    'subtract': ('Map.subtract', Sort.NONE, frozenset(), Effect.MUTATE),
    'update': ('Map.update', Sort.NONE, frozenset(), Effect.MUTATE),
    'total': ('Map.total', Sort.NUM, frozenset(), Effect.PURE),
}

# Unified lookup: method → (op_name, result_sort, refinements, effect)
ALL_METHOD_OPS = {}
for table in [INT_OPS, FLOAT_OPS, STR_OPS, LIST_OPS, DICT_OPS, SET_OPS,
              DEQUE_OPS, COUNTER_OPS]:
    ALL_METHOD_OPS.update(table)
